### ISSUE TITLE
Files with identical hashes open wrong file

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#101]
Minor issue with the new hash, should be easily fixed!

When you have duplicates of the same file, and they have the same hash, clicking on one to open it will opened the "last" version of the file! This is because `openVideo(hash)` takes a hash value, so it picks the last one with the matching hash, as they all share the same one!

To fix this, `openVideo()` should take the video path instead! 👍

**Comment by cal2195** [comment]
Am I correct that we can remove the `fileMap` now, and just use the `index` for everything?

**Comment by whyboris** [comment]
I think that's the case -- the index also coincides with the index in the array.

A tad of history: in version 1.0.0 - 1.3.0 there was a number that used to refer to the screenshot file name. But as you removed files and added new ones, the indexes would become misaligned, so I created a `fileMap` which would be generated when the app ran. Now that we insert the unique index when the _vha_ file is opened, I'm 99.9% sure the `fileMap` is safe to remove 👌 

One quick spot-check to do after removing it: do a file name search to filter out most of the videos, click on any of the resulting videos. If the correct file opens, we likely have no bugs 😅

**Comment by cal2195** [comment]
PR ready to fix this and the same issue for tagging when #116 merges! 👍
