### ISSUE TITLE
Thumbnail Generation Issues

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#103]
Some files are still having problems generating thumbnails and/or video previews! 👎 

This issue is to track down the (likely multiple) issues!

Problematic files:
1) .wmv files - Some of these files have their 0th stream be a mjpeg with 90k fps??
We should be using the 2nd stream, wmv. Will have to see if it's all wmv, or just some badly encoded ones...

I will add more details as I deal with each problematic file!

**Comment by whyboris** [comment]
Thank you for your continued debugging work. 

I wonder if there's anything to be learned by looking at how [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) does things? I used the library before and it seemed to handle all the edge cases (as far as I can tell).

Is there a chance there is no universal way to ask `ffmpeg` to extract screenshots without having to resort to checking various cases?

**Comment by cal2195** [comment]
Good thinking, Batman! 👍 Looks like they have some more logic that should fix issue 1. up there! 🎉 

I'll look into implementing the edge-cases they deal with! 👍

**Comment by whyboris** [comment]
I'm _ok_ with leaving edge cases as is. If there's just a way not to have the app crash while extracting (whenever an error arises) we're good to go 🌊

**Comment by cal2195** [comment]
Fixed with #128! 🎉
