### ISSUE TITLE
New library won't show videos until reload

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#110]
Just noticed, that new libraries created with the wizard import the videos, but doesn't display anything until you reload the library or app! 😖 

Not sure the cause yet.. could be the new sorting options?

**Comment by whyboris** [comment]
I think it's been happening since we added the images to be _background-url_ CSS rather than _<img>_ tag. It affects just-about every gallery item.

It's something I plan to look into closer to before v2.0.0 release. Feel free to look into it yourself if you're interested 😄

**Comment by whyboris** [comment]
I may have misunderstood you -- I think you are describing that _no gallery items show up_ when importing a new folder (not even the black placeholders!). I thought you meant the placeholders are there but the images don't appear as the new _jpg_ files are extracted/created.

Will investigate 🔍

**Comment by cal2195** [comment]
An observation while working on something else - this appears to be related to the resolution/duration filter?

Disabling it makes them appear...

**Comment by whyboris** [comment]
Confirming -- when the _duration_ filter is on, nothing is displayed in the gallery.

I'll be moving it to its own _div_ (currently `DURATION WIP` toggled with the new _hourglass_ icon) - I'll see if I can fix it 👍

**Comment by whyboris** [comment]
I think I found the problem:

https://github.com/whyboris/Video-Hub-App/blob/master/src/app/components/home/home.component.html#L846

```
lengthFilterPipe: settingsButtons['resolutionFilter'].toggled
```

The length filter was using the resolution filter toggle 😅

**Comment by whyboris** [comment]
The PR #150 may have not closed this bug -- I'm unsure, but if the bug persists, I'd rather track it with a new issue.
