### ISSUE TITLE
Adding new icons

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#114]
We have too many repeat-us icons (obviously, because previously adding icons was impossible without rebuilding the underlying font file - which without all the dependencies and custom SVGs I created couldn't be done without me 😢 ).

Adding icons is very easy now - just add a definition to the `svg-definitions.component.html` file, name the icon something unique and descriptive, and use it! E.g. if you name the icon `cool-icon` you'll be able to, anywhere in the app:
```html
<app-icon [icon]="'cool-icon'"></app-icon>
```
🚀 

Icon changes and additions are welcome 🎉 

Please make sure the icon is built on a 15 x 15 px grid, is centered, and is generally about 3-4 pixels away from edges (please see other icons and how they are designed).

I'll be creating some more icons, but any volunteers are welcome 🥇

**Comment by cal2195** [comment]
Do you have any recommendations for software to create such icons? 💾 

I'm feeling we _really_ need different icons for each thing - very hard to see what's what in the main bar... I wonder if it's possible to decrease the time it takes for a tooltip to appear as well... ❓

**Comment by whyboris** [comment]
To create icons I used _Adobe Illustrator_. There are many other pieces of software that will do well:
https://alternativeto.net/software/adobe-illustrator/
There are even websites online that can do it.

I also added instructions: https://github.com/whyboris/Video-Hub-App/tree/master/src/app/components/home/icon

Looks like we can't adjust how fast the tooltip appears: 
https://stackoverflow.com/questions/9150796/change-how-fast-title-attributes-tooltip-appears
But we can implement a custom tooltip if we'd like.

**Comment by whyboris** [comment]
I'm also going to experiment adding an accent color to some icons - might help 👍 

I was considering allowing for larger icons in the ribbon (via a setting), but there would be quite a lot of code to change that I'd rather not spend time on now. The best solution to me seems the `zoom` setting that increases everything in the UI.

**Comment by whyboris** [comment]
Definitely adding & changing icons -- though likely at the latest stage, once all the code/functionality is ready.

Commenting just to confirm so no one is worried 😉 

If anyone is really into icon design, let's coordinate 👍

**Comment by whyboris** [comment]
😅  Finally on it -- planning to finish by the end of this weekend 🐌
