### ISSUE TITLE
Clip gallery fixes

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#115]
Two minor possible improvements to the video gallery (with live video previews) 

- Stop playing videos when the app is minimized
- Add a mute button (on by default) so hovering over a video does not play the audio

While we could simply not extract audio (it ends up choppy since the clips are short and jump between scenes), but since we already have the audio extracted (a freebie!) we may as well just have a mute button that is on by default. Thoughts? 😸

**Comment by cal2195** [comment]
I agree about the audio mute button! 👍 Was already meant to be added, but the `muted` attribute didn't work afaik... We can just use JS instead! 💯
