### ISSUE TITLE
Auto update/notification

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#12]
It would be nice to have to option to see if there are any new updates available, possibly on launch.

Making it as easy as possible for people who have purchased the app to update would be great! 👍

**Comment by whyboris** [comment]
I've added this feature -- in the settings at the bottom, you can now click on "check for new version" to see if a new version is available.

Currently it's a very simple API call to https://my.videohubapp.com/version.php -- and if the string is different, the app claims "new version available" 😅 

I'd rather not make the check automatic 🤷
