### ISSUE TITLE
Display folder path in other views

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#122]
If the user has the setting toggled, show the _folder path_ not just in the _file view_ but in all other views 😁 

Creating the issue for tracking - I have the feature first draft ready with _thumbnails_ view ✅

**Comment by whyboris** [comment]
Will be closed with #123 🐉

**Comment by cal2195** [comment]
This can probably be closed with #166! 😄

**Comment by whyboris** [comment]
Thank you Cal for #166 🙇
