### ISSUE TITLE
Setting the star rating resorts the array!

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#126]
If you set a star rating, the array is refiltered! This is especially a problem with the Random view, as the items are re-randomised! 👎 

Possibly reordering the filtering, or using a seed for the randomness might work?

**Comment by whyboris** [comment]
Thank you -- I'll investigate a solution.

When clicking the star rating a method updates the `finalArray` with the data, but that doesn't propagate to the view, so I hacked it to refresh the view. Looks like a better way to go is to have a fake variable inside the element that toggles the view update (I think I had it that way for a bit). I suspect it will be a quick fix.

**Comment by whyboris** [comment]
Will look at it later this week.  Will also: 
- [ ] add a star icon
- [ ] update app to allow 5 stars max ⭐️ ⭐️ ⭐️ ⭐️ ⭐️
