### ISSUE TITLE
Thumbnails don't show up if the path to the vha file has a space in it

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#131]
Thumbnails also don't show up if:
- [ ] The path to the vha file has a space in it!

Reopening this issue as it's shown up again! 👍 

With mac, this is fixed with `encodeURI()`, but it seems (?) Windows can't handle `%20` in file names?

Maybe surrounding the path with quotes could help... investigation needed! 🔍

**Comment by whyboris** [comment]
Since I have both a Windows and a Mac machine I'll look into it 👍

**Comment by whyboris** [comment]
I'll look into it sometime this week and hopefully solve it without resorting to a hack: filling in the space character in the hub name with a `-` :trollface:

**Comment by cal2195** [comment]
I identified a second issue which might be easy to fix at the same time - (silly) Windows treats the file string funny, and takes the `\` to mean an escape code! 😢 

This means that a path like `D:\Files\...` is taken as `D: iles\...`
(`\f` being form feed https://en.wikipedia.org/wiki/Page_break)

Encoding the string, or escaping everything should fix both issues! 👍

**Comment by cal2195** [comment]
> I'll look into it sometime this week and hopefully solve it without resorting to a hack: filling in the space character in the hub name with a `-` :trollface:

This won't work, unless you plan on replacing all spaces in the entire path to the file as well... - :trollface:

**Comment by cal2195** [comment]
Damn, this issue is going to be trickier than I thought - it also includes using a vha file created on one system, on another system... 😢 

Linux/Mac using `/` as a path delimiter, but Windows uses `\` - This means if you create on one, but then load on another, the saved paths aren't going to match `path.sep`! 👎 

Looking at [this](https://stackoverflow.com/a/31976060), it seems the best option would be to convert Windows `\` to `/` (it's used in the urls anyway), and then we can always assume folders are separated by `/` - I think this should work for opening files too.

Only problem is any libraries created on Windows will need to be rescanned - thumbnails should be safe! 👍 

Are you okay with this?

**Comment by whyboris** [comment]
I think I understand your description of the solution you describe. Could you just clarify what you mean by:
> Only problem is any libraries created on Windows will need to be rescanned - thumbnails should be safe!
Meaning that after this change, any .vha file you create on Windows will work fine, but any old .vha file will not?

If so -- no problem at all -- version 2.0 is _all-breaking-changes_ (vha files, settings, etc - as if it's a separate app from before) 🙆‍♂️

**Comment by cal2195** [comment]
I was referring to `.vha` files created using a recent git master (most likely just you and I), should work with a simple meta regen! 😄 Old files won't work anyway - thoughts on #168?

**Comment by whyboris** [comment]
Seems like if the a folder is capitalized, the app also isn't able to show anything in thumbnail view (`background-image` URL ends up garbled, e.g. rather than `C:/Boris/` it has `C:/%0Boris/`; meanwhile it works with a lowercase folder, e.g `C;/temp/` becomes `C;temp/` and still works :trollface:
