### ISSUE TITLE
Clean up and speed up sorting.pipe.ts

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#141]
- consolidate the code (keep it _DRY_)
- possibly handle _undefined_ values
- investigate if subtraction 
    (`y.duration - x.duration;`)
    is slower than comparison
    (`y.duration` > `x.duration`).
- after testing with > 1,000 videos consider _LSD [Radix Sort](https://www.cs.usfca.edu/~galles/visualization/RadixSort.html)_ or something similar (suggestions welcome!)
- consider returning only at most 100 results when sorting (writing a custom sort will speed up the sorting considerably!)

**Comment by whyboris** [comment]
Also in the _settings menu_ add toggles for hiding some of the sorting options (no need to sort by _year_ if a user doesn't add the _year_ meta tag!)

**Comment by whyboris** [comment]
Looks like conditionals are better:
```
function sort1(x, y) {
  return x - y;
}
```
> ~0.5ms 

```
function sort2(x, y) {
  if (x > y) {
    return 1;
  } else if (x === y) {
    return 0;
  } else {
    return -1;
  }
}
```
> ~0.08ms

tested with arrays of 1000 items 👍 
```
console.time();
sampleArrayOfNumbers.sort(sort1);
console.timeEnd();
```

**Comment by cal2195** [comment]
Ha, that surprises me! 😄 Must be some under the hood optimisations! 👍

**Comment by whyboris** [comment]
I had the intuition because it's likely easier for JS to check whether one integer is larger than another, than to compute the exact difference. I'm glad that under the hood the comparison operator is smarter than a subtraction of the two :trollface:

**Comment by whyboris** [comment]
A clever use of pipes I found: https://stackoverflow.com/a/43310428/5017391
A pipe will have a callback as an input (which is provided by a component) 🎉 
Maybe useful sometime in this app 🤔

**Comment by cal2195** [comment]
I don't understand what you mean by:
>     * consider returning only at most 100 results when sorting (writing a custom sort will speed up the sorting considerably!)

I'm also a little wary of over optimising and introducing a lot of complexity with custom sorts - is there not a native way to use built in sorting (quicksort?) and just give it the comparison? Or is this already a thing?

**Comment by whyboris** [comment]
I suspect we won't need any optimizations really -- everything is fast enough and there are bigger problems to address first. 

I thought that perhaps, when people filter by any attribute, it's unlikely they care about the _middle_ of the distribution -- they just want _the top N_ items. But arbitrarily cutting it off at 100 may be silly (only reasonable if sort takes much too long with numbers less than 3,000 videos).

I'll likely not have a cutoff :)

**Comment by whyboris** [comment]
Closed with https://github.com/whyboris/Video-Hub-App/commit/7412c8e6ee6da54c857ce74ccd557b10a0886597 -- speeding up sorting by comparison `>` rather than subtraction 🚀
