### ISSUE TITLE
Can't play videos, or see information until reload after importing

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#144]
Seems to be a new bug - if you import a new library, the video details are undefined, and you can't play any video. Reloading the app and loading the vha file fixes this - looks like the finalArray is undefined for some reason... 😕

**Comment by whyboris** [comment]
Great catch - thank you!

I think I've noticed that the metadata is incorrect at first (showing 0 for file size, etc) ... might be misremembering.

My brother is visiting for 2 months so now I spend more family time than coding time ... I've not forgotten about this project 😅

**Comment by cal2195** [comment]
Haha, found the issue! 👍 In `sendFinalResultsHome`, we add the temporary fields to the array (good), and then we write the file to disk, which then proceeds to strip all our temporary fields out again (bad)! 😂 And this is saved back to the final array, so the app then has no temporary fields!

When you just load an existing library, the write vha function isn't called, so the fields don't get stripped out! 👍
