### ISSUE TITLE
Possibly seperate out user generated metadata from file generated metadata?

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#145]
I'm trying to decide what the best option for updating metadata of files, while keep user generated metadata like tags, ratings, etc., and also preventing accidental corruption as much as possible!

One solution would be to keep the user generated content in a separate file, indexed by the file hash - this way if the library got corrupted, you could just make a new library of the same name, and keep both metadata and thumbnails!

Thoughts? 💡

**Comment by whyboris** [comment]
Interesting. That could work, though I wonder if we could just create `filename.vha.backup` file every once in a while ? Would be easier ... 

How many times have you run into a file getting corrupted? Hasn't happened to me once yet (though I've not been working with it much lately).

**Comment by whyboris** [comment]
Seems like that could be an _optional_ feature -- that is if you're doing something advanced like the _Daemon_ mode (see #161).

I think for convenience, the metadata will stay all in one file, at the very least in version 2 (coming within 2 weeks). It seems like additional logic could just check if some `filename.vha2-metadata` file is present -- or for the app, if you're running it along with the _daemon_ mode, the metadata would be copied over just in case into some `.vha2-metadata` file -- or some similar arrangement.

I'm closing this issue to clean up the _Issues_ for the release. I'm not saying 'no' to the idea. @cal2195 Feel free to re-open with a comment or create a new issue 👌
