### ISSUE TITLE
Extract Thumbnails on Startup

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#15]
It would be nice to have the option to start extracting missing thumbnails when you open the app! 😄

**Comment by cal2195** [comment]
@whyboris Have many people requested this feature?

An alternative option is #4, a `Verify Thumbnails` button that could be pinned to the main bar.

**Comment by cal2195** [comment]
Sounds good! 👍 I'll look into this!

**Comment by whyboris** [comment]
Related: #205

**Comment by whyboris** [comment]
#64 -- @cal2195 you said:
> I'd like these function to be pinable to the button bar! (needs new icons)

I think this is a better idea than to have auto-extract-on-start-up 😅 

While we could have both, I'm thinking about the annoying scenario of a user opening an old hub and it starts adding new files, locking the app while the green progress bar extracts all the meta. If the user exits out in the middle, perhaps there will be some weird state the app will be in that will be hard for the user to recover from ...

I'm uneasy about anything happening automatically, even when there is an explicit toggle for it.

I think the simplest solution is to allow the users to add the `rescan` button to their toolbar and then click on it whenever they feel ready.

This solves another problem -- which of the two scan options would the _automatic_ rescan use? The _add only_ or _add and remove_? Making the decision for the users makes me uneasy, but providing two different options makes it a headache.

Your suggestion of simply letting users surface the _rescan_ button to the toolbar is the best 👍 👍 👍 

I'll implement it now and close this issue 👍 Please feel free to comment as we can change the behavior from what I described here too 👌

**Comment by cal2195** [comment]
I prefer your solution! 👍
