### ISSUE TITLE
Languages to add

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#151]
Before `v2.0.0` I'd like to translate the app into these languages:

- [x] English
- [x] Arabic
- [x] Bengali
- [x] Chinese
- [x] French
- [x] German
- [x] Hindi
- [x] Italian
- [x] Japanese
- [x] Korean
- [x] Malay
- [x] Portuguese
- [x] Russian
- [x] Spanish
- [ ] ~Punjabi~ ⚠️ _Google API_ can't auto-translate 😞 

Please suggest others. 

Just before release I will use Google to auto-translate all the text into each of the above languages. It will not always result in grammatically correct translations, but it will be better than nothing.

**Comment by wAuner** [comment]
Hey Boris,

to be honest I wouldn't translate the app, at least not with some kind of auto-translate. As a German native speaker I can tell you that (auto) translations usually make things much worse than just sticking to English. They often even translate to the opposite of what is really meant.

So my advise would be to just stick with English. Most people are capable to understand enough to get along.

BTW any ETA of version 2?

**Comment by whyboris** [comment]
Hey @wAuner - thanks for chiming in 😄 

Translation should take about 2 minutes per language with the script @cal2195 wrote: [instructions](https://github.com/whyboris/Video-Hub-App/tree/master/src/app/i18n) 👍 

I don't intend to spend time cleaning up the automatic translations but will welcome corrections from whoever is capable and interested.

The list of languages above is roughly the top-spoken languages in the world. It's easy enough, so I may as well add them 😁

**Comment by whyboris** [comment]
I've been aiming to release version 2.0.0 before March 20th but it requires fixing up the few remaining bugs and I've been spending more family time than coding these weeks, so it's taking longer and might be delayed by a bit more.

**Comment by wAuner** [comment]
Hey boris, thanks for your reply. 
If you add additional languages, please make sure to allow the user to change it and do not determine it solely on the user's system preference.

I'm glad to see the project making progress. Sorry I can't help, but webdev isn't my metier, otherwise I would have liked to help.

How to plan on distriubting the update? I guess there isn't an update function in the current version!? Will a new download be required=

**Comment by whyboris** [comment]
Interesting that you recommend _not_ detecting the user's language from the user's system preference. I already have code that does it (not tested yet).

For what it's worth, now when you open _Settings_ you'll see 5 tabs (unlike before - a long poorly organized list of options), and if your screen resolution isn't too small, you'll see right away at the bottom the language selection dropdown:

![image](https://user-images.githubusercontent.com/17264277/54034245-5fc8e280-4184-11e9-9152-881a525f4365.png)

Hopefully should be very easy to find. Alternatively -- if I have enough time, since I'm already detecting whether this is a first time installation of the app, I can ask the user to select the language (if the app detects the system language is different from _English_) 🙆‍♂️ -- though that would be a lower priority issue before release 😅 

No worries about not being able to contribute code -- contributing comments and words of support are excellent ways to help 🎉 

I'll have an installation file I'll send over in a mass mailing to all those who purchased a copy (even if they purchased the app over a year ago). I don't have an update system implemented; perhaps in the future. 

P.S. the new version will have numerous breaking changes, so the old files (and maybe app settings) will have to be rebuilt from scratch 😢

**Comment by cal2195** [comment]
You're last comment there reminded me of #158! 👍

**Comment by wAuner** [comment]
sounds good.
using the system language as a default is a good idea, as long as it is possible to change the language manually (and override the default permanently)

**Comment by whyboris** [comment]
I implemented a new way to translate which is so fast I'm almost done with all the language translations 🚀 :trollface: 

https://github.com/whyboris/Video-Hub-App/pull/282

Hoping to finally get version 2 through the door 😅 😂

**Comment by whyboris** [comment]
Closed with #282 🛠
