### ISSUE TITLE
All image file names blank after recent PR

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#156]
Hey @cal2195 -- looks like something in your PR https://github.com/whyboris/Video-Hub-App/pull/155 did something. 

I should have tested it better 😅  -- I was in a hurry and merged without checking.

It seems current _master_ doesn't save file names of screenshots extracted and every preview is the same image.

Probably something small -- I might look into it but I might not have time until Sunday. Wanted to create an issue to keep track of it 👌

**Comment by whyboris** [comment]
Maybe when `hash` happens?

https://github.com/whyboris/Video-Hub-App/pull/155/files#diff-068f4f333d876532b9e3589218b4cbf1R801

**Comment by cal2195** [comment]
I haven't experienced this myself - how can I reproduce the issue? 🤔

**Comment by cal2195** [comment]
I don't see how that PR would cause this if you don't use the function... hmmmm...

**Comment by cal2195** [comment]
Ooooooooopppppssss
That `!==` should be `===` 😞
