### ISSUE TITLE
Remember Each View's Zoom Level

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#16]
It would be a very nice addition to remember the last zoom level for each view, and they often look better with different zoom levels! 🔍

**Comment by cal2195** [comment]
I assume we can make it nice like the way I didn't need to actual save the new video preview view?

So any new views can default to a zoom, and saved view levels will take priority! 👍

**Comment by whyboris** [comment]
Important feature -- may as well fix it up 👌 

Will have a PR later today.
