### ISSUE TITLE
customizing the word frequency service

### ISSUE THREAD

**Issue by HankBrown** [whyboris/Video-Hub-App#167]
Awesome project.

RE /app/components/pipes/word-frequency.service.ts

```
  public addString(filename: string): void {
    // Strip out: {}()[] as well as 'for', 'her', 'the', 'and', & ','
```

Um... this seems sexist. I'm guessing there a straight porn lover in the crowd.
On my system, "him" would be more appropriate ;)
Plus I would add more words to ignore.

There's no separate "cloud database", right? These terms are all based on file names. That's a good compromise. But I would want to take it further.

a) A custom regexp (and/or or list of words) could be loaded from some runtime config. I have not looked into how settings are stored yet, and whether thats a good place for word / tag config. Maybe a json file that is used if it exists and otherwise ignored.

b) ...? hmm. Still thinking. How to add tags to file names? I'm considering adding tags to the file name in brackets, eg:  "my file name[tag1,tag2].ext". I want to keep the original file name and not affect sorting.

Not going to jump in yet. Putting this out for feedback.

**Comment by cal2195** [comment]
Hey! :)

Re: a) It could be done - I believe that regex is just to strip out most common words that wouldn't make good tags (a, the, and, etc...). I agree either it should be her and him, or neither! 👍 You can also "ignore" tags in the app itself, under the tag panel! Would that do?

b) You can add tags in the app now, (not the release version yet, git only) - and they're saved in the library .vha file! Exporting from this file could be an option in the future - is there a reason you'd need them in the file name?

Thanks for your interest! 😄

**Comment by cal2195** [comment]
Also, in the latest master, tags can be based of any combination of:
- File names
- Folder and subfolder names
- Manually added tags

**Comment by whyboris** [comment]
Thank you @HankBrown 🤝 
I've added "him" to the master regex with #259 

I'm closing the issue since it might become irrelevant with release of version 2 🤞 -- while the features you were recommending aren't going to be there, the tag system might be good-enough for what you were originally looking for 🤷‍♂ 

Please feel free to create a new issue once version 2 comes out 🙌
