### ISSUE TITLE
Rename .vha to .vha2

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#168]
In the same spirit as #158, should we also bump the file extension of version 2.0.0 compatible library files as old .vha files will not be compatible?

Maybe `.vha2`? 🤔 💡

**Comment by whyboris** [comment]
That could solve the problem of users clicking old files and getting errors. My only reluctance is aesthetics -- I really like a 3-letter file extension. But I think it's a great to do what you propose 👍 

Let's keep this issue open until we have all the other bugs/problems solved and we're a week from release to reevaluate the idea -- this is likely a 3-line change 👌

**Comment by whyboris** [comment]
Yeah -- as I was looking out the window today it dawned on me that's it's almost surely a good idea to make `.vha2` the filename. Less confusion for users 🙆‍♂️ 

I'm also thinking it might be worth making the app install into a different folder `video hub app 2` -- so users can keep their old installation (and still have access to their old files).

Thoughts on this? 😄

**Comment by cal2195** [comment]
Makes sense to me, it's a major version bump and everything breaks with the old one, so why not have a clean slate! 😄

**Comment by cal2195** [comment]
Also, if we do this, we can revert #159! 👍
