### ISSUE TITLE
Named Saved Searches

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#169]
Since we have a very powerful search and filtering system, it would be **really cool** to be able to save filters you've set up! 💡 

For example, you could set up all your filters (tags, folders, ratings, durations, resolutions, sorting), and then save these values under a defined name! 💯 We could possibly even save other settings such as zoom level, view mode, certain features enabled/disabled (folder view)?

For example, you could have a saved filter called "Recent HD Under 5 minutes", which would sort by recently modified, HD only resolution, and duration from 0-5 minutes! 👍 

These could be selected by having a drop down at the top of the filter sidebar, with +/- buttons for adding/removing saved filters! 😄 

This would add to the powerful filtering system, and make it much more worthwhile using! 👍

**Comment by whyboris** [comment]
Thank you for the idea! What I love is that it doesn't really seem technically difficult -- we just store some aspects of the current state into an object, store the object into the `settings.json` (soon to be `settings2.json`) file, and that's it!

Making the UI for it is a bit of a nuisance, but not too bad visually as you describe.

I'm not sure who _would_ use such a feature (just _my_ failure of imagination), but as long as it's hidden behind a toggle (so as not clutter up the standard UI) it's good 👌

**Comment by whyboris** [comment]
@cal2195 -- please let me know if you are still working on / considering this feature.

I'm thinking of a feature-freeze sometime soon ❄️

**Comment by cal2195** [comment]
Just fyi, I'm on PTO for a week, so won't have much time to work on vha! Feel free to freeze, there's always minor updates! 😂 I am working on the feature, but haven't much done on it yet!

**Comment by whyboris** [comment]
Hope you have a good time off 🙌 
Hope you never feel pressure to work on VHA 🙇 
I'm untagging this from `2.0.0` release -- there's no need to add more features than already present 💯

**Comment by whyboris** [comment]
Hey @kaer - you left a comment once that was possibly related to this _issue_: https://github.com/whyboris/Video-Hub-App/pull/242#issuecomment-518039600 -- is this what you had in mind?
Cheers 🙌

**Comment by kaer** [comment]
The search settings will work for what I told, but I guess an option to save the settings as a collection instead just display as recent searchs because the history may have a limit and then the search will be removed.

**Comment by whyboris** [comment]
Related discussion about `Smart Albums` #315

**Comment by whyboris** [comment]
I still think that _named saved searches_ is a large undertaking (from the UI and coding perspective) but it might be easier now that we have a *bottom tray* which can display some things horizontally.

I'm unsure if visually it would be easy to use and understand, but just food for thought 🤔 

I'm keeping this issue open for a little bit longer, but if there's not a sustained interest in it I may close it in the future (though no fear - it's easy to re-open too) 👌

**Comment by whyboris** [comment]
I'm closing the issue as there doesn't seem to be continued interest. I have no problem reopening it if someone wants to continue the discussion 👌 

I am unlikely to add this feature myself, but I am open to adding it if it is cleanly implemented by someone and proposed as a PR 👌 (do discuss if you start working on it 🤝 )
