### ISSUE TITLE
Add Support For More Thumbnail Import Settings

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#17]
As well as thumbnail size, it would be nice to support more properties such as:

- JPEG and Video Compression
- Number of thumbnails to extract
- Number and length of video clips to extract
- Disabling thumbnail or video clip generation
- Option to enable extracting thumbnails on startup #15 

Customise **everything!** 👍

**Comment by whyboris** [comment]
Seems like the _jpg_ quality is relatively easy to set with _ffmpeg_ (e.g. `-qscale:v 2`), right? 😁

**Comment by whyboris** [comment]
Once this PR lands, we'll have a better organization of the settings menu 🎉 
https://github.com/whyboris/Video-Hub-App/pull/43

**Comment by whyboris** [comment]
I've been struggling while thinking of a clean UI for the selection for number of thumbnails to extract.

_Currently:_
A single dropdown with set options in two categories: 
 - fixed number of screenshots per video (e.g. 10 per video)
 - fixed number of screenshots per some duration of video (e.g. 1 per 5 minute)

_Desired:_
Give the ability for the user to choose the number per video or number per some duration. Easy conceptually, but how do we represent this choice visually?

I'm thinking `<input type="number">` with some _min_ and _max_ already set ([example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number)).

Maybe something like this:
```
_____
|   n |   (  ) screenshots per video
|____|   (*) screenshots every hour
```
a large size input on the left with two radio buttons on the right.

I just wish users wouldn't have to do math in their head and choose N from `1 screenshot every N minutes`.

Maybe a radio box with two independent inputs?
```
(  ) [  n  +/- ] screenshots per video
(*) 1 screenshot every [ n +/- ] minutes
```

Might be easier ... just unfortunate that the number input will then be either small, or will disrupt the flow of text a bit. I'll play with the _css_ to make it as nice as possible.

@cal2195 - thoughts?

**Comment by cal2195** [comment]
I like this idea a lot - although do we need to limit it to a `max`? No max, or at least a very large max will allow for greater use cases we haven't thought of! 😄 

I prefer the second idea - makes more intuitive sense! 👍
