### ISSUE TITLE
Similar videos tab

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#173]
On _YouTube_, when you watch a video, there are _recommended videos_ in the sidebar.

This app can do the same very easily by reusing the already existing "show similar" functionality. 

There would be a button in the ribbon which would toggle a horizontal drawer along the bottom which would show 5 most-similar videos to the last video clicked.

Unsure how useful it would be to anyone, but it's easy-enough to implement. I'll add it 👍

**Comment by cal2195** [comment]
This would be very cool! 💯 👍👍

**Comment by whyboris** [comment]
Works beautifully -- see #174 😎
