### ISSUE TITLE
Implement .tag files

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#178]
A nice feature to have is the ability to import tags from `.tag` files which are located with the videos - eg. `video.mp4` and `video.mp4.tag`

This tag file would store comma seperated values of tags, and the app can load in these tags automatically into the manual tags field when importing to files!

This allows you to script any number of things to scrape, or generate tags for files and then add them to the app easily! Writing out current tags to the tag files would also be a nice option! 💡 

I've already got this working, just need to think about when to import tags, if the file is already tagged - Currently it only imports if there are no tags on a particular file. 👍

**Comment by whyboris** [comment]
I've never heard of `.tag` files 😮
In what OS is this available? 
Could you share any documentation/summary about them?

**Comment by cal2195** [comment]
I just invented them! 😆 I figured it was a fairly simple way to allow people to interface from their favourite programming language to automatically tag the video files in whatever way they wanted, and then have the ability to magically import all the tags into vha! 💡

**Comment by whyboris** [comment]
I see 👍 

I'm reluctant to fill up people's directories with new files (even if they are hidden 😓), but if the suggestion is to allow VHA to extract tags from those files, that could work.

**Comment by cal2195** [comment]
Well no - I agree and this is *completely* optional - you could choose whether to import `.tag` files _if present_, and exporting the tag files would be an option in the settings! More for backup/regenerating libraries! 👍

**Comment by whyboris** [comment]
I feel like we might need some secret *dev* mode :trollface: 
https://www.youtube.com/watch?v=pXPXMxsXT28

**Comment by whyboris** [comment]
@cal2195 -- I'm thinking of cleaning up the _Issues_ page to keep it ready for after Version 2 release.

You said you had some version of this implemented, though I also think it's the kind of feature that would at best be used by only a few people. 

It sounds like it may be as simple as a single function that checks whether there is a `.tag` available and attaches the tags to the _ImageElement_. On the front-end you might need to merge the flags or ignore them 🤷‍♂ So I'm not opposed to merging a PR - as long as it doesn't cause any bugs 🙆‍♂ 

Please feel free to re-open the issue as you see fit 🤝

**Comment by cal2195** [comment]
Reopening as there seems to be continued interest in some feature like this. 👍

**Comment by whyboris** [comment]
I had another user email me with a request to import tags attached to files that can be seen in the OS.

Seems like this might do the trick:
https://www.npmjs.com/package/exif-parser
Found here:
https://stackoverflow.com/questions/26091836/is-there-a-way-to-read-file-metadata-using-node-js

I'll test it out this weekend and see if it works 🤷‍♂

**Comment by whyboris** [comment]
⚠️ this dependency can't be installed on _Windows_ and I would have to maintain a `mac` branch in order for this feature to exist. This isn't a problem, but I think this may be a mac-only feature for a while.

**Comment by whyboris** [comment]
I figured out a way to import OS-X tags on first scan. I'll try to get this PR #370 merged before VHA `3.0.0` is released 🎉
