### ISSUE TITLE
Similar Videos feature bug tracker

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#179]
This issue is to track any bugs with the similar videos feature!

So far I've noticed:
- The similar issue bar overlaps the bottom of the side bar, hiding features
- The similar issue bar overlaps the bottom of the video browser, hiding videos

I assume the best option is to move the bounds of these two up, if the bottom similar bar is enabled? 💡

**Comment by cal2195** [comment]
Also, at least for me, titles that take two lines are half hidden in the similar videos bar!

**Comment by whyboris** [comment]
Ah -- I did the quick-and-dirty ™️ thing :trollface: - simply re-using the `tag` tab that pops up from below (which inherently has the same problem - hiding some of the sidebar). 

I'll see if it's simple-enough to move the bounds of the sidebar and the video browser as you suggest (a nicer solution than those I began thinking of as I was reading issues you raise) 🤔

**Comment by whyboris** [comment]
Yeah -- I was eager to release and polish later -- thank you for listing the issues you see with the _similar videos_ bar 🙇 

I did add in a nice animation though for when you close the sidebar 😉 

I'm not near my 4K screen for another month and a half so I can't test the app in bigger resolutions than my laptop -- that will be the _ultimate_ test 😆

**Comment by whyboris** [comment]
Thank you again for opening the issue to keep track of stuff to do -- this is now on my _to-do-next_ list ✅
