### ISSUE TITLE
Perfomance degradation in dev mode

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#180]
This is more of an interesting observation, and maybe this is common knowledge but it was news to me! 😄 

Turns out the app runs a **lot** quicker in production mode (yay!), due to less assertions in the code - see https://stackoverflow.com/a/37355273

Found this out while trying to see why scrolling was so slow with the performance monitor - waaaaaay smoother with:
`npm run-script electron:local`

🚀 🚀 🚀

**Comment by whyboris** [comment]
I suspected it has to do with all the _console.log_ statements I have peppered in the code 😓 
If you happen to have images that are missing, the _console_ will get dozens of messages printed as you scroll around which slows things down.
I wonder if you close the console in the dev mode - does the app feel like it speeds up a bit?

**Comment by cal2195** [comment]
I don't think it has to much to do with that, the app is the same with open or closed! And I ran the performance monitor and it's definitely the assertions mentioned above, mostly checking for equality! 👍

I find the logs very useful for dev anyway, although we could move them all under the debug flag?

**Comment by whyboris** [comment]
I've been meaning to remove most of the `console.log` statements in the files (except for the ones you've added to `main.ts` / `support` files) -- though they've not been bothering me, just thought I left too many around from when I was debugging earlier 😅

**Comment by whyboris** [comment]
Not directly related, but this seems really cool: https://github.com/AriaMinaei/pretty-error -- I might give it a go in this project 👍

**Comment by whyboris** [comment]
Thank you @cal2195 for the note -- I'm closing this _Issue_ as I'm unsure what actions we could/should take. I'm ok with the app being less performant while developing (as compared to _production_) 🤷‍♂ 

Feel free to re-open with a commend if you think we should keep it open 👍
