### ISSUE TITLE
Try ngx-virtual-scroller 3

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#186]
Version 3 came out recently!

https://github.com/rintoj/ngx-virtual-scroller/blob/master/CHANGELOG.md#v300

Also, Angular 8 is coming soon 😁

**Comment by cal2195** [comment]
I tried that in `image-viewer` actually - worked fine (it's not a big change, but someone complained about breaking changes in minor versions 👍 ).

Didn't try too hard but I didn't get the cool scroll thing working - I think you have to append or something, not replace... Worth investigation! 👍

**Comment by whyboris** [comment]
What's the "cool scroll thing"? 🙃

**Comment by cal2195** [comment]
> If items array is prepended with additional items, keep scroll on currently visible items, if possible.

Ideally this would let us update the array (by filtering new terms), while keeping the current items scrolled-to on screen! 😄

**Comment by whyboris** [comment]
I'll glance at it, but most likely I'll keep behavior in the app as is. Perhaps include a "scroll to top" behavior whenever a search occurs. Unsure what the current behavior is like 😅
