### ISSUE TITLE
contact box on website no appearing

### ISSUE THREAD

**Issue by Poddi** [whyboris/Video-Hub-App#191]
Hello
i*ve already tried the "Please refresh the page if the contact box does not appear." but its not appearing.
just wanted to ask if there is a way to add more than one folder to an hub.if not i hope for 2.0.0
Greets

**Comment by whyboris** [comment]
Thank you for posting 🙇 

I'm aware of the issue: the provider I was using for feedback eliminated their free tier. 

When I'm back from my vacation in late June I'll put in some replacement 👍

**Comment by whyboris** [comment]
ps - sorry Video Hub App 2.0.0 will not allow to select more than one folder per hub. 

Two solutions I can think of:
1. Create several hubs, and you can switch between them with 1 click (just toggle in settings to _show recent hubs_) in the left sidebar.
2. Create a `symlink` to all the folders you'd like within one folder, and create a hub from that one folder. I'm 99% sure it will work, though have not yet tried.

Please do share any other ideas if you think of anything. 

While it's possible to rearchitect VHA to allow more than one folder, it would add a lot of extra complexity (and an annoying user interface problem to solve, followed by lots of logic of what to do when users want to add or remove previously-added folders, etc). At least for this year VHA will not have this functionality built in.

Conceptually -- I thought people would have their movies either all in one folder, or compartmentalized in several folders (e.g. "Home Movies", "Cartoons", etc). But I never conducted a survey ... was just hoping that it would be enough for most use cases 😓

**Comment by whyboris** [comment]
Thank you again @Poddi -- I've finally fixed the contact form on the website:

https://videohubapp.com/contact.html

Huge thank you to https://formspree.io/ for making it so easy 🙇 🙇 🙇 
Glad I don't have to spend time setting up my own form with PHP 👌
