### ISSUE TITLE
Propose of improvement of the translation addition workflow

### ISSUE THREAD

**Issue by Lakshamana** [whyboris/Video-Hub-App#194]
Although it is easy to add new translations (because of translate.sh), the process of adding new translations is still manual (manual edition in some files) and then it could lead to mistakes in the time to add new languages. In order to minimize those mistakes and turn contributors more confident to this process, I propose here an automatic way:
Just run (for instance):
`./translate.sh Deutsch de`
and then it's done.
I was working on it and will submit a PR.

**Comment by whyboris** [comment]
Thank you again for your work @Lakshamana 🙇 

Closed with #195
