### ISSUE TITLE
Hide clip view when no clips available

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#204]
Hide the button to switch to the `clip` view if the hub does not contain clips.

**Comment by cal2195** [comment]
I wonder if it would be better to either disable it, or link it to an explanation of the feature and the option to enable - if someone skips over the option in the wizard, they may never know the feature exists! 😱

**Comment by whyboris** [comment]
I _love_ the _extract clip_ feature (thanks again @cal2195 for creating it!) - it _would_ be a shame for users not to realize it's there.

I'm thinking I'll have an extensive `rescan` settings menu with toggles / explanations, see #205
