### ISSUE TITLE
Choose preview image if desired

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#206]
It's not clear to me why anyone would want this option, but I had a user request it 🤷‍♂ 

It's technically feasible. For ease of UI we could have the app receive drag-drop events, and if the event happens over a particular thumbnail, we'll just swap in* the image.

\* `ffmpeg` already _can_ handle an image resize, so it shouldn't be too problematic 😅

**Comment by cal2195** [comment]
Hmmm, my only issue here is that recreating the hub, you'll lose this information - currently you can delete the thumbnail "cache", and recreate it all without any consequences! 🤔 

I wonder what the usecase is... A better idea might be to autodetect a file named `video_cover.jpg` or something along those lines next to the `video.mp4` and use that instead - overcomes my above issue, and is scripting-friendly like my tag feature! (I don't recall if I've merged that yet or not...)

**Comment by cal2195** [comment]
#178 This one! 😄

**Comment by whyboris** [comment]
This sounds like a good option as well, though it forces users to format things a certain way.

I would reach out to the user who requested this feature before developing - just to get a sense of why / when they would be interested in using it 👍 

ps -- this is for the `Ideas` _Milestone_ 👌 -- no sooner 😅

**Comment by whyboris** [comment]
The gentleman who requested the feature initially emailed me recently expressing he's looking forward to the version 2 and was wondering if I'd thought about including the option to replace the main image. I asked if drag-and-drop is a decent-enough interface and he said that would be great.

Turns out ❤️ _Angular_ ❤️ makes detecting drop events _stupid easy_: just add `(drop)=someFunc(event)` in your code and you're done.

So I'm going to include this feature in 2.0.0 😉

**Comment by whyboris** [comment]
Solved with #238 😎
