### ISSUE TITLE
Speed up ffmpeg & ffprobe if possible

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#214]
I'm unsure whether there are any more optimizations we can put in, but since extracting screenshots, clips, and file info are a pivotal part of the app, it would be great if these were as fast as possible 😅 

Hypothesis:
- we can seek to the closest _keyframe_ rather than a specific second in the video (though perhaps we're already doing that)

Weaker hypothesis:
- we can use some options when calling _ffprobe_ to extract only the data we want, rather than what we get now (though from my reading of the documentation this doesn't seem possible 🤷‍♂ )

I welcome other ideas and suggestions 🙇

**Comment by cal2195** [comment]
I think we may already be using keyframes at the moment - I spent a large amount of time researching the best methods for this, and I think we have the current best practice! 👍 

But if anyone know otherwise, please tell! 😄

**Comment by whyboris** [comment]
🙇 thank you @cal2195 🙇 
I suspected your code was already doing the keyframe thing.
🎉 yay 🎉

**Comment by whyboris** [comment]
I'll just close the issue -- I'd rather have fewer open issues and more user-initiated issues going forward 👍
