### ISSUE TITLE
Linux build for 2.0.0

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#218]
Eventually when 2.0.0 is ready, we'll need to build this app for _Linux_

We'll likely upgrade to `electron-builder` version `21.X.X` which has a breaking change:
https://github.com/electron-userland/electron-builder/releases/tag/v21.0.1
> desktop integration for AppImage is removed in favour of AppImageLauncher.

I'm unsure what that means, but I suspect this means our `electron-builder.json` will need to be updated: 
https://github.com/whyboris/Video-Hub-App/blob/master/electron-builder.json#L46

This _Issue_ is to keep track of the Linux build ✅

**Comment by cal2195** [comment]
I can help out with this if needed! 👍

**Comment by whyboris** [comment]
Thank you Cal! We'll coordinate sometime in August on this 🙇

**Comment by whyboris** [comment]
`master` branch now has the latest version of _electron-builder_ 👌 
I suspect the _Linux_ build is now broken 💔 
I'm hoping to polish off the app this week and build the first draft of the final release next weekend 😅 
I'll probably ask to borrow a co-worker's Linux laptop for a half hour to confirm a Linux build sometime this week 🤞

**Comment by whyboris** [comment]
🚀 Getting close to the release. Once I confirm everything is in a release-ready state for _Mac_ & _Linux_ I'll borrow someone's computer at work for 15 minutes and build the app 😅 

Given there was a breaking change to how _electron-builder_ builds _Linux_ it might take more than 15 min 😓

**Comment by cal2195** [comment]
No linux build yet 💔 

If you need some help with this, give me a shout! :)

**Comment by whyboris** [comment]
😅 I forgot I could just install _VirtualBox_ and build it there.
✅ `AppImage` built and is now available as a demo and for purchase.
📫 I'll be mailing out the link to everyone who purchased the app.
🙇 If you bought the app and want the link please [contact me through the website form](https://videohubapp.com/contact.html).
