### ISSUE TITLE
Hub with Multiple Folders

### ISSUE THREAD

**Issue by Noctem** [whyboris/Video-Hub-App#248]
I'd love the ability to create a hub that has multiple folders that are in different parts of the directory hierarchy. This was already requested in #191 (and you mentioned that it won't be implemented any time soon), but since that wasn't the main subject of that (now closed) issue I've opened this here to track its status.

You mentioned creating a folder of symlinks to other folders and creating a hub from that, which you expected to work. I tried that on macOS with the latest git master and it doesn't traverse directory symlinks, so in a folder containing nothing but directory symlinks it finds no videos and won't even allow you to create the hub. I'd be satisfied with this symlink workaround if it can be made to work.

Symlinks to the actual video files work, but maintaining many symlinks would be a hassle particularly if videos are added, moved, or removed frequently.

**Comment by whyboris** [comment]
Thank you for opening this issue -- I was pretty sure the _symlink_ to folders would work (someone said it did, perhaps on an older build). I'll test it out today after work and see if I can get it to work. 👍

**Comment by whyboris** [comment]
Haven't forgotten about this -- was fixing other bugs and adding more features 😅

**Comment by cal2195** [comment]
We probably need to just check `fs.isSymlink()` and then try stat the link to see if it refers to a directory! 😄

**Comment by whyboris** [comment]
Thanks @cal2195 for pointing me in the right direction:
[isSymbolicLink()](https://nodejs.org/api/fs.html#fs_dirent_issymboliclink) seems to do the trick 💯 
Should be fixed with #259 🙇
