### ISSUE TITLE
Autodetect User Language

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#26]
It looks like we can do something like this:
`translate.use(browserLang.match(/en|ru/) ? browserLang : 'en');`
But I'm unsure how Electron handles browser language.
It might be worth adding a modal if the app detects it's the first start that has a language selection dropdown.

**Comment by whyboris** [comment]
Will be closed with https://github.com/whyboris/Video-Hub-App/pull/78 🎸
