### ISSUE TITLE
Thumbnails default to 3 if nothing is touched

### ISSUE THREAD

**Issue by avenminer** [whyboris/Video-Hub-App#272]
If I create a new hub and I dont touch any of the settings other than location, the default screenshots is set to 10 but once you actually create it only 3 screenshots per video are created and if you go into settings for the hub, it will show it as 3 aswell.

**Comment by whyboris** [comment]
Thank you for catching that! It's a super-easy fix, I'll get it fixed with #267 🙇

**Comment by whyboris** [comment]
Thank you @avenminer for noticing the bug!
Closed with https://github.com/whyboris/Video-Hub-App/commit/8adc27a63624a0f26005e613127f11bac9e41eac 📯
