### ISSUE TITLE
Mac does not retain tags or preferences on close

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#290]
🔍 Trying to replicate first

User emailed saying:
> Video Hub app does not retain any added tags or toolbar customizations. When you exit the app after make tag additions or toolbar changes - they are not retained when reloading hub. Running this on MacOS version 10.15.

**Comment by everythingIO** [comment]
Confirming issue on MacOS 10.14. Tested with both local files (and hubs) and with files and hub stored on server via AFP.

Additionally, tags, ratings, etc. aren't saving. Could it be a GateKeeper issue? I tried running the app as sudo without luck!

Loving version 2 so much! Thank you!

**Comment by cal2195** [comment]
Are there any steps to reproduce this?

Could either be a permission problem, or a logic bug.

**Comment by whyboris** [comment]
I've been meaning to replicate, but has been a busy time for me lately 😅 
Will report once I try it (this or next weekend).

**Comment by cal2195** [comment]
@everythingIO Could you tell me more about how to replicate this issues?

Is it first run? What changes are you making? How are you closing the app? 😄

**Comment by everythingIO** [comment]
The issue seems to have been resolved. Maybe, I just needed to restart my computer or the latest macOS update fixed it right up?

Working just fine now. Thanks so much for this wonderful app!

**Comment by whyboris** [comment]
This issue _may_ have been resolved earlier, but with version 2.1.0 it should finally be gone:

https://github.com/whyboris/Video-Hub-App/pull/345/commits/edc63eb96e7f02651160eed48a45b6189ba13450

Because I'm using _Electron_, at least in version 2.0.0 it automatically responded to `CTRL` + `W` / `Command` + `W` - closing the app without triggering the pre-shut-down-logic I implemented to save settings (and tags!)

Closing this issue. If it still happens, please feel free to open a new one 🤝
