### ISSUE TITLE
Mac VLC opens many instances when chosen manually as default app

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#291]
Shouldn't open many instances ... that code was a bit of a hack ... I'll see if I can fix it 🤷‍♂ 

If anyone's interested in fixing it, please be my guest 🙇

**Comment by LordJon** [comment]
I haven't seen this problem on Windows 10 x64 yet. I did however experienced a large noticible delay in loading the video in VLC after setting the path without activating "Start playing from time of clicked screenshot". After activating this setting the delay disappeared.

**Comment by arszh** [comment]
I couldn't  reproduce the problem. The app opens VLC correctly.
macOS 10.15.1, VLC 3.0.4.

**Comment by whyboris** [comment]
Closing as part of the `3.0.0` pre-release cleanup 😅 

Please feel free to comment or open a new issue in the future 👍
