### ISSUE TITLE
Thumbnail directory not automatically created on linux

### ISSUE THREAD

**Issue by kdkavanagh** [whyboris/Video-Hub-App#292]
v2.0: 

Thumbnail generation appeared to run without error, however no thumbnails showed up.  Strace'd one of the ffmpeg processes during the generation to see what it was doing:

```
futex(0x6067350, FUTEX_WAKE_PRIVATE, 1) = 0
open("~/vha-vids/thumbnails/d5a7982cc9e242af3c3851013cf9e134.jpg", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
write(2, "[image2 @ 0x5dfe780] ", 21)   = 21

```

Manually creating that directory fixed things and thumbnails are generating now

**Comment by whyboris** [comment]
Thank you for the report and for digging in!
I haven't tested much on Linux other than install / create a hub, see that it works, and exit 😓 

Perhaps it's some weirdness because the folder was in some protected directory? Seems like you tried to put it into `~/` 🤷‍♂ 

I'll try to replicate. I welcome suggestions for a fix.

**Comment by kdkavanagh** [comment]
Must admit that I switched the absolute path to a fake path in the example above.  The original path given by strace was indeed a full absolute path

**Comment by cal2195** [comment]
@kdkavanagh Can you tell me more about this issue?

Did you have a previous hub from before (v1 or v2)? Or was this a *completely* fresh hub? (ie. never before named like this, even if you deleted the `.vha` file)

Can you tell me an example full path (you can replace the folder names, just an example of what it would look like)?

I have a hunch, but need some more info! 😄

**Comment by whyboris** [comment]
@kdkavanagh -- please let me know if I can close the issue -- if it happened just once, or it's been occurring again.

I've not added any code to fix whatever caused the issue -- I basically never use Linux so it's a bit more rough-around-the-edges than Mac & Windows versions 😅 

I've not had anyone report this bug, so perhaps it's a fluke 🤞

**Comment by kdkavanagh** [comment]
Hasnt happened since, since once the directory is created, everything works.  I'd guess I'd say just make sure that the thumbs directory exists before trying to write to it

**Comment by whyboris** [comment]
Seems like this line _should_ do the work 🤷‍♂ 

https://github.com/whyboris/Video-Hub-App/blob/master/main.ts#L695

`fs.mkdirSync(path.join(outDir, 'vha-' + options.hubName + '/thumbnails'));`

I'm closing for now. If anyone encounters the problem again, please open up a new issue and reference this one 🙇
