### ISSUE TITLE
valid folders ignored with leading underscore (all platforms)

### ISSUE THREAD

**Issue by sbaker617** [whyboris/Video-Hub-App#293]
https://github.com/whyboris/Video-Hub-App/blob/c20940ba586da0007e973af610253641c865af94/main-support.ts#L242

It would be nice if the ignore patterns were configurable.  I had multiple files missing and realized anything in a directory which had a name with a leading `_` was being skipped.  Use of a leading underscore helped with the natural sort order in some instances.   If the concern is metadata/previews on mac systems in `__MACOSX` folders, using that full folder name as an ignore pattern might be an option to avoid files unintentionally being skipped on all platforms :-)

**Comment by lighthunt** [comment]
I have exactly the same problem with "_" underscore prefix for most of the folders (and I spent quite a lot of time to figure out why my hub is incomplete or even empty ... ) this is actually blocking me from using this otherwise very nice app, please consider the suggestion above

**Comment by whyboris** [comment]
Thank you for opening this issue. Sorry I'm unsure I why we're ignoring `_` -- I think it was introduced in this PR: https://github.com/whyboris/Video-Hub-App/pull/22
@cal2195 -- if you happen to have time, could you comment briefly? 🙂 

I'm unsure if there are any auto-generated folders with `_` (other than `__MACOS`) 🤷‍♂ 

@lighthunt -- until this issue is fixed, please feel free to build your own patched copy of this app. You can reach out to me if you have trouble.

**Comment by cal2195** [comment]
It was originally listed in the `Future` section on the official site - although now that I look at it, it was _folders_ beginning with `.` and _files_ beginning with `_`!

Must have gotten confused along the lines somewhere - I'm not sure what the original request was for, but I assume some temp/cache files can start with `_` - thoughts?

**Comment by whyboris** [comment]
Seems like we could safely allow the `_` in folders again ... while perhaps just ignoring the `__MACOS` one? 🤷‍♂  Comments welcome 🙇

**Comment by lighthunt** [comment]
@whyboris, thank! I managed to patch and build my own binary, so it's no longer a blocker for me. As for the general question, allowing underscore should be safe (supported by my experience and additional short googling only so not 100%) as easy fix, but configurable ignore patterns as proposed originally would be nice little feature to add as a second step IMO. Other programs may eventually create their databases just like VHA does inside the video dir root and you may want to ignore them.
@sbaker617 many thanks for your initial report, it helped me to figure out why scanning doesn't work in some cases ...

**Comment by sbaker617** [comment]
> Seems like we could safely allow the `_` in folders again ... while perhaps just ignoring the `__MACOS` one?  Comments welcome

Sounds good to me :-)  The leading `.` exclusions could go either way... that's the typical hidden file/folder prefix on *nix platforms, so makes sense, but might not fit for all.  Maybe most flexible option would be to provide a list with default values to skip at hub creation/edit time ?

@lighthunt glad it wasn't just me, thanks :-)

**Comment by whyboris** [comment]
Thank you @cal2195 for fixing this 🙇
