### ISSUE TITLE
Open multiple hubs as one

### ISSUE THREAD

**Issue by lighthunt** [whyboris/Video-Hub-App#296]
Would be nice to be able to open multiple hubs at once so that they can be viewed and searched as one hub. Motivation:
* I have video files on multiple drives and would like to search them all
* I can create large hubs by adding smaller increments (hubs)
* I may have some folders I want to ignore in the hub (this can be work around by configurable ignore patterns, if something like that is implemented, but multi hubs is better way to do)

Proposed implementation: If the hub can contain other hubs, this can be stored and thus such combination remembered and easy opened later again. Please consider.

**Comment by whyboris** [comment]
I like this idea -- it's in some ways similar to being able to add many folders to a hub, but may be cleaner and simpler in some ways.

The trickiest part is that as I was building the app, from the start, I explicitly decided I would focus on one folder (directory) per hub, and one hub at a time with no consideration for ever implementing anything different. This means that it might be very tricky to implement what you ask. There is a chance it won't take much work, but I'm unsure. 

As I've discovered working on the app, sometimes the UI / UX is the most challenging: creating a feature is sometimes straightforward, but what can be challenging and very time consuming is communicating how to use it intuitively, putting in buttons that make sense, and catching all the weird states that users might get into if they don't follow the expected process.

I welcome an attempt by others to code a rough draft of the feature (and I'm happy to answer questions and share ideas), but I'm not planning to implement it myself at this time.

**Comment by whyboris** [comment]
ps - just FYI, in case you hadn't come across this feature: you can enable the "view recently opened" in the sidebar and you are then able to switch between hubs once you enter your search (the search terms don't disappear when you switch hubs) 😉

**Comment by whyboris** [comment]
In version `3.0.0` we'll have the ability to add more than one folder to a hub. I think that is a satisfactory solution to the feature request. 

Please feel free to comment or open a new issue if you think this is still worth addressing in another way 🤝

**Comment by lighthunt** [comment]
Thanks @whyboris. I have played with it and found multiple folders solution satisfactory for my use-case.
First I wanted to manually merge all my (relevant) vha2 files into one to save time, but found it easier to just add folders and re-scan all the folders again one more time since I wasn't sure about all attributes added to the new format. Anyway, this will do.

I've added the note about showing "root" folders in the view when "show folders" is enabled in the #456 discussion

**Comment by whyboris** [comment]
@lighthunt - it is possible to move over all the "thumbnails" and "filmstrips" images to the new hub before adding the new source folder. As long as the extraction settings (number of screens per video) match up, the app will add the videos to the gallery and skip extracting all the thumbs that have been copied (so it's much faster).

I'm glad it worked for you with a _re-scan_ 👍 

Thanks for the comment about "root" folders is "show folders" view. I've been thinking about it previously. I'll continue the discussion in that thread 👍

**Comment by lighthunt** [comment]
@whyboris  Thanks for the hint with thumbnails and filmstrips, I was considering it earlier but unsure how names are generated (using paths, what if roots are different etc.), possible duplicate names etc I didn't do, but will try that later.

re-scan didn't work so well, for larger usb disks, few things I experienced, sorry for lack of details (if something is unknown, I will try to explore further, let me know).

1. after re-scan button pressed, nothing much happened, or the progress "circle" (in the top right corner of the app) only briefly showed then disappeared than the same blink couple of seconds later (I had more folders added, could be some race condidtion, async scans influence each other?, if so, allow only one folder scan at the time - singleton?, until solved)
2. I always ended up in status where the app couldn't be closed or it crashed later (probably scan on the background, task manager showed these processes running after it crashed), but no scan "circle" indicator. would be nice to have the scan indicater on the button running for the whole time the associated scan is in progress
3. if I had jpegs in the path, some javascript error pop up for every file (new error dialog after Ok confirmation of previous file), I had to kill it

**Comment by lighthunt** [comment]
>3. if I had jpegs in the path, some javascript error pop up for every file (new error dialog after Ok confirmation of previous file), I had to kill it

A JavaScript error occured in the main process
Uncaught Exception:
Errror: ECANCELLED: operation cancelled, scandir .... 

I think this is caused when I close the main windows. It doesn't do anything for a long time, then dies with the above error (never ending, after OK, it just shows error with next folder).
Aparently scan was running, but no indication about it.

Sorry, point 3 was misleading, it has nothing to do with jpeg, was cancelled at img folders by coincidence.

**Comment by whyboris** [comment]
Thanks for bug reports 🤝 
Some comments in random order:
- `.jpg` file names are based off video file bitstreams (a bit from the front, middle, and back), so moving the video file doesn't change the "hash" - keeping the image file name the same 😁 
- (re)scanning multiple folders _should_ work without error - the scanning is a parallel process, and each file is added to a single queue which extracts metadata; all those files are added to a (different) singe queue which does the screenshot extraction
- screenshot extraction (top right indicator) should persist until the thumbnail queue is done (so when you rescan and no video files appear, it should either not appear at all or go away swiftly).
- initial scan for files should have a green indicator on top-left (next to number of files in the gallery) and should go away as soon as we're done collecting a list of all the files in all the directories the app is (re)scanning
- I think I don't have a metadata extraction indicator, but as soon as one file has been added, it's now in the "thumbnail extraction" stage which should show the top-right indicator (the donut progress bar)

After merging the WIP `3.0.0` branch into `main` I've not tested the app too much on the create hub/add folder/rescan/switch hub/rescan/close (etc) interactions. I'll likely discover those bugs when I try to play with the app more, but I _definitely_ appreciate reports like this. Please feel free to open a new issue for better visibility if you'd like.

As of now, I expect the app to not have bugs in a standard way of use: open, create new hub, add some more folders, exit. Re-open, have no bugs 😅 🤞 I've tested it with network drive, external HD over USB, and local HD.

I have not tested closing the app mid-scan, but I don't expect the app to break catastrophically 🤔 -- it should allow re-opening of the file and a re-scanning without problems.

**Comment by lighthunt** [comment]
Thanks @whyboris  for explanation! I don't know, but something is wrong. Scan process is very slow in latest version compared to v2.2.3 even with a single folder and relatively not many video files. I can't use the new app. I'll make a new issue for that.
