### ISSUE TITLE
Use fs.Dirent objects, and extract metadata in the background

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#3]
Currently, the app freeze while performing the first phase of the import (listing all the files recursively).

A large portion of this delay in phase 1 is due to `stat`ing all the files to see if they are directories. Alternatively using `fs.Dirent` objects, the following code would be much better:
```
// Recursively walk through a directory compiling ImageElements
  const walkSync = (dir, filelist) => {
    const files = fs.readdirSync(dir, {encoding: 'utf8', withFileTypes: true});

    files.forEach(function (file) {
      if (file.name) {
        if (!fileSystemReserved(file.name)) {
          // if the item is a _DIRECTORY_
          if (file.isDirectory()) {
            filelist = walkSync(path.join(dir, file.name), filelist);
          } else {
            const extension = file.name.split('.').pop();
            if (acceptableFiles.includes(extension.toLowerCase())) {
              // before adding, remove the redundant prefix: sourceFolderPath
              const partialPath = dir.replace(sourceFolderPath, '');
              // fil finalArray with 3 correct and 5 dummy pieces of data
              finalArray[elementIndex] = [partialPath, file.name, cleanUpFileName(file.name), '', 0, '', 0, 0];
              elementIndex++;
            }
          }
        }
      }
    });
```
See https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options

This will be a drastic improvement in speed, especially over networked file systems. Unfortunately, this is only added in node v10.10.0, which will need to be updated first.

Additionally, it would be much better if the second phase (metadata extraction) was performed in the background like phase 3 (thumbnail generation). This is especially important with the addition of file hashes, which will require reading every file.

**Comment by whyboris** [comment]
_master_ has been updated with _node 10_ so this is ready for a PR -- whenever you'd like 🥇

**Comment by whyboris** [comment]
I think you're right - https://electronjs.org/releases#3.0.0 electron 3 comes with Node v10.2.0
I suspect _electron 4_ is coming out soon - before we have our next release 👌

**Comment by whyboris** [comment]
A better way to see which _node_ version is in which _Electron_ version: 
https://github.com/electron/releases

**Comment by cal2195** [comment]
Nice! 🎉 

I noticed you tried to use v4 in your original upgrade - was there any problems, and would it be possible to have a beta branch to test it out?

**Comment by whyboris** [comment]
It's worth a try -- feel free to give it a go: electron 4 beta 10 came out 30 minutes ago:
https://github.com/electron/electron/releases/tag/v4.0.0-beta.10
I tried it before but _something_ wasn't working (could have been something else), so I just rolled back to decrease the number of moving pieces, fixed the problem, and never tried with the version 4 beta 🐟

**Comment by whyboris** [comment]
When working on this, should be easy to close this issue too: https://github.com/whyboris/Video-Hub-App/issues/24 👍

**Comment by cal2195** [comment]
I just tried beta 11 there on master and it works! 🎉
