### ISSUE TITLE
Auto-generated clicked tag does not always find videos

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#307]
User emailed me diagnosing this problem:

Naming format for video `first-last_movie-title_production-company` 
Example: `tom-cruise_mission-impossible-fallout_paramount-pictures`
VHA identifies that `tomcruise` should be a tag in the auto-generated tags page, 
Clicking on that tag shows no results, because the actual string on the file is `tom-cruise` and the app is searching for the auto-generated tag of `tomcruise`. 
Seems like the tag is stripping the `-` character when maybe it shouldn't?  

User's suggestion:
> Maybe there is some custom setting that can be added in the future where users can set the delimeter they use to name their files.

My thoughts at the moment: 
I need to clean up the tag auto-generation code -- there _is_ a mismatch between what it detects and how it searches for when you click on the tag.

I replicated: added 5 videos with `tom-cruise` to test:

-  `tomcruise` showed up under the one-word auto-tags (⚠️ bug) 
    - I would expect it to show up as `tom cruise` under the two-word auto-tags!
    - it shows as 5 found, but should show 0 as there are none!

- I added `tom cruise` manually into the auto-tags and it showed up with 0 results (⚠️ bug) 
    - I would expect it to show 5 results

- I added 'tom-cruise' manually into the auto-tags and it showed up with 0 results (expected), but clicking it, it found 5 results (understandable)
    - Unsure how this should play out

I'll work on this, but other thoughts are welcome, and you can also call dibs on making a PR for this, let's just agree on the behavior we want in the discussion below ❤️

**Comment by whyboris** [comment]
Example with `tom-cruise` in 5 file names:

![2019-11-08 10_10_19-Window](https://user-images.githubusercontent.com/17264277/68487517-35e32680-0211-11ea-91a8-9bf545b50c2c.png)

**Comment by cal2195** [comment]
Personally, I think any word boundary should be used to delimit tags.

eg.
`tom cruise`, `tom-cruise` and `tom_cruise` should all generate `tom`, `cruise` and maybe `tom cruise`.

(The name Tom Cruise looks really weird now 😅 )

**Comment by cal2195** [comment]
This can be done in regex using `\b` to match for word boundaries. 😄

**Comment by cal2195** [comment]
And yes, tagging and filtering should use the exact same logic.

**Comment by whyboris** [comment]
Thank you @cal2195 for the `\b` suggestion -- I should have been doing it all along 😅 

#380 will close this 🤝
