### ISSUE TITLE
Off-by-one error in the number of clip snippets created

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#308]
A user reported that:
> setting the number to 5 will generate 4 clips; setting it to 6 will generate 5.

Should be an easy fix 😅

**Comment by LordJon** [comment]
I just facepalmed. This is indeed a thing I just thought I didn't paid enough attention when I added all my libraries haha.

**Comment by basavaraj96** [comment]
Hi, can I take up this issue

**Comment by whyboris** [comment]
Thank you @basavaraj96 -- let me know if you run into any trouble 🙂

**Comment by whyboris** [comment]
Will be closed by #320 

Thank you @basavaraj96 🙇

**Comment by whyboris** [comment]
Closed with #320 
Thank you @basavaraj96 for the fix 🎉
