### ISSUE TITLE
Cmd+Q on Mac doesn't trigger vha file resave

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#31]
If you use `cmd+q` on Mac to quit the app, the vha file doesn't get resaved if required. (Eg. a file renamed) 😢 

The correct behaviour occurs when you quit using the `x` in the window title bar. ❌

**Comment by cal2195** [comment]
Looking a bit more into this, it looks like we need to implement:
```
app.on('before-quit', (event) => {
});
```
And use it to call `initiateClose()` in `home.component.ts`!

Seems like you can't catch `cmd+q` with javascript anymore - also that key combo is there twice for two different functions:
```
// Listen for key presses
  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    // .metaKey is for mac `command` button
    if (event.ctrlKey === true || event.metaKey) {
...
      } else if (event.key === 'q') {
        event.preventDefault();
        event.stopPropagation();
        this.initiateClose();
      }
...

      } else if (event.key === 'q') {
        if (!this.settingsButtons['magic'].toggled) {
          this.settingsButtons['magic'].toggled = true;
        }
        this.showSidebar();
        setTimeout(() => {
          this.magicSearch.nativeElement.focus();
        }, 1);
      }
...
```

**Comment by whyboris** [comment]
Thank you for finding the reference!

https://github.com/electron/electron/blob/master/docs/api/app.md#event-before-quit

Looks like we can just `preventDefault()` in `main.ts` and let the electron front-end handle it 👌

**Comment by whyboris** [comment]
Should be fixed here: https://github.com/whyboris/Video-Hub-App/pull/79
