### ISSUE TITLE
Define favorite thumbnail

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#310]
🤷‍♂ a user emailed me with this request ... maybe useful to others?

Currently, you can drag & drop any image you'd like over any thumbnail and the thumbnail will be replaced.

It looks like the user is interested in selecting one of the many generated thumbnails a particular thumbnail. 

I'm thinking the easiest way would be:
1) hover over the thumbnail until the particular thumb you like shows up
2) right click
3) select "make default" (though I'm unsure what short phrase/word would be good to put there -- I don't want it to be long

Another alternative would be in the "Details" view (right click -> details / ctrl + click / top-right icon when hovering over a thumbnail in thumbnail view) where you see all the screenshots individually -- perhaps hovering over a thumbnail you can click on it to add a star on it -- to indicate it's the "primary preview thumbnail"

Discussion welcome 👍

**Comment by LordJon** [comment]
Not sure if I would use such a feature. Actually now I think about it, I might use it for a filmfestival I work for. I think I would prefer the second methode with marking the thumbnail with a star.
For the festifal we also make our own thumbnails, so linking a custom made thumbnail would be nice too, although that's probably way out of the scope. :p

**Comment by whyboris** [comment]
Adding a custom thumbnail is super easy -- drag and drop any image over any video in _thumbnail view_ 😉

**Comment by whyboris** [comment]
I'll try to implement the star method in the "Details" view -- seems doable ⭐️

**Comment by whyboris** [comment]
Will be released in the next version `2.1.0` 🚀 #327

**Comment by Kotzlowski** [comment]
"Favorite thumbnail" does not apply to details view. For me it should be the first thumbnail shown in details view. I mainly use the details view (1). Currently it shows a random (?) thumbnail, thats not even in the thumbnail collection (right click on video, Details)

**Comment by whyboris** [comment]
Thanks for the catch! I'll update the _Details_ view to show the favorite thumbnail (if it has been chosen).

Currently, every video gets a single screenshot extracted at ~10% into the video and that's the default thumbnail. It will almost never coincide with a screenshot in the filmstrip (which is its own collection of images). This is on purpose -- intended behavior.

**Comment by whyboris** [comment]
@Kotzlowski -- I fixed it 😎 https://github.com/whyboris/Video-Hub-App/commit/bdea404b11048d5a5cc9603730353b603a155b50

Will be part of version `3.1.0` - hoping to release tomorrow 🤞

**Comment by Kotzlowski** [comment]
wow, you are fast. Thank you very much!
