### ISSUE TITLE
Add fuzzy search  

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#311]
Fuzzy search should be super-simple to add by using another library.
This search will allow users to mis-spell the word they are looking for and still find it 🎉 
This would be an _additional_ *live* search (just like the "magic" one) -- added directly below the "magic" search in the pipe order and in the sidebar layout.

Current proposed libraries (numbered for ease of discussion):
1. https://github.com/mattyork/fuzzy
2. https://github.com/farzher/fuzzysort
3. https://github.com/krisk/Fuse

The first challenge is picking one of the three 😅 (other suggestions welcome 🙇 )

**Comment by mcpalmer1980** [comment]
My sidebar has gotten far too crowded. Perhaps fuzzy searching should be added to the magic search instead of a whole new bar. It seems like something a magic search should do.

Perhaps this should coincide with adding custom tags to the magic search bar?

**Comment by whyboris** [comment]
I personally have only 2 searches showing: the _folder_ and _file_ search 🤷‍♂ 
I hope most people simply disable the search features they don't use.
Perhaps you use them all? 😁 
Fuzzy search _can_ become part of the current _magic_ bar, but _magic_ searches for folders or files, while I think the fuzzy search would only search for file names. 
I'm open to more opinions 👍

**Comment by cal2195** [comment]
I think a better option would be to have both bars, and disable whichever you don't use - I can see uses for both (fuzzy could be annoying when you're looking for exact match). 😄

**Comment by mcpalmer1980** [comment]
That is a good point. Perhaps Fuzzy should be a button that enables fuzzy search for any existing bar where it makes sense(file, folder, tag, magic).

**Comment by whyboris** [comment]
Decided to go with [Fuse.js](https://github.com/krisk/Fuse) 🎉 

#340 will be released with public version 2.1.0 😁
