### ISSUE TITLE
Improved Custom Tags

### ISSUE THREAD

**Issue by mcpalmer1980** [whyboris/Video-Hub-App#313]
Custom tags can be a vital feature when searching for or filtering videos. They are used extensively in photo viewers and music players(think genre), but severly lacking in video library software. Searching for this feature led me toward Video Hub App. I still think that a few important additions to custom tags in Video Hub App should be considered.

**Metadata**
I understand that custom tags are stored in a config file instead of as metadata, and that the Video Hub sites advertises that it doesn't alter the video files. There is logic to this, but I think an option to save tags into the file would be a good idea. This of course would suggest that a way to read tags from the meta data should also be included, but this is less important.

**Manual Tags in Magic Tag searches**
I think that custom tags should be included in the 'magic search' bar along with file and folder searches

**Auto Tags in Tag Bar**
Auto tags from the filename should be included in the manual tag bar at the bottom of the screen. Not sure if all tags with frequence > 0 should be included or if there should be a configurable option for this.

**Click to add Tags**
An option to add tags by clicking instead of typing would be great. There are 2 places this might be implemented. The obvious way would be to add the manual tag buttons beneath Add text input in the details dialog. A second, perhaps more effective method to tag videos would be to override the behaviour of the tag buttons in the manual tag bar.

When in detail view and the cursor is active a video's 'Add' manual tag text input box, clicking a tag from the manual tag bar at the bottom of the screen should add that tag to the video instead of to the filter list.

**Comment by whyboris** [comment]
Thank you for starting this discussion!

Several users have emailed me independently asking for a "mass tagging" feature.

One of the biggest challenges I have with that request is figuring out a UI (user interface) / user workflow.

Feels like applying a tag to a large set of videos could be accomplished with a drag-and-drop from the tag tray onto the current gallery, but we'd need a modal to confirm whether the user indeed wants to apply the tag to the current 100+ videos. And I would hate to have to implement any kind of "undo" functionality. 

Since I personally never use tags, I have a hard time picturing the use cases for when people use them and why they'd want to manually tag a collection 🤷‍♂ 😅 

Please do share more suggestions 🙇

**Comment by mcpalmer1980** [comment]
> I have a hard time picturing the use cases for when people use them and why they'd want to manually tag a collections

- O'keefe Music Foundation: I collect their well produced music videos featuring children and teens covering famous rock and metal songs. I have some favourite performers and will add their names to the videos that feature them.
- Tutorials: I occasionally download tutorial videos on various subjects. Some of these fit nicely into folder based categories, such as game design and home repair, while others might require multiple tags, such as engine(Godot, LibGDX, Pygame), genre(Platformer, Shooter, RPG), type(2D, 3D), platform(Linux, PS4, Android)
- Porn: Although not my cup of tea, many people will use Video Hub to play their pornography collection and might like to tag videos by type, actor, fetish, etc.

> Several users have emailed me independently asking for a "mass tagging" feature.

This is more difficult and less useful than people might think. The more important thing is to be able to add existing custom tags to individual videos more easily, such as my 2 earlier suggestions. I well get back to this in a second.

> applying a tag to a large set of videos could be accomplished with a drag-and-drop from the tag tray onto the current gallery

At first thought, the ability to tag all currently visible videos sounds like a good idea, but it actually has little to no use. This would allow you to tag every video in a Hub, in a Folder, or that is already filtered by another tag. In other words, you can already filter it down to the current list, and therefore don't need to tag them.

**Multi-Select**
There is no way to select a video, let alone multi-select them. Adding this feature will adversely effect the current user experience, add very little benefit for mass tagging, and as you mentioned, require an Undo feature to be added. I tried to add Undo to the level editor of one of my games and will not be trying that again.

**Workflow**
A common workflow to tag multiple files would be to hold CTRL, select each one, then use a toolbar or a right click menu to add the tag to them all. Since each file needs to be clicked one at a time anyway, it would be easier to have a 'tag mode' option to the Manual Tag Bar. When in tag mode, instead of opening a video when you click it, the currently selected tag will be added to it.

**Comment by cal2195** [comment]
> **Metadata**
> I understand that custom tags are stored in a config file instead of as metadata, and that the Video Hub sites advertises that it doesn't alter the video files. There is logic to this, but I think an option to save tags into the file would be a good idea. This of course would suggest that a way to read tags from the meta data should also be included, but this is less important.

The problem with this is that this depends on each file system - most file systems don't even have a way to save metadata like this! Some file formats do, but again, it completely depends on the file type! 😢 Not to mention if you tried to move files between file systems and lose all your data...
I had a solution to this, discussed at #178 which might suit your needs?

> **Manual Tags in Magic Tag searches**
> I think that custom tags should be included in the 'magic search' bar along with file and folder searches

I agree, but it should be configurable like the current tag fields. 😄 

> **Auto Tags in Tag Bar**
> Auto tags from the filename should be included in the manual tag bar at the bottom of the screen. Not sure if all tags with frequence > 0 should be included or if there should be a configurable option for this.

Sounds good to me - it should replicate the currently enabled tags.

> **Click to add Tags**
> An option to add tags by clicking instead of typing would be great. There are 2 places this might be implemented. The obvious way would be to add the manual tag buttons beneath Add text input in the details dialog. A second, perhaps more effective method to tag videos would be to override the behaviour of the tag buttons in the manual tag bar.
> 
> When in detail view and the cursor is active a video's 'Add' manual tag text input box, clicking a tag from the manual tag bar at the bottom of the screen should add that tag to the video instead of to the filter list.

This sounds pretty cool - you could even try to guess the tags based on what other videos are tagged similarly! 😄

**Comment by mcpalmer1980** [comment]
> most file systems don't even have a way to save metadata like this!

I should have been more clear about this. The tags should be added only to file types that support tags, not using any OS or partition dependant feature. If the file doesn't support metadata AND the option is enabled, the tags could be saved into sidecar files, such as you suggested in #178

Of course the tags would only be exported from the hub to the files when the user manually requests it from a menu, like in many desktop and mobile photo gallery apps.

On a side note, it would have been my preference to store the tags and other options in sqlite file instead using plain text in an XML file. Then the thumbnails could be stored as glob data and I wouldn't have thousands of extra files added to my system.

**Comment by mcpalmer1980** [comment]
@cal2195 
> This sounds pretty cool - you could even try to guess the tags based on what other videos are tagged similarly! smile

You quoted my first two suggestions for quick tagging videos, but I'm not sure if you noticed my better idea that was included in a response to whyboris. I'm going to duplicate it here just in case.

**Quickly Tagging**
There is no way to select a video in Video Hub, let alone multi-select them. Adding this ability will adversely effect the current user experience, add very little benefit for mass tagging, and as you mentioned, require an Undo feature to be added. I tried to add Undo to the level editor of one of my games and will not be trying that again.

A common workflow to tag multiple files would be to hold CTRL, select each one, then use a toolbar or a right click menu to add the tag to them all. Since each file needs to be clicked one at a time anyway, it would be easier to have a 'tag mode' option to the Manual Tag Bar. When in tag mode, instead of opening a video when you click it, the currently selected tag will be added to it.

**Comment by whyboris** [comment]
In the next version we'll have:
- batch tagging 🎉 select any files, click on tag in tag tray to add tag to all those files
- drag & drop 🎉 drag tags from tag tray into any file to add tag

👍 😎 👍

**Comment by mcpalmer1980** [comment]
This is great to hear. Especially useful when away from keyboard (TV viewing). BTW love the new "play selected files' feature :)

**Comment by whyboris** [comment]
There were great ideas in this discussion. I will remember the suggestions. I'm closing it as I'm trying to clean things up for VHA `3.0.0` release 😅 

We now have batch tagging as well as drag&drop. With 3.0.0 we'll have "select all shown" button that will select all the currently-found videos (based off search or folder navigation). 

Please feel free to open up a new Issue or comment on this one 🤝 

Current priority: successful release of VHA 3 🎉
