### ISSUE TITLE
Multiple Configuration Crash

### ISSUE THREAD

**Issue by mcpalmer1980** [whyboris/Video-Hub-App#314]
Video Hub fails to load after changing the $HOME environment variable to a non-default value.

The Linux version is distributed as an AppImage and saves its data to _$home/.config_. It is common for Linux users to export a custom $config$ or $home$ environment variable to either 
- A: specify where the config should be saved, or 
- B: have multiple configs depending on which shortcut is used to open the AppImage.

An additional feature of AppImage in Linux is to automatically export the $home or $config variable when a folder with the AppImage's name exist in its folder. So if I try to open /wherever/VideoHub.App and the folder /wherever/VideHub.App.home exists, then the app will use /wherever/VideoHub.App.home as the home directory and store its files in /wherever/VideoHub.App.home/.config

Whenever I try to do this with Video Hub App a dialog pops up and immediately vanishes. The app never opens.

**Comment by whyboris** [comment]
I'm sorry I'm not well-versed with how Linux works. 

I would be thrilled if someone fixes the problems you describe 🙇

**Comment by cal2195** [comment]
I believe the variable you're looking for is `$XDG_CONFIG_HOME` - this is what we currently use to store the config files.

You should also be able to use `VideoHub.App.config` as this exports `$XDG_CONFIG_HOME`, while `VideoHub.App.home` only exports `$HOME`, which we currently don't use.

**Comment by cal2195** [comment]
After some experimenting on my linux box, `XDG_CONFIG_HOME` takes priority over `HOME` if it's set, but if it's not, `$HOME/.config` is used instead.

Also, both `.home` and `.config` folders work for me with AppImage - can you confirm you see this when running the AppImage in a terminal?

```$ ./Video\ Hub\ App\ 2-2.0.0.AppImage
Setting $HOME to /home/asd/Desktop/Video Hub App 2-2.0.0.AppImage.home
Setting $XDG_CONFIG_HOME to /home/asd/Desktop/Video Hub App 2-2.0.0.AppImage.config
```

**Comment by cal2195** [comment]
Also, please post any error messages, as I'm unsure what would cause it to crash in any case! 😄

**Comment by mcpalmer1980** [comment]
I don't get any error message. I have tried with the folder method and by manually exporting the $home and $XDG_CONFIG_HOME variables.

All that happens is that a small dialog box pops up for a fraction of a second and then vanishes before I can get a good look. The video-hub-app-2 folder is created, along with the three folders and a _Network Persistent State_ file, but not _settings.json_. I copied over a _settings.json_ but the app still won't start
```
$ './Video Hub App 2-2.0.0.AppImage'
>Setting $XDG_CONFIG_HOME to /media/ThumbA/Apps/Video Hub App 2-2.0.0.AppImage.config
$
```

**Comment by whyboris** [comment]
I'm closing this issue as I don't know how I could help with it and the discussion has dried up.

Perhaps with all the _Electron_ updates since the issue was opened, the app works on Linux again 😅 🤞  -- it certainly worked on _Ubuntu_ when I built the _AppImage_ and installed it 🤷‍♂️ 

Please feel free to comment or open a new issue 🤝
