### ISSUE TITLE
Metadata import / export

### ISSUE THREAD

**Issue by chhutchins** [whyboris/Video-Hub-App#316]
I don't see a metadata import/export function. Does one exist? It would be nice to be able to do a few things:
- Import metadata from web scrapes
- Import metadata that already exists as used in another media organizer
- Export metadata to be used in a hub on another computer

Perhaps there's a work-around or interface that can be used without making software changes?

**Comment by cal2195** [comment]
Hi @chhutchins! 😄 

Some of this functionality exists, although not as complete as I'd like it:

> Export metadata to be used in a hub on another computer

The metadata is stored as plain text json file (the `.vha` file), so you could transfer that to another computer if you'd like, or mess around with the file yourself in an text editor/script.

> Import metadata from web scrapes

This is something I'm very interested in, and I've even implemented myself on my own branch - I haven't gotten around to merging it yet, but if there's interest, I certainly will. See #178.
The basic gist is that you can write your own web scraper to save `.tag` files to your library, and it will import them automatically as tags. This could be expanded to more metatdata if required. 😄 

> Import metadata that already exists as used in another media organizer

This might be harder, and less useful as not everyone would use `insert other media organiser here`. What had you in mind?

**Comment by chhutchins** [comment]
> Hi @chhutchins! 
> 
> Some of this functionality exists, although not as complete as I'd like it:
> 
> > Export metadata to be used in a hub on another computer
> 
> The metadata is stored as plain text json file (the `.vha` file), so you could transfer that to another computer if you'd like, or mess around with the file yourself in an text editor/script.
> 
I take that to mean that I can programmatically change the tags and other metadata by modifying the JSON using python/pandas or another tool. 
> > Import metadata from web scrapes
> 
> This is something I'm very interested in, and I've even implemented myself on my own branch - I haven't gotten around to merging it yet, but if there's interest, I certainly will. See #178.
> The basic gist is that you can write your own web scraper to save `.tag` files to your library, and it will import them automatically as tags. This could be expanded to more metatdata if required. 
> 

Thanks. I'll take a look at #178 

> > Import metadata that already exists as used in another media organizer
> 
> This might be harder, and less useful as not everyone would use `insert other media organiser here`. What had you in mind?

I'm using jriver. I agree that it would be difficult and not very productive to write a custom interface for each "other" media organizer.  It seems to me that if I can use JSON as a metadata input then I can accomplish what I want by writing something up in python. XML -> JSON -> .vha

**Comment by whyboris** [comment]
@chhutchins -- I hope the interface is easy to deal with 😅 
The `.vha` (now `.vha2`) file is a JSON with this structure: 
https://github.com/whyboris/Video-Hub-App/blob/master/interfaces/final-object.interface.ts#L6
Each image element is this:
https://github.com/whyboris/Video-Hub-App/blob/master/interfaces/final-object.interface.ts#L17
Please feel free to reach out with any questions 👍

**Comment by chhutchins** [comment]
Thanks, whyboris. I may spend a little time playing with it this weekend.

**Comment by whyboris** [comment]
It seems that some people might be using the native _tags_ feature in MacOS. Perhaps it's not too hard to allow importing those 🤷‍♂  -- may be worth a look -- could be a quick win 👍 

I think import is the more-important feature than export (if they are to be done in sequence).

**Comment by whyboris** [comment]
I'll try something this weekend: https://github.com/whyboris/Video-Hub-App/issues/178#issuecomment-589839418

**Comment by whyboris** [comment]
PR for automatically importing os-native tags on a Mac: #370 😁

**Comment by whyboris** [comment]
As a bonus, thanks to `osx-tag` https://github.com/keichi/osx-tag -- we can save all the tags to OS-X 👍 

I can't find anything for _Windows_ yet 🤷‍♂ 🙆‍♂ 👌

**Comment by whyboris** [comment]
⚠️ this dependency can't be installed on _Windows_ and I would have to maintain a `mac` branch in order for this feature to exist. This isn't a problem, but I think this may be a mac-only feature for a while.

**Comment by whyboris** [comment]
I figured out a way to import OS-X tags on first scan. I'll try to get this PR #370 merged before VHA `3.0.0` is released 🎉
