### ISSUE TITLE
Tag tray needs scrollability

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#318]
An email come in -- seems like at least one person has filled up their custom tags to the brim 😁 

Let's make a container (create a new one if needed) that holds the tags scrollable 👍

**Comment by navin1551** [comment]
Hi, this is my first time contributing to an open source project and would like to take a shot at this. Can I try to add the scrollability?

**Comment by cal2195** [comment]
Sure thing @navin1551! Go ahead! 😄

**Comment by whyboris** [comment]
Thank you @ScottBWar for fixing this issue 🙇‍♂️ #328
