### ISSUE TITLE
2.1.0 Release

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#339]
I would like to release 2.1.0 as it patches an important bug:
- 2.0.0 sometimes fails to extract screenshots for some videos on some computers 
   - ✅ already fixed in `master`

Finished:
- [x] Merge #338 (improve resolution detection)
- [x] Fuzzy search #311 
- [x] Grey out "delete" in right-click menu when root folder not present
- [x] Offer a _portable_ version of VHA

👂 I'm happy to hear more suggestions

**Comment by frez777** [comment]
> :ear: I'm happy to hear more suggestions

To me an actor section would be awesome, in my perspective it could be as simple as letting the user define an actor name, actor image and to associate videos to this actor

**Comment by whyboris** [comment]
Thank you for the request! Now that I'm working on automatic face detection, (something like) this will likely by the next large feature 🎉

Though not in version `2.1.0`, which I want to create and release in the next few days 🚢
