### ISSUE TITLE
Add Mojave Dark Mode Support

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#34]
Electron v4.0.0 now has APIs to support Mojave's Dark Mode! 🎉 

https://github.com/electron/electron/issues/13387

We should support this! 💯

**Comment by whyboris** [comment]
Should be pretty straight-forward! We have a _dark mode_ in the app already -- it's just a matter of hooking up the setting to trigger the change, right? 😁

**Comment by cal2195** [comment]
Exactly! 💯

**Comment by whyboris** [comment]
Cool -- now I have `Mojave` on my Mac -- I'll be able to add the code and test it out 👌

**Comment by whyboris** [comment]
Will be in `2.0.0` - PR #211 -- waiting for Electron `5.0.7` to be released as it provides a needed bugfix 👍
