### ISSUE TITLE
Update view when video was deleted

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#344]
Currently right-click and `delete` will move the video to the recycling bin, but will not update the gallery -- the video will look like it is still there.

Desired outcome:
Remove video from gallery

⚠️ Caveat
Simply removing element from array will cause the `index` property to be out of whack - so we'll need to re-index the whole array 👌

**Comment by cal2195** [comment]
Side-thought: Is there a reason we need an `index`? Couldn't we just index them by their hash?
This would save on all this recalculation. 💡 

I know the default sort is by index, but this is the same as sorting by full file path...?
🤔 💭

**Comment by whyboris** [comment]
I don't mean to insist on the indexing -- that's just something I implemented before we had the hashes.

I may be misunderstanding the idea you have -- please elaborate if what I write below is off-topic.

The hashes are _not_ unique though -- as there may be two (likely) identical files in a hub with the same hash.  It may matter which of the two (likely) identical files are played -- since one might be corrupt and another not.

I was thinking re-indexing may be easier (just add a new method) rather than re-write a lot of older code.

**Comment by cal2195** [comment]
Good point about the hash uniqueness - that may be a point that needs to be addressed regardless. 🤔 

Haha, and I'm not suggesting we do this *right now*, I just like to think about what future-Boris and future-Cal will be glad we did for easier maintaining and adding features in the future! 😄

**Comment by lemiesz** [comment]
which view does this happen in?

**Comment by whyboris** [comment]
Every view -- currently when you right-click and "Delete file", the file moves to the recycling bin, but the view continues to show the video in the gallery.

**Comment by lemiesz** [comment]
I do not see Delete File in any view. Am I setting up something wrong?

**Comment by whyboris** [comment]
Under _settings_, scroll down to "Various settings" (in 3rd tab -- the one that shows when you open settings) and click "Show 'Delete' option in the right-click menu".

Sorry I don't have any documentation about what features exist and where to find them. The settings menu has a lot of toggles and I hope everyone who uses the app looks at all the options at least once 😅

**Comment by whyboris** [comment]
I have an idea of how to do this without interfering too much with the current code -- I'll likely code it up on Sunday 👍

**Comment by whyboris** [comment]
Was an easy fix with #364 -- and it makes the UX (user experience) so much better 😂

**Comment by whyboris** [comment]
The fix was easy:
1) add `deleted` property (boolean) to an element
2) add a _pipe_ that filters out any elements that have `deleted` property
3) strip out any `deleted` elements before saving .vha2 file 👌
