### ISSUE TITLE
Show full thumbnail for single parent folders

### ISSUE THREAD

**Issue by danjool** [whyboris/Video-Hub-App#348]
![solo-thumb-folder](https://user-images.githubusercontent.com/10146364/73228385-a6745200-4133-11ea-8dfc-100c26495de2.png)

It seems more natural to me that if folder only has one media item, then why not show the whole thumbnail?  

I have this implemented locally already, but either github is being ornery or there is some kind of push access required.  Also I could see where this would be a View Settings toggle button, as different people would have different preferences.

**Comment by cal2195** [comment]
Hi @danjool,

To make a pull request, fork this repo, push your changes to your forked repo and then create a pull request from there! 🙂

**Comment by danjool** [comment]
Thanks for the heads up!
https://github.com/whyboris/Video-Hub-App/pull/350

**Comment by whyboris** [comment]
Thank you @danjool for the improvement -- I think it looks much better!

Sorry took 2 weeks for me to get to merge in your change 🙇 

Closes #350
