### ISSUE TITLE
Backlog 2.X.X

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#365]
Miscellaneous stuff that could be done someday:

### Not Done
- [ ] Run `lint:scss` again 😓 (also see #196)
- [ ] Migrate to `eslint` (since `tslint` will be [deprecated soon](https://github.com/palantir/tslint#tslint)) 
    - probably just copy this: https://github.com/maximegris/angular-electron/pull/410
- [x] Add setting: _Folder view_ show _random_ screenshots rather than first 4.
   - I don't want to set random without an option to disable: some users _might_ find it unpleasant to see folder thumbnails change every time they navigate
- [ ] Check scrolling isn't janky or is making items disappear too soon (as _full view_ used to before, possibly still). Investigate if there are too many repaints happening with dev tools. Reconsider the element shadow - might be slowing things down [ref talk about 60fps](https://addyosmani.com/blog/making-a-site-jank-free/)

Continuation of the previous backlog: #284 

Other ideas welcome 👍

**Comment by whyboris** [comment]
I'm thinking of creating a release for `2.2.0` within the next 5-ish days 🎉 

I think 2 more issues would be good to address before then (I'll fix these; comments welcome):
- Update the colors on the manually-added tags in the details view
    - they are currently blue, even though in the tag tray they show up as yellow 😕 
- Word cloud shows manually-added tags, but when you click on them, the string is added to the _file_ search and not the _tag_ search (and so no video may be found) 😅

**Comment by whyboris** [comment]
I'm updating the _colors_ with #384 but don't feel like fixing the word-cloud bug; will leave that for later 🤷‍♂ (no one has ever emailed me about it, so it's probably a bug rarely encountered, and I'd rather release the next version of the app 👍 ).

**Comment by LordJon** [comment]
Aah is that why the word-cloud tags gives no results sometimes. I assumed it was somerthing in my settings but haven't looked into it yet so I now avoid using the feature hahaha.

**Comment by whyboris** [comment]
Screenshot for `README.md`

![video-hub-app](https://user-images.githubusercontent.com/17264277/82097107-3ed91700-96d0-11ea-8679-87fa3e07cd0b.jpg)

**Comment by orkomlosh** [comment]
_Add setting: Folder view show random screenshots rather than first 4.
I don't want to set random without an option to disable: some users might find it unpleasant to see folder thumbnails change every time they navigate_

so I implemented this ⬆️  . see PR #502 

I implemented it in the folder pipe an added it to the settings + Icon.
tell me what you think.

**Comment by whyboris** [comment]
Thank you @orkomlosh for adding the "Random screenshot in folder" feature 🙇 🤝 😁  #502 🚀

**Comment by whyboris** [comment]
Closing in favor of #574
