### ISSUE TITLE
Sorting by Date Modified in Folder View Doesn't Work

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#368]
Sorting by `Date Modified` in `Folder View` used to work, but it no longer does.

Ideally this should sort by the folders by the latest video in each folder. 🐞

**Comment by whyboris** [comment]
Interesting 🤔 -- I don't remember messing with anything that should affect things ...
Last PRs that touched the `sorting.pipe.ts`: #367 & #363 (4 & 8 days ago)
Any idea when the issue started?

**Comment by whyboris** [comment]
😅  I'm unsure if it ever was able to sort by date 🤔 
https://github.com/whyboris/Video-Hub-App/blob/master/src/app/pipes/folder-view.pipe.ts#L21

I think this is where things would happen, and we manually, explicitly, have to track things. Currently all we track is:
 - totalFileSize
 - totalDuration
 - starAverage
 - totalStars

**Comment by cal2195** [comment]
I believe this did work, before you rewrote my code with a clearer, better version! 🚀 

It's a valuable feature worth implementing! 😄

**Comment by whyboris** [comment]
That makes sense 👍 
This feature should be easy to add (simply tracking the latest timestamp and putting it as a property on a folder). I'll code it up sometime this week 😁 

Cheers 🤝
