### ISSUE TITLE
Current Scanning Method `Stats` All Files, Not Just Videos

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#369]
I know we redesigned this at one point, but I think I'll look into a more efficient way.

The current method works great for folders of **just** videos, but crawls to a snail 🐌 when there's as many `.tag` files and `.jpg` files etc. inside the folder hierarchy too. 🙇 

This is a waste of hard drive bandwidth as we then proceed to filter them out in app.

I'll look into a better solution for this. 😄

**Comment by whyboris** [comment]
Thank you for catching this! 

I only tested folders with a few varied files and with large folders containing only videos, never with large folders with many various files 😅

**Comment by whyboris** [comment]
I'm pretty sure this is the _gist_ that I used when starting _VHA_ (and the code hasn't changed much). I see there are some interesting comments there: 

https://gist.github.com/kethinov/6658166#gistcomment-2692596
- uses `yield`

https://gist.github.com/kethinov/6658166#gistcomment-2936675
- uses a _functional programming_ approach 

https://gist.github.com/kethinov/6658166#gistcomment-2733303
- `async` 

🚀

**Comment by cal2195** [comment]
Looking at this again, this may be a non-issue - looks like you need to stat everything anyway to find out if it's a directory or not. 😢 

But, it would be nice if the whole thing was async!! 🎉

**Comment by whyboris** [comment]
@cal2195 -- thanks to your PR (❤️) with `chokidar` I believe the issues has been solved, right? 😁 

Please reopen if that's not quite correct 😅
