### ISSUE TITLE
Search in a manual tag

### ISSUE THREAD

**Issue by mmega** [whyboris/Video-Hub-App#372]
Capitalization is required when entering manual tags.
![캡처](https://user-images.githubusercontent.com/57275671/75104131-a8ed9d00-5648-11ea-9232-17ee1baa0b8c.JPG)
![캡처2](https://user-images.githubusercontent.com/57275671/75104132-a9863380-5648-11ea-9fde-27365ff1be88.JPG)
![캡처3](https://user-images.githubusercontent.com/57275671/75104133-aa1eca00-5648-11ea-80f5-c1e6cd9427b3.JPG)

Can search for it by typing in lowercase?

**Comment by whyboris** [comment]
Great idea! Let's do `.toLowerCase()` on both search and each string when matching 👍

**Comment by whyboris** [comment]
@mmega -- thank you again for recommending this improvement -- I fixed it with #376 😁
