### ISSUE TITLE
Scroll back to original location when clicking 'UP' inside folder

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#382]
1. When in _Folder View_ scroll down some distance, 
2. open a folder,
3. click the `up` button
4. notice that the app resets the scroll to the top of the page

It would be nice if it went back to roughly where you were before clicking on the folder.

This feature was requested by a user. Seems useful when navigating using folders.

Feels like it may be easy to implement: 
- for simplicity the feature could be available only for the _root_ folder
- simply store the y-offset (or whatever number associated with it) in the component
- make _virtual scroller_ scroll to there
    - it may be possible to use `scrollToIndex` or `scrollToPosition` in _virtual scroller_ to achieve this

**Comment by cal2195** [comment]
Alternative solution to apply to any number of nested folders:

- Scroll to the `imageElement` representing the folder containing the first (or any) video you just came up from.

**Comment by cal2195** [comment]
See [here in image-viewer](https://github.com/cal2195/image-viewer/blob/master/src/app/components/home/home.component.ts#L156-L160) for an example.

That method allows you to move up one folder, showing more images, but scrolls back to the top right image you were looking at. 😄

**Comment by whyboris** [comment]
I discovered a bug in _ngx-virtual-scroller_ 😅 
The `scrollToPosition` does not accept `0` ms 😓 
I'll try to fix it 😁 
https://github.com/rintoj/ngx-virtual-scroller/issues/420

**Comment by whyboris** [comment]
Thank you @cal2195 for the code reference 🤝 -- it was helpful 😁 
I ended up using pixel offset because that maintained the scroll position more-exactly 👌

**Comment by cal2195** [comment]
Does this only work for a single folder level? 🤔

**Comment by whyboris** [comment]
Yeah -- it's a really rough implementation only aiming to handle the _root_ level 😅 

There is also breadcrumb navigation, so to handle all cases I'd have to keep track of depth (since `up` is not the only way to navigate).

Also I didn't add a reset when switching hubs, so it will navigate incorrectly the first time after using the folder navigation in one hub and switching to another if the user hasn't come back to _root_ level 🤷‍♂ 

While it's a hack-y implementation, it will handle (I think) 95% of the cases without causing any more discomfort than before, and significantly improving the navigation experience otherwise.
