### ISSUE TITLE
Auto play 10 screenshots on hover option

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#39]
*Problem:*
Some users prefer to have the thumbnails view cycle through the screenshots without having to move the mouse

*Solution:*
Add a settings toggle that will allow the thumbnails to cycle without having to move the mouse.
If I remember correctly, the code for the cycling is already there, but disabled.

**Comment by whyboris** [comment]
May be best to wait for the new filmstrip component branch to settle: 
https://github.com/whyboris/Video-Hub-App/tree/new-filmstrip
The `new-filmstrip` should make it easier to handle more than 10 screenshots once we start allowing users to extract more 👍

**Comment by cal2195** [comment]
Would also be nice to add the `autoplay` attribute to the video previews in this case! 💯

**Comment by cal2195** [comment]
(and the muted tag! 😂 )

**Comment by whyboris** [comment]
The `new-filmstrip` PR is ready.
We could start work on this auto-play issue once the PR lands: https://github.com/whyboris/Video-Hub-App/pull/44

**Comment by whyboris** [comment]
I think we should delay work on this feature until we've implemented the feature / option to scan more than 10 screenshots 👍

**Comment by cal2195** [comment]
#76 has landed! :tada: Good to go!

**Comment by whyboris** [comment]
Currently working on "full preview view" for the video - I can get this done right after 👍

**Comment by whyboris** [comment]
I'll look into this now

**Comment by whyboris** [comment]
Will look at it tomorrow 👍 
Will also see if I can clean up some old buttons (miscellaneous functionality) that are unsorted and possibly not working 😅

**Comment by whyboris** [comment]
On my `to do next` list 🌊 
Disregard my past self from Feb 25 🤣 perhaps "tomorrow" meant something different in the past 😅
