### ISSUE TITLE
Stop initial scan for total number of videos after 500 videos found

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#394]
Sometimes users want to create a hub from a directory with thousands of files. During the initial "wizard" the app freezes as it tries to find the exact number of videos. 

I think it would be a better experience if the app reported the exact number of videos up to a point (for example 500 videos), after which it reported "over 500 videos found" 👌 

This would make the first step never crash 😅

**Comment by deepank120896** [comment]
@whyboris Is anyone working on this?

**Comment by whyboris** [comment]
No -- please feel free to fix 👍 

I'm thinking even if we detect 1 video it's enough to say "videos detected" -- please feel free to implement as you would like.

Please let me know if you'd like any advice / help / direction 🤝

**Comment by whyboris** [comment]
@deepank120896 -- let me know if you're intending to work on this 🤝

**Comment by whyboris** [comment]
I'll add this feature before release: #412

**Comment by whyboris** [comment]
I'm thinking this feature will not be needed once #383 lands 😁

**Comment by whyboris** [comment]
I'm leaving this issue open just in case someone, who like me, is also annoyed at the app freezing 😅 

This feature will be fixed with #443 - `Video Hub App 3` release 🎉 

No need to work on this issue 👌

**Comment by whyboris** [comment]
Closing for cleanup. Will be released with #443 👍 -- already fixed in the `video-hub-app-3` branch 😎
