### ISSUE TITLE
New Filter for Framerate

### ISSUE THREAD

**Issue by Aer20** [whyboris/Video-Hub-App#396]
Especially when editing video, it is very important not to mix frame rates. It would be helpful, if Video Hub App would
1.) have an option to display of the frame rate rounded to whole numbers unter the video or in one of the corners in the thumbnail.
2.) have a new slider filter according to the frame rate rounded to whole numbers (FROM x fps TO y fps)

**Comment by whyboris** [comment]
Interesting -- I never thought frame rate would be something of interest.

I suspect it's a feature very few people would be interested in. 

I can help direct you where to edit the code so you can build a custom version of this app that will show the frame rates as well 🤝 🙂

**Comment by whyboris** [comment]
I'm closing this issue as I'm not intending to implement it into the app.

Please feel free to reach out if you'd like a hand with adding this feature to your own build of the app 👍
