### ISSUE TITLE
New filter for number of vowels

### ISSUE THREAD

**Issue by Aer20** [whyboris/Video-Hub-App#398]
Videos from the cameras often have few vowels (eg. Clip0001.mp4 = 1 vowel) and with such a function you can quickly see where there are still unlabeled videos.
So I have this feature request:
- New Filter/Slider according to the number of vowels (a, e, i , o, u, ä, ö, ü)

**Comment by whyboris** [comment]
This is much-too-specific for general use I think. 

If you are familiar with coding you can probably implement something like this; I'd be happy to direct you to where to edit it.

You mention "unlabeled" videos -- are you thinking videos that don't have manual tags added? If so, perhaps it makes sense to just have a sort by "number of tags"?

You can already sort by _date added_ which may be related.

Please feel free to share more details about the problem you're trying to solve -- perhaps there is another solution also?

**Comment by mcpalmer1980** [comment]
I think regular expressions might be a good feature that can solve this and other problems

**Comment by whyboris** [comment]
So you're thinking to have a "RegEx" search where a user can enter a regex instead of a string?

Easy-enough to implement 👌 right?

PR welcome 👍

**Comment by mcpalmer1980** [comment]
Should there be a menu option or just a prefix to the string maybe?

**Comment by whyboris** [comment]
I'm unsure how it's typically done. I imagine a simple search bar - like all the rest of them on the sidebar, but it allows you to put in a regex? 🤷 

Suggestions welcome

**Comment by whyboris** [comment]
I have a PR #427 that addresses this issue 😎
