### ISSUE TITLE
New filter aspect ratio

### ISSUE THREAD

**Issue by Aer20** [whyboris/Video-Hub-App#399]
It would be helpful to have a new filter for the aspect ratio of the video
Name in filter : range of aspect ratio
Vertical 16:9 : 0 - 0,64
Vertical 4:3 : 0,65-0,89
Square : 0,90-1,10
4:3 : 1,11 - 1,59
16:9 : 1,60 - 1,89
Cinema 2:1 : 1,90 - 2,10
Cinema 2,35:1 : 2,11 - 20,00

**Comment by whyboris** [comment]
This is an interesting idea. Visually it would be too cluttered to fit it as a horizontal slider in the sidebar, but perhaps it could become a "sort by" feature where it sorts videos from vertical to horizontal or from horizontal to vertical 🤷 

As a filter it may be relatively easy to add to the current setup -- for every video compute the ratio (width/height) and sort by that number.

Will accept an "Aspect ratio" sort PR 👍

**Comment by whyboris** [comment]
Thank you @martincaron for implementing this feature (#423)  👍 🎖️ 🤝
