### ISSUE TITLE
Split rescan into quick and full rescan

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#4]
In order to improve the speed of adding new files to a large library, as well as supporting rebuilding the entire library if files have changed since adding, we should split the rescan function into two modes:

- Quick: Just scan all files, and add any new file paths. *Don't* `stat` any files for sizes except new ones.
- Full: Completely rebuild the library and rescan all metadata, but keep existing thumbnails. Changed files will have a new hash, so will get new thumbnails.

This will allow for both adding new files very quickly, and fixing out of date libraries.

**Comment by cal2195** [comment]
A third option may be useful:

- Verify thumbnails: Make sure all files have thumbnails, and remove any obsolete ones.

That way, `Quick Scan` can be as quick as possible and only deal with new files, but you still have a way to just update thumbnails without rescanning all files.

**Comment by whyboris** [comment]
Thank you again @cal2195 for implementing all these 🙇
