### ISSUE TITLE
Quick file rename

### ISSUE THREAD

**Issue by Aer20** [whyboris/Video-Hub-App#400]
I have the following feature request:
Please implement a very fast file rename: make the filename in the view editable: a click on the filename in the view places a cursor and you can immediately stark typing and on changing the focus (e.g. by clicking elsewhere or pressing ENTER or TAB) the file is renamed.
Like if it would be an input-box with no visible border and transparent background.
This would speed up the workflow when importing new videos.

**Comment by whyboris** [comment]
This could be a bit tricky, but doable.
I imagine this would make the most sense in the _Details view_ where people are adding/removing tags. 

I'd want it behind a toggle (new button) that toggles from regular un-editable title to "renameable" title 👌 

PRs welcome 🙂

**Comment by byrw** [comment]
@whyboris may I work on this?

**Comment by whyboris** [comment]
@byrw thank you 🤝  -- please let me know if you'd like any assistance / advice / etc 😁

**Comment by whyboris** [comment]
🙇 Thank you @byrw for the excellent PR 🎉 
I'll add some styling fixes and merge both through the `renaming-file-intgration` branch 👌 
Details: https://github.com/whyboris/Video-Hub-App/pull/402#issuecomment-616240376

**Comment by whyboris** [comment]
My styling will be added sometime this week: https://github.com/whyboris/Video-Hub-App/pull/407

**Comment by whyboris** [comment]
#407 is done -- now merging #402 and #407 together to create the integration branch PR #408 
I think it's ready 😅 🚀 🤞
