### ISSUE TITLE
Filter for untagged entries

### ISSUE THREAD

**Issue by Kotzlowski** [whyboris/Video-Hub-App#406]
i want to find entries that are not tagged but cannot find something like a negative tag filter. Maybe I just don't know how to do it?

**Comment by whyboris** [comment]
Hello -- thank you for the message 🙂 

There is no way currently to sort by number of tags or show specifically videos that have no tags added.

If you're interested in doing a minor bit of coding, this feature should be very easy to add for yourself (you would build the app on your computer with the change) -- I'm happy to point you to which files need to be edited a bit for this to work.

Most easily -- you would add a filter to sort by the number of tags added, and then you could just sort it 'ascending' and all videos without tags would be at the top.

This isn't a feature I think many people would want (though I could be wrong -- I hope others comment if they do). So I'm not thinking I'll be adding it to the app (at least until more people request it).

🤝

**Comment by Kotzlowski** [comment]
Thanks for your fast reply. I will give it a try. But my programming skills end with hello world. I think i have to download the source code, change something in specific files, rebuild the program, right? What files do i have to start with?

**Comment by whyboris** [comment]
I'm sure you can handle this challenge 😁 

You'll need to install:
- `node` (latest version is fine). It comes with `npm` (automatically, nothing needs to be done). 
- `git` if on Windows install `git-bash` (don't worry over setup settings, the defaults are fine; _git-bash_ will be your "terminal" -- you can use others, but may as well use this one. On _Mac_ you can use the OS default terminal).
- `VSCode` (you can use another text editor, but I recommend this one)

Once it's all installed, in your `terminal`:
- `clone` this repository 
```
git clone https://github.com/whyboris/Video-Hub-App.git
```
- enter into the folder `cd Video-Hub-App` 
- install everything `npm install`
- run the app `npm start`

After that, it's a matter of editing a few files 👍 

Let me know if you want more-detailed directions about any of the steps 🤝 Once you're done, I can point you to which files to edit and what to change 😉

**Comment by Kotzlowski** [comment]
I'm on Windows 10

installed node from node-v12.16.2-x64.msi with the option "Automatically install the necessary tools...". So i now have Microsoft Visual Studio Installer, Python 3.8.2, Windows Software Developer Kit, Windows SDK AddOn, Python Launcher

installed git-bash
The clone thing did work

"npm install" gives warnings
$ npm install

> video-hub-app-2@2.2.0 postinstall C:\Users\Username\Video-Hub-App
> npm run postinstall:electron && electron-builder install-app-deps


> video-hub-app-2@2.2.0 postinstall:electron C:\Users\Username\Video-Hub-App
> node postinstall

  • electron-builder  version=22.4.1
  • loaded configuration  file=C:\Users\Username\Video-Hub-App\electron-builder.json
npm WARN axobject-query@2.1.1 requires a peer of eslint@^5 || ^6 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.1.0 requires a peer of @angular/compiler@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 || >8.1.0-beta <9.0.0 || >8.2.0-beta <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.1.0 requires a peer of @angular/core@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 || >8.1.0-beta <9.0.0 || >8.2.0-beta <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN video-hub-app-2@2.2.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules\@ffmpeg-installer\linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules\@ffmpeg-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules\@ffmpeg-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.4 (node_modules\@ffmpeg-installer\linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm64@4.1.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/win32-ia32@4.1.0 (node_modules\@ffprobe-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules\@ffmpeg-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/darwin-x64@4.1.0 (node_modules\@ffprobe-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules\@ffmpeg-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-ia32@4.1.0 (node_modules\@ffprobe-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-x64@4.1.0 (node_modules\@ffprobe-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 18405 packages in 9.986s

79 packages are looking for funding
  run `npm fund` for details

found 68 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

then npm start:
$ npm start

> video-hub-app-2@2.2.0 start C:\Users\Username\Video-Hub-App
> npm run postinstall:electron && npm-run-all -p ng:serve electron:serve


> video-hub-app-2@2.2.0 postinstall:electron C:\Users\Username\Video-Hub-App
> node postinstall


> video-hub-app-2@2.2.0 ng:serve C:\Users\Username\Video-Hub-App
> ng serve


> video-hub-app-2@2.2.0 electron:serve C:\Users\Username\Video-Hub-App
> wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve


chunk {main} main.js, main.js.map (main) 1.42 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 290 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 626 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 10.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.99 MB [initial] [rendered]
Date: 2020-04-20T23:25:18.909Z - Hash: 358f5b4eaaa11451454d - Time: 7763ms

WARNING in C:\Users\Username\Video-Hub-App\main-extract.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\Username\Video-Hub-App\main-rescan.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\Username\Video-Hub-App\main.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\Username\Video-Hub-App\src\assets\demo-content.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\Username\Video-Hub-App\src\environments\environment.dev.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\Username\Video-Hub-App\src\environments\environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.

> video-hub-app-2@2.2.0 electron:serve-tsc C:\Users\Username\Video-Hub-App
> tsc -p tsconfig-serve.json

C:\Users\Username\Video-Hub-App\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (C:\Users\Username\Video-Hub-App\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (C:\Users\Username\Video-Hub-App\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Username\Video-Hub-App\node_modules\electron\cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video-hub-app-2@2.2.0 electron:serve: `wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video-hub-app-2@2.2.0 electron:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2020-04-20T23_25_21_972Z-debug.log
ERROR: "electron:serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! video-hub-app-2@2.2.0 start: `npm run postinstall:electron && npm-run-all -p ng:serve electron:serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the video-hub-app-2@2.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2020-04-20T23_25_22_062Z-debug.log

**Comment by whyboris** [comment]
Looks promising, though unsure exactly what went wrong. The key line is here:
```
C:\Users\Username\Video-Hub-App\node_modules\electron\index.js:14
throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
```
The suggestion you are seeing is to enter the folder and delete the entire `node_modules` folder and try again 🤔 

I [forgot to mention](https://github.com/whyboris/Video-Hub-App#development) that you _might_ need to install `Angular` -- the JavaScript framework I'm using for making the visual interface for (and most of the functionality of) the app:

In your terminal run this command: `npm install -g @angular/cli` (installs angular CLI -- command line tools).

Perhaps after installing `Angular CLI` and then deleting `node_modules` and running `npm install` again, it might go better this time 🙏

**Comment by Kotzlowski** [comment]
I deleted everything and downloaded the 32 bit instead of the installed 64 bit versions of git-bash and node.
Now everything works!
Video Hub App 2 is on the left and the coding window is on the right (Elements, Console, Sources, Network, Performance... html-window, below is a box with html / body)

**Comment by whyboris** [comment]
🎉 Hooray! 
Now comes the fun part: coding 😁 
I think the easiest thing is to simply add a new way to _sort_ your videos. This way you can sort videos in two new ways "most tags on top" and "least tags on top"

The sorting happens in the `sorting.pipe` file which is a "pipe" meaning stuff goes into it, the stuff gets processed in some way, and stuff comes out out if. In my case - `ImageElement[]` (an _array_ of type "ImageElement" is passed into it, is sorted, and is returned sorted).

You'll need to add a few things in this file (just follow the patterns you see nearby):
- a new "sort type" 
    - https://github.com/whyboris/Video-Hub-App/blob/master/src/app/pipes/sorting.pipe.ts#L5
- a new block with the same sort type
    - https://github.com/whyboris/Video-Hub-App/blob/master/src/app/pipes/sorting.pipe.ts#L184
- a new sorting function that uses the number of tags
    - https://github.com/whyboris/Video-Hub-App/blob/master/src/app/pipes/sorting.pipe.ts#L50
    - this is where you will want to look at the [tags](https://github.com/whyboris/Video-Hub-App/blob/master/interfaces/final-object.interface.ts#L36) property of the `ImageElement`
    - since it's a property that may not exist, you might need `.tags || []` (the "or empty array") so that it doesn't error
    - you'll want to compare the _length_ of the array, so [`.length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length) (the MDN is a great place for documentation about JavaScript)
    - so the final thing might look like `(x.tags || []).length < ...`

Feel free to reach out with questions.

Once you start the app, you can make changes to the code, save the edited code, and the app will restart with the new changes.

You can always log what's happening in the app `console.log(x.tags);` for example -- right before you run the comparison -- to see which things are being compared. The logs will appear on the right side of the app, in the `console` (see top right, 2nd tab)

You'll then need to let the app know how to access this sorting function:
https://github.com/whyboris/Video-Hub-App/blob/master/src/app/components/home.component.html#L920
... the way I found out where, was simply by searching across all the code for the text `alphabetAsc` (which is similar to what you're doing) ...

Now because this line has `sortOptionAlphabetical` you'll want to look for this word in the codebase and see where you'll need to add a bit more code 😉 

Basically this is it -- I just didn't tell you the last 1 or 2 files to update, it's a "homework assignment" 😛 -- just let me know if you get stuck and I'll let you know the rest 🤝 

Cheers!

**Comment by Kotzlowski** [comment]
Thank you for your advanced training course ;-)
But apparently i made some mistakes.
And that's where my logical mind ends.

hmmmm...

- It still shows "SIDEBAR.sortTags" in dropdown.
- It doesn't sort as it should. Something changes in the sorting but i can't figure out what's changing. It's still some kind of alphabetical.


Files in which i have changed something:

1. sorting.pipe.ts
2. home.component.html
3. sorting.pipe.js
4. settings-buttons.ts
5. en.json


**What i have done:**

**sorting.pipe.ts**

added under export type SortType = 'default'
```
    | 'tagsAsc'
    | 'tagsDesc'
```

added under return randomizeArray(galleryArray, currentIndex);

```
    } else if (sortingType === 'tagsAsc') {
      return galleryArray.slice().sort((x: ImageElement, y: ImageElement): any => {
      return this.sortFunctionLol(x, y, 'alphabetical', true);
      });
    } else if (sortingType === 'tagsAsc') {
      return galleryArray.slice().sort((x: ImageElement, y: ImageElement): any => {
      return this.sortFunctionLol(x, y, 'alphabetical', false);
      });
```

added above if (property === 'hash') {

```
    if (property === 'tags') {
      if ((x.tags || []).length < (x.tags || [])) {
        return -1;
      } if (x.tags > y.tags) {
        return 1;
      } else {
        return 0;
      }
    }
```

saved (_is there a save button? i used right click save as_)

**home.component.html** in Notepad++ because the npm start window looks different

added above <option *ngIf="settingsButtons['sortOptionTime'].toggled" value="timeAsc">

```
    <option *ngIf="settingsButtons['sortOptionTags'].toggled" value="tagsAsc">
      &#x25B2; {{ 'SIDEBAR.sortTags' | translate }}
    </option>
    <option *ngIf="settingsButtons['sortOptionTags'].toggled" value="tagsDesc">
      &#x25BC; {{ 'SIDEBAR.sortTags' | translate }}
    </option>
```

```
ERROR TypeError: Cannot read property 'toggled' of undefined
    at HomeComponent_div_57_Template (template.html:926)
    at executeTemplate (core.js:7575)
    at refreshView (core.js:7452)
    at refreshDynamicEmbeddedViews (core.js:8515)
    at refreshView (core.js:7472)
    at detectChangesInternal (core.js:8720)
    at ViewRef.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ViewRef.detectChanges (core.js:10069)
    at SafeSubscriber._next (home.component.html:formatted:1)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:192)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:130)
```

**sorting.pipe.js**

added above if (property === 'hash') {

```
    if (property === 'tags') {
        if ((x.tags || []).length < (x.tags || [])) {
            return -1;
        }
        if ((x.tags || []).length < (x.tags || [])) {
            return 1;
        }
        else {
            return 0;
        }
    }
```

added above else if (sortingType === 'sizeAsc') {

```
    else if (sortingType === 'tagsAsc') {
        return galleryArray.slice().sort(function (x, y) {
            return _this.sortFunctionLol(x, y, 'tags', true);
        });
    }
    else if (sortingType === 'tagsDesc') {
        return galleryArray.slice().sort(function (x, y) {
            return _this.sortFunctionLol(x, y, 'tags', false);
        });
    }

```
**settings-buttons.ts**

added above 'sortOptionTime',

`    'sortOptionTags',`

added above 'sortOptionTime': {

```
    'sortOptionTags': {
      description: 'BUTTONS.sortOptionTagsDescription',
      hidden: false,
      iconName: 'icon-checkmark', // this specific icon makes the button only appear in the Settings menu (not in ribbon)
      moreInfo: 'BUTTONS.sortOptionTagsMoreInfo',
      title: '',
      toggled: true,
    },
```

Now the App shows in dropdown: Default, SIDEBAR.sortTags (up/down), Duration (up/down), Size (up/down), Random

**Video-Hub-App\i18n\en.json**

added above "sortOptionTimeDescription": "Duration",

```
    "sortOptionTagsDescription": "Tags",
    "sortOptionTagsMoreInfo": "Show the tags order option in the sorting dropdown",
```

**Comment by Kotzlowski** [comment]
I have found an error. Replaced alphabetical with tags.
But now nothing happens when i choose the sort option (SIDEBAR.sortTags) up or down.

added under return randomizeArray(galleryArray, currentIndex);

```
    } else if (sortingType === 'tagsAsc') {
      return galleryArray.slice().sort((x: ImageElement, y: ImageElement): any => {
      return this.sortFunctionLol(x, y, 'tags', true);
      });
    } else if (sortingType === 'tagsAsc') {
      return galleryArray.slice().sort((x: ImageElement, y: ImageElement): any => {
      return this.sortFunctionLol(x, y, 'tags', false);
      });

```

**Comment by Kotzlowski** [comment]
ouch
i started npm start again. Now:

```
ERROR in src/app/pipes/sorting.pipe.ts:63:11 - error TS2365: Operator '<' cannot be applied to types 'number' and 'string[]'.

63       if ((x.tags || []).length < (x.tags || [])) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/pipes/sorting.pipe.ts:144:16 - error TS2367: This condition will always return 'false' since the types '"default" | "hash" | "alphabetAsc" | "alphabetDesc" | "modifiedAsc" | "modifiedDesc" | "sizeAsc" | "sizeDesc" | "starAsc" | "starDesc" | "timeAsc" | "timeDesc" | "yearAsc" | "yearDesc" | "timesPlayedAsc" | "timesPlayedDesc" | "tagsDesc"' and '"tagsAsc"' have no overlap.

144     } else if (sortingType === 'tagsAsc') {
                   ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Kotzlowski** [comment]
i changed

if ((x.tags || []).length < (x.tags || []).length) {

the first error is gone but the second not

ERROR in src/app/pipes/sorting.pipe.ts:144:16 - error TS2367: This condition will always return 'false' since the types '"default" | "hash" | "alphabetAsc" | "alphabetDesc" | "modifiedAsc" | "modifiedDesc" | "sizeAsc" | "sizeDesc" | "starAsc" | "starDesc" | "timeAsc" | "timeDesc" | "yearAsc" | "yearDesc" | "timesPlayedAsc" | "timesPlayedDesc" | "tagsDesc"' and '"tagsAsc"' have no overlap.

144     } else if (sortingType === 'tagsAsc') {
                   ~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Kotzlowski** [comment]
and another change (tagsDesc)

npm start works again :-)

added under return randomizeArray(galleryArray, currentIndex);

```
    } else if (sortingType === 'tagsAsc') {
      return galleryArray.slice().sort((x: ImageElement, y: ImageElement): any => {
      return this.sortFunctionLol(x, y, 'tags', true);
      });
    } else if (sortingType === 'tagsDesc') {
      return galleryArray.slice().sort((x: ImageElement, y: ImageElement): any => {
      return this.sortFunctionLol(x, y, 'tags', false);
      });
```

**Comment by whyboris** [comment]
Awesome! It looks like what you did is what was needed to get everything to work out 👍 

I'm guessing you got past the `Cannot read property 'toggled' of undefined` error once you added the `sortOptionTags` object into the `settings-buttons.ts` file 👍 

It looks like the main feature you wanted is now working as you wanted! I'm unsure what you mean by "I made two mistakes." -- is it that some UI (user interface) text is showing up as "SIDEBAR.sortTags" rather than "sort by number of tags" (or some human-understandable text)? If so -- just go to `en.json` and add a `sortTags` property in the `SIDEBAR` section 😉 

The reason your sort only works in one direction is because you're not making use of the `decreasing` boolean -- so rather than `return 1` you should `return decreasing ? -1 : 1;` 

The syntax here looks funky, but in JavaScript, the `... ? ... : ...;` pattern is like saying `if ... then ... else ...` -- search for "ternary" to read about it.

Here's a cool thing you can do now -- if you'd like the next version of my app to include your code, you can share it via _GitHub_! While the feature isn't obviously useful to most users, because it's behind a 'flag' (normally toggled off and can be enabled via settings if the user wants it), I'm happy to include it in the public version of the app 🙂 

The standard process for this is to `fork` this repository (the button is on top-right [here](https://github.com/whyboris/Video-Hub-App)). This will create a copy of my code in your GitHub account. You then will "push" your code to it, and open a "pull request". This will require a few setup steps in your terminal (some `git` commands) -- I'm happy to help you with those steps if you'd like too.

Cheers!

Let me know if you'd like any help with anything 😀

**Comment by mcpalmer1980** [comment]
Searching by the number of tags is actually a fairly common features in image gallery apps. I consider Video-Hub to be the video equivalent and would definitely use this feature. Mostly just to find untagged videos so I can tag them.

**Comment by whyboris** [comment]
Good to know!
I'm sadly not very familiar with image gallery apps so it's good to know. I may as well add this in 🤷‍♂️ 

@Kotzlowski -- are you interested in submitting your code, or should I just replicate it on my own?

Cheers 🤝

**Comment by Kotzlowski** [comment]
I uploaded the changed files to the fork manually file by file and created a pull request.

How do i make my own Video-Hub-App out of it so that i don't have to use Git Bash / npm start all the time?

**Comment by whyboris** [comment]
Hey! Just so you know, if you get more into programming stuff, a lot of the procedures become faster. For example, rather than adding the code changes file-by-file there is a `git` command that lets you push all the changes to your fork 😉 -- I'll be happy to help whenever.

Whenever you want to _build_ the app from your code, you just run a command (all currently-available commands for this project are listed in `package.json`):

```
npm run electron:windows
```
https://github.com/whyboris/Video-Hub-App/blob/master/package.json#L36

This will create an executable file in the `/release` folder wherever your code is 👍 

And thank you for the PR (pull request) 😁

**Comment by whyboris** [comment]
Thank you @Kotzlowski for your code 🤝 

I have copy-pasted your work #414 into #415 (because there were too many whitespace changes otherwise). So your code is in `master` and will be released with the next release 🎉

**Comment by Kotzlowski** [comment]
Thank you @whyboris for your big support and release 2.2.3 :smiley:
