### ISSUE TITLE
Windows 10 maximize, close, reopen position incorrect

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#413]
On Windows 10:
1. maximize app
2. close app
3. open app
4. observe that the top bar extends above the screen, making the close/maximize/minimize buttons harder to press.

Should fix 😅 💦

**Comment by martincaron** [comment]
Tested on Windows 10, but observed a different behavior : 

After executing step #`1`, steps #`2` and #`3` are **not necessary** to observe behavior in #`4`

I'll take a stab at it, hopefully i'm not working on something different.

**Comment by martincaron** [comment]
Disregard the previous comment about a different behavior. I got mixed up. I can reproduce the same behavior. 

I think it may be considering the window `frame` when exporting the bounds to save.

**Comment by whyboris** [comment]
I'm pretty sure everything was working in version 1.0.0 -- so since then, perhaps Electron changed its behavior, or a new version of Windows causes trouble 🤷‍♂️ ... just guesses here -- I've spent 0 time so far looking into the issue 😅 

I'll take a look if you'd prefer to work on something else 🤝

**Comment by martincaron** [comment]
Got this working in Windows 10. Looks like it was a combination of two factors :
- Frameless BrowserWindow
- Exporting/Saving the bounds on exit included the frame pixels.

I'll submit a PR

**Comment by whyboris** [comment]
Thank you @martincaron for the fix 🙇‍♂️🎖🎉 #425
