### ISSUE TITLE
[shortcuts] Command + H on Mac shortcut conflict

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#426]
`Command` + `H` is the Mac command to hide the app which some users may use.

In VHA the same command hides all the panels which doesn't make for a good UX (user experience).

I'm open to suggestions for the fix. The easiest is probably reassigning the VHA shortcut to something else.

**Comment by martincaron** [comment]
How about `Command` + `K` for Kiosk mode since I think that might be the underlying intention. Like Chrome's Kiosk mode ?

**Comment by whyboris** [comment]
I love the `K` for "Kiosk" ✅ 

This is a 2-line change that is perfect as a `good first issue`. 

If no one picks it up, I'll do it on the day I'm releasing the next version of the app (whenever that is; no sooner than a month from now probably) 🤝

**Comment by whyboris** [comment]
Let's wait until #443 lands as it touches the shortcut code 👍

**Comment by whyboris** [comment]
👋 hello @martincaron -- the huge #443 finally landed 😅 

Let me know if you'd like to fix this issue 😁

**Comment by orkomlosh** [comment]
can also take that one, waiting for approval

**Comment by whyboris** [comment]
Hey @orkomlosh -- thank you for your contributions 😁 

Please feel free to feed two birds with one scone 😉 by adding changes for this in your already-open PR #494 -- or as a separate PR -- whichever is most convenient for you 🤝

**Comment by whyboris** [comment]
Thank you @orkomlosh for the fix #494 🎉
