### ISSUE TITLE
Sometimes thumbnails are small on startup

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#431]
Occasionally when starting the app the thumbnail size isn't remembered and is shown as very small. A simple zoom-in/out or switching of views and back fixes the problem.

Unsure what the cause is. There's probably a hack-y way of fixing it too. Would be cool to also figure out why it's happening.

**Comment by jamesd35** [comment]
What OS does this error occur on? I wasn't able to replicate on linux. Or maybe it occurs when there are over some number of videos in the hub?

**Comment by whyboris** [comment]
I've seen this on _Windows_ -- unsure if it happens on other OSes. 

Perhaps it has something to do with the app starting up with a very small window to show the loading animation - before it resizes to the last-window-size. 

Other thoughts ideas welcome 👍

**Comment by whyboris** [comment]
It's such a hard-to-track-down bug, and I've personally not seen it in months ... I'm closing the issue unless someone can reliably reproduce it 🤝
