### ISSUE TITLE
Default Player on Linux

### ISSUE THREAD

**Issue by mcpalmer1980** [whyboris/Video-Hub-App#433]
The change default player dialog filters files by the '.exe' extension without any options to show all files. Linux does not use this extension, and I doubt Mac does either. I worked around this by creating a bash script and naming it player.exe.

The common uses for selecting a custom player instead of using the system default would probably be to use a 'portable' player on a thumb drive, or to use different configuration settings when launched from Video Hub App instead of the file manager.

It might be difficult to filter the file select dialog to show files with the executable flag set on Linux(and mac?). The easy solutions would be to show all files when selecting a default player on Linux, or to let you select 'All Files' from the non-functional drop-down box that's already in the dialog box.

**Comment by whyboris** [comment]
I try to make the app as easy to use for the greatest number.

The custom player on Windows and on Mac works well. I don't know much about Linux which is why the option isn't available for Linux.

This is the line which needs to change to allow Linux video players:
https://github.com/whyboris/Video-Hub-App/blob/master/main.ts#L456

What are the appropriate extensions? `AppImage` ?

**Comment by mcpalmer1980** [comment]
Unfortunately there is no appropriate extension. Sure, AppImage is fairly popular, but most binary files have no extension at all. I suppose adding AppImage and sh would serve most users, or just add something like:

```
  filters: [
    { name: 'Executable', extensions: ['exe', 'app', 'sh', 'bat', 'AppImage'] },
    { name: 'All Files', extensions: ['*'] } ]
```

I would love to be able to just type in a command, such as:

`
smplayer -config-path /media/Data2/Apps/smplayer`

A quick look through Electron documentations found no way to type a file/command into a open file dialog, so adding this feature would require a third button on the Main Settings page.

_Preferred Media Player:  'Select', 'Enter Command', 'Use System Default'_

My solution was to create a plain text script file called 'player.exe' with one line in it

`smplayer -config-path /media/Data2/Apps/smplayer "$@"`

**Comment by whyboris** [comment]
I like the addition of "All Files" as a simple alternative for those who know what they are doing 👍 

Thank you for the proposed solution -- PR welcome 😁

**Comment by whyboris** [comment]
Thank you @mcpalmer1980 -- I implemented this change -- it will be available in the next version of VHA 🎉 
https://github.com/whyboris/Video-Hub-App/pull/432/commits/ce20aa7e30088c99dfe87875c4eab71a49e62b0d

**Comment by whyboris** [comment]
I believe since we allow users to select 'All Files' now, the issue can be closed.

Please reopen if this issue still persists 🤝
