### ISSUE TITLE
[shortcuts] Add Shortcut for toggling Tag tray

### ISSUE THREAD

**Issue by martincaron** [whyboris/Video-Hub-App#435]
It would be useful to see a shortcut for toggling the tag tray at the bottom. Same way we can currently toggle the side-bar search with `command` + `b`

`command` + `t` is already taken by the auto-tag modal so not sure which shortcut to propose.

**Comment by whyboris** [comment]
I'm open to suggestions for which key to use for the keyboard shortcut.

PR welcome with any key (we can later change it if we decide another key is better).

**Comment by martincaron** [comment]
Ok. Based on what's available I'm proposing `command` + `y`

**Comment by whyboris** [comment]
Thank you for the suggestion 🙂 

This is a simple code change I recommend leaving for `good first issue` for whoever is starting out with coding. I'm happy to assist if you have questions.

If no one volunteers a PR I'll fix it a day or two before releasing the next version (at least a month from now) 👌

**Comment by whyboris** [comment]
🎉 Great news! 
I implemented letting users change the shortcut keys! #432
It's still very WIP, but I'm sure I'll get it 💯 before the next release 😎 
I'll add this shortcut with the default of `y` to toggle it 👍 
Cheers!

**Comment by martincaron** [comment]
Nice. Good stuff!

**Comment by whyboris** [comment]
Let's wait until #443 merges 👍 -- it moves the shortcut code to another location 🔀

**Comment by whyboris** [comment]
@martincaron -- I've finally merged #443 🎉 

Are you interested in adding this feature yourself or would you like me to do it? I'm happy either way 😊

**Comment by orkomlosh** [comment]
Hi, if needed I can work on this and on #441  since it's related

**Comment by whyboris** [comment]
Thank you @orkomlosh for the fix #494 🎉
