### ISSUE TITLE
Filter down the Tag Tray based on videos

### ISSUE THREAD

**Issue by martincaron** [whyboris/Video-Hub-App#436]
The manual tag tray currently displays the entirety of the tags regardless of video subset currently being displayed by search criteria. 

It would be nice for the tag tray to react with the same behavior as the Word Cloud. That is, further filter the manual tags based on the current video subset.

**Comment by whyboris** [comment]
This might not be very easy (though likely doable), unsure from my memory of the code.

PR welcome -- I imagine we could have a simple toggle in the tag tray that either shows _all_ tags or only ones that are found within the current search results.

If you're making a PR, don't worry too much about making the UI pretty -- I can clean it up afterwards 👌

**Comment by martincaron** [comment]
I started working on this. Should have something for PR shortly

**Comment by whyboris** [comment]
Hey @martincaron -- let me know if you'd like to finish your PR or if you'd like me to take over where you left it and finish it off myself 👌 🤝 👍

**Comment by whyboris** [comment]
It seems like this functionality is already present in this form: when you enable manual tags, disable auto-generated tags based on file names, and you open up the _Word cloud_ - the tags will be filtered based on search results ✅ 

Related PR: #589 

I'm still going to look at the PR you opened - just after I release version 3 🤝

**Comment by whyboris** [comment]
I have added buttons to the _Word cloud_ with #590 - which should make it more clear about what the word cloud is based off 😅

**Comment by whyboris** [comment]
@martincaron -- I think this feature may be obsolete -- as the `Word cloud` bottom tray updates with the current view -- and it can be set to display _only manual tags_ (or any combination of manual tags, auto file tags, and auto folder tags). 

I think there's no need to have both, _Word cloud_ *and* _Tags_ update when viewing 🤔 

Please let me know if you agree or disagree 👌 

The benefit of _NOT_ updating the tag tray when the search changes is that the users can then drag & drop (selecting from _all_ the tags) any tag onto the currently-displaying videos. If the tag tray updates, they will also not be able to go to go to "batch mode" and add any new tags to the found videos. All this, of course, unless we add _yet another setting_ to enable/disable the filtering of tags when the gallery view updates 😖

**Comment by whyboris** [comment]
@martincaron -- I'm closing the issue as I think it's been solved with the current `Word cloud` feature in the bottom tray.

Just comment if you think I should reopen 🤝
