### ISSUE TITLE
Allow delete bypassing recycling bin

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#438]
#397 - users are having trouble deleting over network drives

This is because I'm using [trash](https://github.com/sindresorhus/trash) to send files to the _Recycling Bin_ / _Trash_ instead of the destructive `rm path/to/file.mp4` command 😅 

Since making it work over network drives requires some setup, let's instead do this:

### What to do:
1. Add a new button below the "Show 'Delete' option in the right-click menu"
2. Make the button a boolean that makes the app send over the boolean value to `delete-video-file` method in `main.ts` which will
3. Run `rm path/to/file.mp4` 👌

**Comment by jamesd35** [comment]
Hi can I work on this?

**Comment by whyboris** [comment]
Thank you @jamesd35 for the feature addition 🙇 

Solved with #453 -- will be released along with v3 later this year 🤝
