### ISSUE TITLE
Discord channel?

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#439]
Hey everyone 👋 

I see many projects have a [_Discord_](https://discord.com/) (or some other chat) channel.

I'm unsure what the benefit of it would be, but please comment if you think there's a good reason for it for this project.

Cheers!

**Comment by LordJon** [comment]
Hey Whyboris. I haven't seen Discord being used for github projects yet but I do know it can be a very usefull communication tool for fast communication and brainstorming. It's less usefull if you want to find specific information (as opposed to github comments or a forum).
I think it could be interesting though.

Small tip if many people would join such a discord server: do not allow everyone to use the @here tag as it can be annoying if used a lot (everyone gets an notification).

**Comment by whyboris** [comment]
There doesn't seem to be much interest in this. I'm closing the issue.

Please feel free to comment / open a new issue if you think it's worth having 👍
