### ISSUE TITLE
Tag Tray Improvements

### ISSUE THREAD

**Issue by martincaron** [whyboris/Video-Hub-App#442]
Opening up discussion based on two previous exchanges: 
- **PR** #437 : discussed merging the Word Cloud with the Tag Tray and a number of other items
- **Issue** #403 : discussed consistency of the behavior when clicking on a tag anywhere in the application

**Propositions** : 
1. Move the `Word Cloud` into the `Tag Tray` and treat it as an optional view the user can toggle (see point 5 below). This would :
> - streamline all UI/UX for tags under one spot. clean.
> - clean up some duplicate code
> - consolidate some settings
> - give the word cloud more room to breathe

2. Optionally include auto-tags (files & folders) in the Tag-Tray. Thus not limiting it to Manual tags.
> - include/exclude any combination of tag types (auto-file, auto-folder, manual) by recycling those settings.

3. Color code the tags based on type (like in details view)
> - Re-using consistent visual cues
4. Always use the same behavior when clicking on a tag (see Issue #403) by using the `Tag filter`.
5. Render the results as couple different views within the Tag Tray. (User's choice.) 
> 1. The weighted Word Cloud view
> 2. or the current pills view

**Keep the ability to** :
- assign via batch mode
- filter by string (textbox)
- remain contextual to the current video subset (Issue #436 )
- display counts
- sort by frequency or alphabetically

**Downsides**  :
- Users who use both the Word Cloud and the Tag Tray wouldn't have them simultaneously anymore. (would have to toggle back and forth)

I can take a first stab at some of this

**Comment by martincaron** [comment]
@whyboris in **PR** #437 you mentioned : 

> I wonder if it would be simple to hook into the auto-tags and also show those in a third mode?

were you referring to the popup dialog that allows you to `delete` keywords ? Or just the regular auto-tags as being included in the results ?

**Comment by whyboris** [comment]
Sorry I wasn't very clear.

You were suggesting to start using the space of _Tag tray_ to show tags (as currently), but also word cloud. The "auto tags" (the feature which shows you two columns of "tags" - most-common words inside file names) may also be useful to show in the tag tray (since the tag tray has a lot of space).

I'm unsure if it's useful, but if it's very easy from the code perspective, perhaps we may as well provide the option.

If we go in this direction, there might end up being many 'modes' for the tag tray. In that case I could implement a "tab" system (like the settings) which would make it very clear which 'mode' is being shown in the 'tag' tray 🤔  The auto-tags version of the tray need not get filtered based on what videos are showing - tag tray just might be a useful place (since currently you can't keep the auto-tag modal showing while browsing the gallery). It may be worth breaking up the single-word and multi-word tags into separate 'views' (or 'tabs') 🤔 

To be clear -- I'm not saying you should add auto-tags into the tray -- only try it if you want to.

I'm currently focusing on refactoring the app to allow using more than one source folder. I suspect this will take me at least a few weeks (I still have a full time job to attend to 😜 ). I'll be happy to coordinate / collaborate on this feature but might not be as quick as I'd like.

**Comment by martincaron** [comment]
Very clear. That all makes sense to me.  
Happy to leave the UI portion 😜
I don't suspect I'll have anything for review for at least a week or so.

**Comment by cal2195** [comment]
Just chiming in on this!

I personally love the word cloud, and never use the tag tray. My main problem with the tag tray is that:

1. It seems to take a while to load. (Maybe this has been addressed recently).

2. I don't like that it hovers over the video grid content.

3. It doesn't contain all the tags (auto, folder etc.)

I would be very supportive of syncing the two views to use the same code, each both displaying all enabled tags (you can toggle auto and folder tags already). This would make a lot of sense! 😄 

But unless the tag view became a fixed view (like at the bottom, or the opposite side - fixed like the current sidebar), I'd advocate for not removing the word cloud, and just deduplicating the common code to make them easier to maintain! 🤔 

Maybe you weren't suggesting removing the word cloud altogether, but I just wanted to show the word cloud some love! ❤️

**Comment by whyboris** [comment]
Hey Cal, I probably should have a glossary as my app has grown in size 😅 

The *Tag tray* we are talking about is one that shows _manually added tags_ and it slides from the bottom of the screen (only obscuring ~170px of screen space).

The *auto tag* currently show up in a _modal_ (covering up the entire gallery) -- I think you're worried we want to use this thing as default 😅 

I'm thinking of allowing users to _see_ the auto-tags in the tag *tray* as an additional place to see them (and keep them open).

ps - the _auto tags_ load slowly only the first time you open the modal (perhaps I could improve the algorithm for the first-open), they will open instantly ever time until you switch to a different hub or re-open the app.

**Comment by whyboris** [comment]
I recently unified the `word cloud`, `similar videos`, and `tags` into a single tray on the bottom (and added a `recently played` as well) with #553 

This addresses `Proposition 1` ✅ 😁 😎 

Now that there's a unified system for handling stuff in the tray, it may be somewhat straight-forward to add the auto-tags into the tray as well. Though visually it might be a bit cluttered, and I'll need to think about how to make it look good. 

Given that I'm focusing on version `3.0.0` release this feature might wait until after.

I'm open to PRs that add other features -- please feel free to discuss here or open a new issue 🤝 

Cheers ❤️

**Comment by whyboris** [comment]
_possibly related_: 

The _Word cloud_ functionality is really nice that it's in its own tray: when you enable manual tags, disable auto-generated tags based on file names, and you open up the _Word cloud_ - the tags will be filtered based on search results ✅ 

Related PR: #589 

I'll revisit this issue after version 3 is released 🤝

**Comment by whyboris** [comment]
I have added buttons to the _Word cloud_ with #590 - which should make it more clear about what the word cloud is based off 😅

**Comment by whyboris** [comment]
I'm closing the issue as I think most of it has been addressed with the addition of the new `Word cloud` in the bottom tray (and its improved, tag-including functionality) 🎉 

As a side-note: the `auto tags` has also been improved - it no longer locks up the UI when opening (and as always, it will open instantly after it has been opened once, until you leave the current hub). And as a second bonus, the 1-word and 2-word auto-tags can be scrolled independently 😎
