### ISSUE TITLE
main-filenames as configurable option

### ISSUE THREAD

**Issue by frez777** [whyboris/Video-Hub-App#445]
I would like to do a feature request: **to have an option to add new file extension on-the-go** (I'm talking about the file main-filenames.ts which defines what kind of file the video hub will try to import).

Some people may have some video files that works with ffmpeg but its not imported by default because the file extension is not on main-filenames.ts file, some of them maybe not worth add for everybody like a `.part` file that may have unfinished downloaded file video that ffmpeg can work with, or a different/customized file extension not very used.

Another nice think would have an option to try to import every file doesn't matter the filename, of course with a warning on this option to people avoid using it without knowing what its about, could be very useful for video-only directories.

**Comment by whyboris** [comment]
Seems doable 👌 

PR welcome. I imagine in the _main settings tab_ (3rd tab - the one that opens by default) below all the "select default video player" options 👍 

I'm guessing it would accept a comma-separated list of extensions (without periods), so
```
part, abc, xyz
```

Other suggestions welcome for how to handle it 👍

**Comment by frez777** [comment]
I tried so far to implement the last thing a mention on this issue, which is an option to skip the extension check, because its easier and I'm not a developer, my skills are pretty bad. but unfortunately it didn't work.

What I tried was this:

---
```src/app/common/settings-buttons.ts```:
add:
```    'searchForAllFiles'``` on SettingsButtonsGroups constant

and
```
  'searchForAllFiles': {
    description: 'BUTTONS.searchForAllFilesDescription',
    hidden: false,
    moreInfo: 'BUTTONS.searchForAllFilesMoreInfo',
    title: 'BUTTONS.searchForAllFilesHint',
    toggled: false
  },
``` 
on SettingsButtons constant

---
```i18n/en.json```:

```
    "searchForAllFilesDescription": "Skip the file extension check before trying to import a file",
    "searchForAllFilesHint": "Skip the file extension check",
    "searchForAllFilesMoreInfo": "Beware that this option will make the import process try to import all files, even non-video ones, if unsure keep it desabled",
```

---
```main-support.ts```:

add an exportable variable:
```
export var skipExtensionCheck = false;
```

and changes the if responsible for the check:
```
if (skipExtensionCheck === true || (acceptableFiles.includes(extension.toLowerCase()) && !file.name.match(fileIgnoreRegex))) {
```

---
```src/app/components/home.component.ts```:

import the variables:
```
import { ImportStage, skipExtensionCheck } from '../../../main-support';
```

and add the value from stored button value:
```
skipExtensionCheck = this.settingsButtons['searchForAllFiles'].toggled;
```

**Comment by whyboris** [comment]
Hey @frez777 -- let me know if you'd like me to help you with anything.

If you no longer have the time for this, no worries. If you're willing to share your code. please open a PR (pull request) with the changes you've made -- don't even worry if there are merge conflicts or remaining bugs 👌 I can finish things off. It's easier to finish what you started than to do everything from scratch 🤝 

Cheers -- hope all is well 🙂

**Comment by orkomlosh** [comment]
can also try help with this

**Comment by whyboris** [comment]
@orkomlosh -- thanks for the offer! 
@frez777 -- let us know here if you still prefer to finish fixing this issue 👍 else, @orkomlosh feel free to take it on 🤝

**Comment by whyboris** [comment]
@orkomlosh -- if you're still interested in this (if you'll enjoy adding this feature) please feel free to take it 👌 👍 🤝

**Comment by orkomlosh** [comment]
Sure no problem, just to understand what to implement.
I can see in this thread 2 options that are not completely related:
1. add option in settings to add list of extensions.
2. add option in settings to skip extension check.

I can try and add both, just wondered what you prefer.

**Comment by whyboris** [comment]
Thank you! 🙌 

I think (1) is the only option we'd want: just an input field with a comma-separated list of extensions (without periods), e.g.
```
part, abc, xyz
```
Do let me know if you think there are scenarios where (2) is likely. My best guess as of now is there is, for a very few users, some obscure specific file format that they'd like and the app skips it. Disabling all checks would pollute the app view with miscellaneous stuff like .txt files etc.

**Comment by orkomlosh** [comment]
Added this functionality to main.
See referenced PR.
Closing this issue,
Works like charm!

**Comment by whyboris** [comment]
Thane you for the feature addition #507 🚀
