### ISSUE TITLE
Progress bar in Windows taskbar / MacOS dock

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#45]
This is super simple and would be a nice polishing touch: 
> *progress bar in the Windows taskbar / MacOS dock*

Implementing it is about 1 line of code!

https://electronjs.org/docs/tutorial/progress-bar

**Comment by cal2195** [comment]
Sounds great! 👍

**Comment by whyboris** [comment]
Will get closed with https://github.com/whyboris/Video-Hub-App/pull/77 👌
