### ISSUE TITLE
Allow exclude / ignore of directories / folders

### ISSUE THREAD

**Issue by CrendKing** [whyboris/Video-Hub-App#450]
It seems currently VHA2 can't exclude directories when creating hub. To workaround this, user needs to restructure their existing files (e.g. moving `C:\videos\exclude_this` out of `C:\videos`), which is inconvenient. Exclusion is common feature available in many other organizer applications. Suggest to implement this.

Alternatively, VHA2 could consider implement feature that allow multiple directories as source for a hub (e.g. `C:\videos\include_this_1` and `C:\videos\include_this_2`). Both inclusion and exclusion could be useful in certain situations, so why not implement both if you have resource.

**Comment by whyboris** [comment]
Thank you for the suggestion!

I'm currently working on allowing more than one folder as the source of the hub 👍 
- https://github.com/whyboris/Video-Hub-App/pull/444
- https://github.com/whyboris/Video-Hub-App/pull/443

Excluding folders seems like it would be useful to some people. I'll see if I can add that feature with `3.0.0` release 👍

**Comment by CrendKing** [comment]
Multi source could serve the same purpose. Thanks.

**Comment by whyboris** [comment]
VHA `3.0.0` will have multiple 'input' / 'source' folders so I'm closing this issue.

Please feel free to comment / create a new issue if you think it's still worthwhile trying to get the "exclude" to work.

ps - it might be a bit tricky to get "exclude" to work 😅

**Comment by adamwinn** [comment]
@whyboris I believe excluding a folder is different, and has different results, compared to having multiple input sources.  I think there should be an option to exclude folders.

Let's say I have a directory full of 100 folders, named folder_1, folder_2, folder_3, etc and I want to exclude folder_3, but include any new folders that are created.  When I add new folders named folder_101, folder_102, folder_103, etc, they will be included and only folder_3 is excluded (which is the desired behavior)

If we go with the multiple input approach, when folder_101, folder_102, folder_103, etc are created, then I have to go back in and add those new folders.  Then next month I have to add more new folders (folder_104, folder_105, folder_106), and then the month after that add even more folders, and so on.

So an exclude folder is different than allowing multiple input sources

**Comment by whyboris** [comment]
It's not a bad feature to allow excluding of a folder. But at the moment I have my hands full just getting everything to work.

If this feature were to be added, it would be far in 2021 -- definitely not this year.

**Comment by adamwinn** [comment]
Please re-open the issue so it is not lost on the radar

**Comment by whyboris** [comment]
👌 I'll keep this issue open as an invitation for someone to code it up and open a PR for it 👍 

I would rather work on the _facial recognition_ feature (that's already 50% functional as of about 1 year ago now -- I just can't find time for it with all the minor features and the version `3.0.0` release 😓 )

**Comment by whyboris** [comment]
Just a comment:

It would clutter the UI (user interface) quite a bit to allow users to _exclude folder_ during the creation of a hub (there are already very many settings that may be overwhelming).

It _could_ make sense to allow users to exclude folders from the "Current hub" tab in the settings, after they have already created a hub.
