### ISSUE TITLE
Organise thumbnails by prefix folders

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#46]
With 10,000 files, 30,000 thumbnail/preview files will be generated. Currently, these are all stored in a flat structure in the `vha-` folder.

This makes it very hard to list the folder in your file manager with so many files! An improvement would be to sort these previews by prefix folders:

We could have 16 folders (0-F), or 256 (00-FF), and store each image by the first letters of the hash. Eg. a hash of 46afb78c.jpg would be stored in the folder `vha-test/46/46afb78c.jpg`

**Comment by whyboris** [comment]
I won't oppose if you'd like to implement such a feature -- though I'm just thinking most people don't plan to open the `vha-` folder. 

This feels like it will add quite a bit of complexity and I'm unsure if the benefits are so great.

Also the irony of the file manager having trouble viewing that many isn't lost on me 🤣

**Comment by cal2195** [comment]
While it's true for most users, while developing it's quite handy to see that folder, and some users to like to delve into the working cogs of the app! 👍 

Would be a nice improvement I think, and it's not really any complexity!

**Comment by whyboris** [comment]
I won't stop you from putting it in 👍
