### ISSUE TITLE
Open video from screenshot clicked on filmstrip view

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#470]
Currently you can open a video from the screenshot clicked in the _Thumbnails View_ but not in the _Filmstrip View_.

Would be cool to add it in -- should be just a bit of math 👋 

Happy to help anyone who tries to add this feature 🤝

**Comment by sezalmittal987** [comment]
Can i work on this?

**Comment by whyboris** [comment]
Awesome! Please let me know if you have any trouble with it 👍

**Comment by sezalmittal987** [comment]
Okay Thanks!

**Comment by sezalmittal987** [comment]
i think video is playing from starting even in thumbnails view ....

**Comment by whyboris** [comment]
There is an option in the settings to play a video from the screenshot clicked; you'll also have to manually point the app (in the settings right next to the other button) to the location of the video player you want to use (only 3 video players officially supported).

Please let me know if you have trouble with that 🤝

**Comment by sezalmittal987** [comment]
Oh ya , I see

**Comment by walstonjd** [comment]
can I work on this?

**Comment by whyboris** [comment]
Hello @walstonjd -- thank you for the offer!

@sezalmittal987 -- are you thinking of calling dibs on this or are you ok with letting @walstonjd take this task? I see you've finished the _Double-Click_ (#481) PR. It doesn't look like you've started on this one yet 👌 

I'm happy either way (with either of you two doing this) 🤝 really grateful for all the help 😊

**Comment by sezalmittal987** [comment]
i really want to work on this issue but it is not working even in vlc media player.is there any player where it works?

**Comment by whyboris** [comment]
I only use [Media Player Classic: Black Edition](https://sourceforge.net/projects/mpcbe/) though when I was adding this feature I tried it out on VLC and POT players as well (perhaps VLC changed its API 🤷 )

**Comment by sezalmittal987** [comment]
Not getting anything, sorry. @walstonjd  can take this task

**Comment by orkomlosh** [comment]
Hey, if no one is taking this, i'll be glad to work on this.

**Comment by whyboris** [comment]
Thank you @orkomlosh for the successful fix 🙇 with #493 🎉
