### ISSUE TITLE
Single-click / Double-click option

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#471]
Some users requested a way to toggle single-click / double-click.

Specifically, when double-click is enabled you open a video by _double clicking_ whereas single clicking does either nothing, or will show you "similar videos" if the similar videos tab is open.

**Comment by sezalmittal987** [comment]
Can i work on this issue?

**Comment by whyboris** [comment]
@sezalmittal987 awesome, thank you!

Please let me know if you'd like a hand with anything.

Also, consider working off `video-hub-app-3` branch for an easier merge later -- as a lot of things have moved around. _not required_ 👌

**Comment by sezalmittal987** [comment]
As this the first time i am contributing to any project so i may need help.Thank you.

**Comment by sezalmittal987** [comment]
#481

**Comment by whyboris** [comment]
Thank you @sezalmittal987 for the excellent contribution 🎉 🙇 🤝 #481 

😁 it's awesome 💯
