### ISSUE TITLE
Proposal: Rethink how tags are stored in .vha2 files

### ISSUE THREAD

**Issue by TheTacoScott** [whyboris/Video-Hub-App#476]
While it's currently, likely, trivial to do in memory bootstrapping and scanning/searching of tags there are some limitations here and a refactor could provide some benefit.

Given that vha allows tags search with an AND/OR/NOT grouping operators it makes some sense perhaps store these in a local db type thing (sqlite or a variant). Excluding that, it may be wise to store these as more of an inverted index.
`{
   "<tag>": {
    "<hash_that_has_tag>":{<other metadata}
  }
}`

That would be useful for the tag AND/OR use case, and then a DocValues style mapping might be usesful for the NOT case and a future use case of a "clip has NO tags aka ZERO tags" search use case

Worth exploring as this would help raise the ceiling of max tags/clips/etc.

**Comment by whyboris** [comment]
Thank you for the proposal!

I've not used tags at all except while developing (because enough people requested the feature). I suspect the search is fast (less than a second) even with 10,000 videos each with 10 tags. 🤷 

I don't yet see a motivation to do a major refactor unless there's an observed (or definitely-going-to-happen-soon) problem. 🤔

**Comment by TheTacoScott** [comment]
It's more about raising the ceiling of what is possible, and offloading certain problem buckets to tools/libraries that can best handle those problem buckets. Ultimately, the goal here is reduce the amount of  code the project needs to maintain while boosting what the project can offer.

If you want tags to be a supported feature the project is on the hook for a good amount of code that another library/project has already tackled with more features/testing/etc on that feature set.

Having vha2 files be json is hugely useful (we're in violent agreement there) for debugging/corrections and it even allows for outside programs to modify values if need be. But JSON is an abstract data bag that doesn't provide enough runtime benefit(s) compare to alternatives specific to your use cases and access patterns. 

Sqlite or a variant would provide both a place to store configurations/metadata AND provide runtime benefits for the searching use cases.

Think of the use case of 100k videos each with 500 tags. The combinatoric problem in memory makes this troubling, but in a db it makes it trivial.

However, this proposal could easily fall into the scope creep bucket and not be worth pursuing any farther, but I bring it up non-the-less.
=)

**Comment by whyboris** [comment]
Thank you for your thoughts!

I'm uneasy about using other libraries when a bit of personal code will do. For example, I looked into [ngx-chips](https://github.com/Gbuomprisco/ngx-chips) for implementing tags; if I used the library, I would have likely had to fight the library to get the behavior I wanted.

Instead, manual tagging ended up being just a small file with some basic interactions. As far as I can tell bug-free and transparent about what it does.

I can't imagine a typical user would have more than 10 tags per video. Even if a user has many tags, I don't see why the system I have would slow down much -- it's just comparing substrings in arrays 🤷 

At the moment, the tag feature is basically complete -- I can't think of anything missing 🤔 and anything like "remove tag across all videos" could be implemented with a few lines of code if needed 🤷 

I agree that a database is _designed_ for searching (while my implementation requires an equivalent of a `.forEach` through a large array). 

I think that as long as my app can handle 10,000 without trouble, it covers 99% of the users. 

*You gave me an idea:* I'll populate my .vha2 file with fake data (re-using hashes for convenience) and see how it behaves at 100,000 files 🤞

**Comment by TheTacoScott** [comment]
_I think that as long as my app can handle 10,000 without trouble, it covers 99% of the users._ == totally true.

Most of these proposals I'm pushing are about raising the scope for the 1%, or weirder, use cases. Which, let's be honest. we all have limited time and resources and attention: it makes perfect sense to not prioritize these.

Basically: I'm sick of maintaining my own postgres/angular1 version of what is essentially just a much worse version of your app here, so I'm trying to find hooks into it to close the gap where I can.
