### ISSUE TITLE
Automatically use an image of the same name as the video as a thumbnail

### ISSUE THREAD

**Issue by 68cdrBxM8YdoJ** [whyboris/Video-Hub-App#506]
I see that I can manually specify the thumbnail image, but can I do it automatically?

```
.
├── sample.mp4
└── sample.jpg     # Use this image as a thumbnail
```

**Comment by whyboris** [comment]
Interesting idea.  I wonder how common it is for people to have such a setup. My guess it's very uncommon 🤔 🤷‍♂️ ... perhaps some people have `cover.jpg` file name instead 💭 I'm really unsure.

If you'd like I can help you code the changes so you could build your own version of the app 🤝 

I'm unsure whether I'd want the feature to be a part of the app - I'm sort-of on the border. Would love to hear others' opinions 👍

**Comment by LordJon** [comment]
Interesting idea but I agree that multiple people probably use different kinds of formats (yay multiple standards).
The format I'm using is a folder with the movie file in it, an information file (NFO), a trailer, a poster (like a DVD case front) and a background image (fanart). There's also 2 subfolders for thumbnails and backgrounds (fanart).
It looks a bit like this:

extrafanart
├── fanart0.jpg
└── fanart1.jpg
extrathumbs
├── thumb0.jpg
└── thumb1.jpg
.
├── sample.mp4
├── sample.nfo
├── sample-fanart.jpg
├── sample-poster.jpg
└── movie-trailer.mp4

And in the case of TV series there also a theme music file in the same location as the main folder named theme.mp3. But that's outside the scope of this project I think. Besides my TV series folders has a different format with season subfolders. Let's not get in to that (unless you want to).

**Comment by 68cdrBxM8YdoJ** [comment]
Thanks for the reply.
It certainly doesn't seem to be an easy solution, as different people manage their cover images differently.
I'll make a fork that is suitable for me :smirk:.

**Comment by whyboris** [comment]
Do let me know if you'd like me to point you to locations in code where to add your changes / if you have any questions 👍 

ps - the current `main` branch already has the changes from `3.0.0` but it might have minor bugs still. The branch is stable-enough that it shouldn't change much before release, but whatever you build would likely benefit from a `git merge main` update once `3.0.0` comes out 😊

**Comment by whyboris** [comment]
Thank you for the suggestion and the discussion.

I think this is too bespoke and is best handled by individual developers on their end. There's already functionality in the app that can take an arbitrary `.jpg` or `.png` and set it as the main thumbnail for a video. It wouldn't be too hard to add a few lines of code that check for presence of a particular image format and use that functionality.

Closing the issue since I don't think this will appear in the production app. Please feel free to comment on it if you'd like any help with getting the code to work for yourself 🤝

**Comment by Gavriik** [comment]
I'm interested in this functionality can you please point to me the location where to add the changes and what preexisting functions I can use? thanks

**Comment by whyboris** [comment]
Hey @Gavriik -- looks like @68cdrBxM8YdoJ has already done enough to get the feature working on their end. 
You won't need all the code in their branch, but the relevant piece is here:

https://github.com/whyboris/Video-Hub-App/compare/main...68cdrBxM8YdoJ:Video-Hub-App:automatically-use-exist-image-as-thumb#diff-35434f481038fd7aac0dd8caf5dab1a131c5a601cfda35dcf4f98b07111ba0ecR282

Their branch is out of date with my `main` but you can copy/paste the line I link to above and the few below - and with some minor modifications that might work for you. Let me know if you have trouble, I can help out 🤝

**Comment by Gavriik** [comment]
great, thanks!
