### ISSUE TITLE
Drag video out of VHA into Premiere

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#519]
It seems like an interesting puzzle 🤔 - it's not as simple as dragging out a _string_ pointing to the file location 😅 

The closest I got in my Google searches is: https://github.com/electron/electron/issues/2923 but the link there is a `404` and no other leads 😢 

There's a discussion which makes me think this might be impossible 😓 https://github.com/electron/electron/issues/11691

Opening the issue in case anyone has had any experience / has leads on it.

Please _do not spend time on this_ -- only if you already know the answer 👍

**Comment by cal2195** [comment]
Time machine magic! https://web.archive.org/web/20190323025729/https://www.thecssninja.com/javascript/gmail-dragout

But this suggests it works both ways, just using the drag API: https://www.electronjs.org/docs/tutorial/native-file-drag-drop

🤔 💭

**Comment by cal2195** [comment]
https://www.electronjs.org/docs/api/web-contents#contentsstartdragitem

**Comment by whyboris** [comment]
😂 😭 😍  Thank you @cal2195 🙇 

Thanks to pointing me in the right direction -- your last two links were exactly what I needed 😁 

Ref: https://www.electronjs.org/docs/tutorial/native-file-drag-drop#native-file-drag--drop
Ref: https://github.com/electron/electron/pull/6333#issue-76082139 🎉 

PR coming shortly 😎

**Comment by whyboris** [comment]
Got it to work - only a few lines of code for functionality, and some app-related code to finish it off 😎 #532
