### ISSUE TITLE
Manual thumbnail extraction is not async

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#528]
When using the manual thumbnail extraction button, the verifying thumbnails part is synchronous, leading to a massive delay while the app is unresponsive! 😓 

We should do this with async methods, like the normal rescan version! 👍

**Comment by whyboris** [comment]
Hey @cal2195 could you clarify a bit. What is the "manual thumbnail extraction button"? The `Rescan` right next to the folder?

![image](https://user-images.githubusercontent.com/17264277/94326334-47403900-ff71-11ea-8f10-15fa93c904fc.png)

Or is it the `Add missing thumbnails` here?

![image](https://user-images.githubusercontent.com/17264277/94326360-66d76180-ff71-11ea-8727-b13489ee0853.png)

Or perhaps if it's nearby in your mind, could you point me to the code you have in mind?

I finally finished working on other stuff and am eager to get version `3.0.0` released 😅 🙇

**Comment by cal2195** [comment]
I believe it's the `Add missing thumbnails` button I was referring to, which calls this method:
https://github.com/whyboris/Video-Hub-App/blob/adde781171bda66b8bbc6decc8a05c14f0d7ee82/node/main-extract-async.ts#L321
Ideally, anything using the *Sync fs methods should be changed to be async! 😄

**Comment by whyboris** [comment]
Thanks! I'll investigate and update 🤝
