### ISSUE TITLE
Scan doesn't find all videos (regression)

### ISSUE THREAD

**Issue by lighthunt** [whyboris/Video-Hub-App#531]
Videos in some folders are not indexed (either initial scan when creating the hub or later when watching folder or not watching-no matter how many times I hit the rescan on the folder). (Only one root in the hub).

App v2 however does index it just fine. - So I have this (for example) produced in the vha2 file from v2 (if it helps to report), but missing in vha2 file produced by v3 (main branch):
```JSON
{
  "cleanName":"17420736D7A11F2D28488FDC794CD111",
  "duration":12,
  "fileName":"17420736D7A11F2D28488FDC794CD111.MP4",
  "fileSize":90681876,
  "hash":"60012be57952ddd2f018af491e1609cc",
  "height":2160,
  "mtime":1592796692000,
  "partialPath":"/_by others/2020-06-19 Con Dao SUP trip",
  "screens":10,
  "stars":0.5,
  "timesPlayed":0,
  "width":3840
},
```
It's not the underscore '_' in the folder name (this has been resolved long time) and some folders under "_others" were actually indexed in v3, not sure where is the problem. I am puzzled.

**Comment by whyboris** [comment]
Thank you @lighthunt for the report -- I see the problem is the `.MP4` -- same issue as in #551 

Turns out I was not comparing `.toLowerCase()` :trollface:  😅
