### ISSUE TITLE
Recently played list

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#547]
There is a bottom tray that can show _tags_ and _similar videos_.

I want to make the _word cloud_ also appear in a similar tray.

I will add tabs above the tray that will make it easy to switch between the three possible pieces of content.

*Finally*: make a "recently played" tray that will show just like _similar videos_ but just a queue of recently-played videos!

edit: _forgot to mention - this was a request from a customer via email_ 🙇

**Comment by idk** [comment]
Suggested this elsewhere so just jumping in on this thread. 👍

**Comment by whyboris** [comment]
Thank you @idk -- this was a great feature 😁 

note: the "recently played" will only persist per hub, per session. So switching hubs or closing the app resets the "recently played" to empty 👌
