### ISSUE TITLE
Peculiar issue with detecting/parsing certain files to add in a Hub

### ISSUE THREAD

**Issue by AlishaPink** [whyboris/Video-Hub-App#551]
I'm not sure if it's only my systems or a global issue (although I did test multiple systems and various files) but if the extension of any video file is capitalized, then Video Hub failed to parse/detect the file to add, for example "00.mp4" will work, but "00.MP4" will not be added to the Hub.

Also a suggestion along those lines, when adding alot of files, it gets really tedious to weed out the ones which have not been added due to improper parsing or a badly encoded file so it would be great if a report was generated which says which files were not able to be added. Could be done by a simple crosscheck between added files and a walkdir enumerating all files at the source.

**Comment by whyboris** [comment]
Great catch! Thank you!!!

The supported filenames `acceptableFiles` https://github.com/whyboris/Video-Hub-App/blob/main/node/main-filenames.ts 
used to be compared extensions `.toLowerCase` https://github.com/whyboris/Video-Hub-App/blob/main/node/archive.ts#L157
But is no longer: https://github.com/whyboris/Video-Hub-App/blob/main/node/main-extract-async.ts#L185

This is likely a 1-line fix 😁 
Please let me know if you'd like to open a PR for a fix or let someone else handle it 🤝

**Comment by whyboris** [comment]
🤷‍♂️ it was a 1-line fix so I just did it 😎 #554 with https://github.com/whyboris/Video-Hub-App/pull/554/commits/cf3db5d892ac0a5616685a70aa26cdcfd07e0010
