### ISSUE TITLE
Multiple thumbs of single video

### ISSUE THREAD

**Issue by lighthunt** [whyboris/Video-Hub-App#557]
For some of the videos, catalogs shows the thumbnail twice (and I have seen even 3 copies). No idea what cases this. I have seen it multiplied after scan or renaming the file. I will try to reproduce it on some smaller set ...
FYI I have tried to "Delete old thumbnails" function to no luck.
Anyone experienced this? 

This is an exception I got several times, not sure if it's related or different issue

![2020-10-14 15_09_11-Video Hub App 3](https://user-images.githubusercontent.com/14195401/95969140-8d820d00-0e38-11eb-9207-f3d7b692244a.png)

**Comment by whyboris** [comment]
I've not spent any time with the `watch folder` functionality -- other than enable it with a button and hoped that it works 🤞 

There will likely be bugs when you enable "watch folder". Is this a setting you have on?

**Comment by lighthunt** [comment]
Nope, watching all folders is off. I always scan manually (so at least I can predict or prevent some troubles, I don't trust the app at this state of the art, maybe later, LOL ;-) )

**Comment by whyboris** [comment]
Related: #552

**Comment by whyboris** [comment]
ps - "delete old thumbnails" functionality is meant to delete the `.jpg` files on the hard drive for videos no longer in the hub.

I'll try to replicate the problem -- if I can, I should be able to fix it too 🤞

**Comment by whyboris** [comment]
Closing so as to not have a duplicate issue. Discussion continues here: #552

**Comment by whyboris** [comment]
Closed with #573 -- please create a new issue if this issue persists 🤝
