### ISSUE TITLE
Installer installs unnecessary (other platform files)

### ISSUE THREAD

**Issue by lighthunt** [whyboris/Video-Hub-App#558]
regression (#513 ), same thing again, unnecessary files in installation
@ffmpeg-installer
@ffprobe-installer

Note  I run "npm clean-install" before the build

**Comment by whyboris** [comment]
I've changed nothing -- it might be something that happens on your end (unsure why).

When I try, my installer for _Windows_ is around `66mb` and for _Mac_ it's around `107mb` 🤷‍♂️ 

Are they differently sized when you create your `.exe` or `.dmg` installer?

**Comment by lighthunt** [comment]
Possibly. Could be on my side, unsure why boris. I've cleaned all (I hope), clean checkout of main. If your build is ok, please ignore me.

Video Hub App 3 Setup 3.0.0.exe is 220MB

in this path, there are all platform files, not win32-x64 only as I would expect 
... \release\win-unpacked\resources\app.asar.unpacked\node_modules\@ffmpeg-installer\darwin-x64\
... \release\win-unpacked\resources\app.asar.unpacked\node_modules\@ffprobe-installer\ ...

build output:

Robert@lighthunt-xps MINGW64 ~/Work/Video-Hub-App (main)
$ npm run electron

> video-hub-app-3@3.0.0 electron C:\Users\Robert\Work\Video-Hub-App
> npm run build:prod && electron-builder build && npm run buildsize


> video-hub-app-3@3.0.0 build:prod C:\Users\Robert\Work\Video-Hub-App
> npm run build -- -c production


> video-hub-app-3@3.0.0 build C:\Users\Robert\Work\Video-Hub-App
> npm run electron:serve-tsc && ng build --base-href ./ "-c" "production"


> video-hub-app-3@3.0.0 electron:serve-tsc C:\Users\Robert\Work\Video-Hub-App
> tsc -p tsconfig-serve.json

    WARNING: Zone.js does not support native async/await in ES2017.
    These blocks are not intercepted by zone.js and will not triggering change detection.
    See: https://github.com/angular/zone.js/pull/1140 for more information.
WARNING: Using differential loading with targets ES5 and ES2016 or higher may
cause problems. Browsers with support for ES2015 will load the ES2016+ scripts
referenced with script[type="module"] but they may not support ES2016+ syntax.
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2020.409e6590615fb48d139f.js (runtime) 1.45 kB [entry] [rendered]
chunk {0} runtime-es5.409e6590615fb48d139f.js (runtime) 1.45 kB [entry] [rendered]
chunk {2} polyfills-es2020.a0f23dec1ae343454a15.js (polyfills) 36.1 kB [initial] [rendered]
chunk {3} polyfills-es5.532dbc91238b27d811ad.js (polyfills-es5) 129 kB [initial] [rendered]
chunk {1} main-es2020.a6d13b7ba05672ad4c4a.js (main) 1.6 MB [initial] [rendered]
chunk {1} main-es5.a6d13b7ba05672ad4c4a.js (main) 1.72 MB [initial] [rendered]
chunk {4} styles.a6e0c8e0f5426dfdffc4.css (styles) 1.45 kB [initial] [rendered]
Date: 2020-10-14T15:52:00.092Z - Hash: 9b6bb75839dee513ff03 - Time: 99384ms

WARNING in C:\Users\Robert\Work\Video-Hub-App\src\app\components\views\file-path.service.ts depends on path. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\Robert\Work\Video-Hub-App\node_modules\path\path.js depends on util. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\Robert\Work\Video-Hub-App\node_modules\ngx-virtual-scroller\__ivy_ngcc__\fesm2015\ngx-virtual-scroller.js depends on @tweenjs/tween.js. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
  ΓÇó electron-builder  version=22.7.0 os=10.0.18363
  ΓÇó loaded configuration  file=C:\Users\Robert\Work\Video-Hub-App\electron-builder.json
  ΓÇó packaging       platform=win32 arch=x64 electron=8.3.0 appOutDir=release\win-unpacked
  ΓÇó downloading     url=https://github.com/electron/electron/releases/download/v8.3.0/electron-v8.3.0-win32-x64.zip size=71 MB parts=8
  ΓÇó downloaded      url=https://github.com/electron/electron/releases/download/v8.3.0/electron-v8.3.0-win32-x64.zip duration=2m22.908s
  ΓÇó downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  ΓÇó downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=21.426s
  ΓÇó building        target=nsis file=release\Video Hub App 3 Setup 3.0.0.exe archs=x64 oneClick=false perMachine=true
  ΓÇó downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z size=1.3 MB parts=1
  ΓÇó downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z duration=7.956s
  ΓÇó downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z size=731 kB parts=1
  ΓÇó downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z duration=6.754s
  ΓÇó building block map  blockMapFile=release\Video Hub App 3 Setup 3.0.0.exe.blockmap

> video-hub-app-3@3.0.0 buildsize C:\Users\Robert\Work\Video-Hub-App
> sh ./bin/buildSizeCheck.sh


    WARNING: build may be larger than desired

**Comment by whyboris** [comment]
I think, one option is to manually delete the irrelevant files from the `node_modules/@ffmpeg-installer` before creating the `exe` 🤔

**Comment by lighthunt** [comment]
If the problem is on my side only, than I see no issues, I can always delete it from installation etc. But it's good to verify the actual release for the crowd. build size warning worked after-all ;-)
