### ISSUE TITLE
Fundamental flaws, including multiple license violations

### ISSUE THREAD

**Issue by episk** [whyboris/Video-Hub-App#565]
I initially came here to talk about the UI, and perhaps how I could offer my services to better it. I'll only give you the short version now that it's not really relevant in light of other issues: It's a great app concept – but very likely the worst UI of any software I've owned since release of Win10.

As reply to some of the considerations made on the topic of UI here, I mainly got to say that there's no point making it look "clean" if you ignore most of the core fundamentals of what makes a good user experience and you need to address them). I'm being a bit harsh here, but mainly as a way to underline how severely this software fails in being legitimate. You really think of integrating face recognition at this point? What this app need is fundamental UX testing, and even just fixing bugs.

But first and foremost, VHA is heavily dependent on FFmpeg but fails to fulfill the terms of which it can be used on several points, In fact, the license isn't even included in any of the copies I received. What yo do find is simply the license version, and that also reveals that the version is shipped with isn't even compiled for VHA, it's simply a default Windows binary installer. FFmpeg isn't mentioned in either software or on the website. This is the closest to any information about its use:

```
{
  "author": {
    "name": "Kristoffer Lundén",
    "email": "kristoffer.lunden@gmail.com"
  },
  "cpu": [
    "x64"
  ],
  "description": "Windows FFmpeg binary used by ffmpeg-installer",
  "ffmpeg": "20181217-f22fcd4",
  "homepage": "https://ffmpeg.zeranoe.com/builds/win64/static/",
  "license": "GPLv3",
  "name": "@ffmpeg-installer/win32-x64",
  "os": [
    "win32"
  ],
  "version": "4.1.0"
}
```

And would you look at that. It's even the v.3 you're in violation of now because of the extra libraries upgrading it from FFmpeg's standard LGPLv2.1. Things aren't even in order here on Github – I can't even find the _actually complete source code for V2_ since it's overwritten by an incomplete version 3 (still described as v2 in the description). I'm not a programmer, but trying to find how you approach the use of FFmpeg in this version, just gave the impression of an attempt at obfuscating its use. Regardless, it doesn't matter since none of this is made available to the user.

It's a train-wreck. Sorry, but what else can I say?

Now despite the slightly pissed off tone in this post, I actually did spend the time writing all this with intention to help. I do hope you can see it that way.

**Comment by whyboris** [comment]
Thank you @episk for sharing this. I'm sorry I'm not familiar with license stuff. I am unsure what is expected out of software that includes _FFMpeg_. If you have a suggestion of how I can properly handle this issue, I will be very grateful.

I'm sorry to hear you dislike the UI. I'm open to hearing which aspects of it need improvement or redesign (I will be especially grateful if you describe the specific ways which would be better).

The biggest issue I think is the license, but anything more you can add would be great 🙇

**Comment by episk** [comment]
Not being familiar with licensing is simply not an excuse. It's a matter of effort and respect towards the developers of FFmpeg. I'm pretty sure you've read the documentation on how to use their software, so why skip the parts covering what they ask of you?

It's not about folding to some restrictive bs law policy or pay a million bucks either – it's just you undermining the work of those who work for you, You obviously solve the issue by working towards compliance. You don't have to ask me, just do it. 

If you didn't know, these are the licenses that are actually good and the kind you probably would want to comply with, as they benefit everyone.

Regarding the **General Public** License terms and where to get info on that, well, I think you'll figure it out.

**Comment by whyboris** [comment]
I'll do better research. Thank you for the recommendation.

**Comment by AlishaPink** [comment]
@episk You make claims about being here to _"talk about the UI, and perhaps how I could offer my services to better it"_ but other than simply dismissing and insulting the UI, you don't even mentioned any single specifics about _what_ is actually wrong with the UI/UX or what you can do to help, despite the owner asking you to share any problems you might have.

Rather you go on to ramble about FFmpeg licensing and policing a matter which isn't even enforceable, nor required, but rather just good practice in the world of Open Source Software, which you could have conveyed politely and constructively.

That does not make it a train-wreck, according to your delusions.

Also, if you are so concerned about one singular project not religiously following the documentation of an FOSS project such as FFmpeg, you should've seen how numerous much larger software use it without even a mention to it. I can provide a few examples if you're not capable of finding them yourself, as seems more evident.

Have some respect for the Owner of this Repository as well, since he's been nothing but polite and constructive despite your rude criticism, you just being a pointless keyboard warrior venting needless conclusions are not helpful at the least.

@whyboris I'm so sorry for this long post, I'm just intolerant towards such behavior towards a project which is loved by many with hours and hours of development.... (though I've not gotten around my PR yet😅 )

**Comment by cal2195** [comment]
I would have to agree with @AlishaPink here - while it's all well and good trying to improve VHA from a UX and licensing point of view, at least have the decency to do with with respect and give constructive advice, not just insulting comments.

Thanks to @whyboris, this is an open source project with the combined effort of Boris and many contributors giving there own free time to help make the project thrive. I don't believe such a tone is warranted here, especially with the majority of the suggested cost for the packaged versions going to charity.

@whyboris has done nothing but try to engage with you in a constructive way, so please try to do the same in return.

I, and many others I expect, are completely open to having a constructive discussion on how to improve VHA from any standpoint, but we require respectful and productive discourse.

This community is a positive one, and it should stay that way. ❤️

**Comment by episk** [comment]
I apologize for the tone, I would write it differently reading it back now. It's really just disappointment reflecting off a bit much. Part of it being annoyance as I didn't see the response as constructive as I was hoping it to be. I just couldn't see why I'm asked to elaborate on how to solve these issues when it's so obvious. Second reason is that I actually had completely different plans coming here. I prepared some mockups for how to reorganize things in the UI including documentation supporting it. 

I've had this project in the back of my head since first release, doing some work on it now and then, for practice and for fun, not necessarily to ever reach out. But then I decided I had some pretty solid work that I liked, and then decided to give it a shot.

Sadly the hours I spent looking closer at the details of the project made me realize that this wasn't for me. Please trust me when I say that I'm certainly just not "venting needless conclusions". Just because it's unlikely that the issues I'm pointing out will have legal repercussions doesn't make then dismissable. And really, this is not a case of "not religiously following the documentation", these are clear license and trademark violations. I really don't mind about each individual project, but how it damages the free software philosophy. (And regarding open source: https://www.gnu.org/philosophy/open-source-misses-the-point.html)

I guess it's fine if you don't agree with me, but how could you possibly just suppress all the points I'm making into something coming from a "delusional keyboard warrior"? If I really haven't communicating anything useful, you just don't understand me.

@whyboris Boris, I'm sorry for way I approached this matter. I suppose I felt invested a bit earlier than I should've. I hope you'll see the benefits of honoring these licenses and wish you good luck with v.3.

**Comment by whyboris** [comment]
@episk -- thank you for urging me to comply with the FFmpeg [checklist](https://ffmpeg.org/legal.html). I specifically see (9) and (10) applying to me (mentioning and linking to FFmpeg from my download page and from within the app).

Perhaps if you have enough patience for this, you could advise:

I do not have a EULA. Do have to require that before installing the software, those who wish to install it must read through and accept a EULA (mentioning FFmpeg)?

As far as I can tell, nothing else on that list applies to me (mostly since I do not touch _FFmpeg_ code or compile it). Is this an incorrect assessment?

**Comment by whyboris** [comment]
@episk -- while it's not your responsibility at all -- the more specific your advice about complying with the legal stuff, the more likely I'll implement it -- I'll really appreciate if you let me know specific things I can do.

I have updated my website code (will be public in a few weeks when I upload the latest code again) with _FFmpeg_ credit:
https://github.com/whyboris/video-hub-app-gatsby-website/commit/70fc9ae7e070fd5a4249d47c3418428ec1d870b3

I have added a note directly in the app that _FFmpeg_ is getting used:
https://github.com/whyboris/Video-Hub-App/pull/564/commits/79377049a3b22ad987dc3d14153d125248864892

I have added a note directly in the `README` of this project:
https://github.com/whyboris/Video-Hub-App/pull/564/commits/a9f0bae0fd46be3455ab09384c222644353a0f05

This is a great easier-to-comprehend summary of [LGPL 2.1](https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)) 😁

**Comment by whyboris** [comment]
@episk -- you said you "had some pretty solid work that I liked" while working on a UI redesign (or was it something else?). Whatever work you have, or suggestions for UI improvements, I'll really appreciate if you share. 🙂  Even if it's unfinished, or just a sketch on paper -- all ideas are welcome for a discussion. It would be a shame for the work you've done to be lost 🙁

**Comment by whyboris** [comment]
@episk -- I hope you come back to comment. I'm closing the issue, but please add your comments below when you have time.
