### ISSUE TITLE
Monitoring not picking up renamed file

### ISSUE THREAD

**Issue by CrendKing** [whyboris/Video-Hub-App#575]
Continue from https://github.com/whyboris/Video-Hub-App/issues/552 with new ticket as you instructed.

With the new change, if I rename `A.mp4` to a different name like `B.mp4`, monitoring can instantly pick up the change, which is good. If I change it to `C.mp4`, also picked up.

However, if I rename `C.mp4` back to any of the previous `A.mp4` or `B.mp4`, the index is gone and won't come back (even if I manually rescan) until I restart the application.

Also confirmed it is not just a GUI glitch. The filename is missing from the .vha2 too.

**Comment by whyboris** [comment]
😅  -- most likely because I hacked my way to get the thing to work 😝 
I strongly suspect if you exit the hub and re-open it, it will again work 🤞 please let me know 🙇

**Comment by CrendKing** [comment]
This is way less a problem than #552 because user renaming a file back is way less often than user renaming a file, period. So take your time.

**Comment by whyboris** [comment]
The duplicate entries _should_ now disappear whenever you exit out of the hub (as long as you've played at least one video or edited any of the metadata).

If you happen to have an old hub with duplicates, could you try it out and let me know if the duplicates disappear after close-and-reopen? 😅

**Comment by CrendKing** [comment]
It does, but just inconvenient.

**Comment by whyboris** [comment]
Thank you for the check. I'll see how convenient I can make it.
If it doesn't require re-writing a lot of code, I will try to make things better before release 👍 
At the moment it's a balance between releasing something "good enough" and delaying for a while still ⚖️

**Comment by whyboris** [comment]
Fixed with https://github.com/whyboris/Video-Hub-App/commit/ce2a7c691c90c97de07a5039da4cff290f1988ce 😎
