### ISSUE TITLE
v3: Page up and down keys stop working after a few presses

### ISSUE THREAD

**Issue by CrendKing** [whyboris/Video-Hub-App#579]
If I use mouse wheel to scroll up and down, it always works. However, if I use page up and down, it works for the first few presses, then stop working. I need to click an empty space to gain focus then it works for one or few presses, then stop again. Console does not show any error when it happens.

**Comment by whyboris** [comment]
Unfortunately it's not something I can fix without finding a solution for the library I am using:

https://github.com/rintoj/ngx-virtual-scroller/issues/425

**Comment by CrendKing** [comment]
@whyboris https://github.com/rintoj/ngx-virtual-scroller/pull/489
