### ISSUE TITLE
v3: Delete video menu item sometimes does not work

### ISSUE THREAD

**Issue by CrendKing** [whyboris/Video-Hub-App#581]
This is a weird behavior. If I launch the app, choose a video, right click then delete it, for the first time it always works. However, if I proceed to delete a second file, nothing happens. I have to repeat the same clicks again to make it work. Basically odd number actions work, even ones don't.

I thought there might be some error in console. However, if I enable dev mode, the delete always work, and no error.

**Comment by whyboris** [comment]
I'll see if I can replicate and then figure out what is causing the problem.

Scary that the _dev_ mode does not faithfully reproduce the behavior of the built app 😱 

So far I've always been testing in _dev_ -- so I'll see if I can fix this before `3.0.0` release 😅

**Comment by whyboris** [comment]
Thank you @CrendKing for the bug report! I think I fixed it correctly with #588 🎉 
Please comment if the error reappears 🤝
