### ISSUE TITLE
[Feature Request] Ability to ignore folders

### ISSUE THREAD

**Issue by adamwinn** [whyboris/Video-Hub-App#599]
I have a large number of folders and subfolders that I'd like to exclude from vha so they dont waste resources scanning them.  It would be nice to be able to exclude folders entirely or even exclude folders that are greater than a certain size.

**Comment by whyboris** [comment]
This has been requested previously - I'm sure this is a nice feature to have.

One current option is to simply add the folders you want directly, though it's not as convenient if you just want to exclude one or two out of many.

For the folder exclusion to prevent scanning, you'd have to exclude a folder first before adding the folder to scan, which feels like a weird flow. I guess I expect people to have an organized video folder that they view with Video Hub App - I didn't expect people to point the app at a full hard drive and try to find videos across it (though I guess that works too). 

If I do include this feature, it would be a while from now. Thank you for requesting a feature -- I keep all requests in mind as I work on the app.

If there's anyone who thinks the UI (user interface) and the workflow for how to exclude folders would be less complicated than I imagine (than I described), let me know in the comments - perhaps there _is_ an elegant solution to this problem.

I don't think excluding a folder "greater than a certain size" is going to be a feature I'll want to add - could you elaborate why you'd like this feature? Perhaps there's a better way to solve the problem you are having.

**Comment by adamwinn** [comment]
"greater than a certain size" would just be to cut down on scanning time and resources

**Comment by whyboris** [comment]
In order for "greater than certain size" to work, the app would need to not only scan the folder in its entirety, but also to then calculate its size (which is even more resource-intensive). 

The best approach is to point Video Hub App at a folder with your videos, not a full hard drive.

The current implemented code (and any algorithm that would work) has to look at every single file in the folder you give it. At the moment, if the file extension does not match any on the list of supported file types, the file is ignored. Only if the file type is supported does the file path get added to the list of "try extract metadata from these files". 👍

**Comment by whyboris** [comment]
Closing in favor of #450 (duplicate)
