### ISSUE TITLE
Error when dragging videos outside of app / Compact view shortcut key? / Add support for MPV player for time of clicked screenshot

### ISSUE THREAD

**Issue by fire838** [whyboris/Video-Hub-App#607]
1. Getting "A Javascript error occured" when holding onto mouse button to drag: https://i.imgur.com/aWlO1St.png
2. Add a button to toggle compact view
3. Add support for MPV player please

**Comment by whyboris** [comment]
Thank you for opening the issue! 🙂 

1. Could you explain the scenario better? What are you dragging? 
    - you are expected to be able to drag a `tag` from the tag tray onto a video
    - you are expected to be able, _if you enable the feature in settings_, to drag a video out of the app somewhere in your computer (like a video editor or a folder to create a copy of the video there).
2. There is a button to toggle compact view, please go to settings, click on 2nd tab ("View settings") and scroll to "Layout" section, 1st button "Compact view". Click on the eye icon to show/hide it from the ribbon of button at the top of the app
3. Every player should be supported. But opening from a specific time in the video is only officially supported on MPC, VLC, and POT.

**Comment by fire838** [comment]
1. I hold down mouse button and move the cursor to drag a video I get the JavaScript error. Here is a video: https://streamable.com/uncgqa

**Comment by whyboris** [comment]
Thank you for the video! It makes it very clear what is going on. I'll try to reproduce the error on my machine ✅

**Comment by whyboris** [comment]
Thank you @fire838 for bringing the dragging-out bug to my attention -- I fixed it with #608 and it will be part of the version `3.1.0` release (coming before 2020 is over).

I'm considering closing this issue as I think the biggest problem is solved.

I'm stunned and disgusted by `MPV` -- how many hoops do they want their users to jump through to install a video player?
:trollface:  https://mpv.io/installation/ ... are they serious? I'm really turned off from trying to install this video player.

As of now, I'm 99% sure you are able to use the player from VHA, you're just missing out on the "open from thumbnail clicked" right?

**Comment by fire838** [comment]
> As of now, I'm 99% sure you are able to use the player from VHA, you're just missing out on the "open from thumbnail clicked" right?

Yes

**Comment by whyboris** [comment]
OK -- it's late and I'm being extra cranky. Sorry -- I installed _Chocolatey_ and the installation of `MPV` after that was not too bad. But installing Chocolatey felt really annoying. I just really wanted a simple installation like when you're installing `node` (or VHA 😉 ) - just download a _single_ file, double-click, and everything is done.

I have `MPV` installed now (annoyingly in a _hidden_ folder!? `C:\ProgramData\chocolatey\lib\mpv.install\tools` WTF!?) ... so I'll try adding "open from screenshot" support 🙆‍♂️

**Comment by whyboris** [comment]
I have to stop being so grouchy 😅  sorry about that ...

I added `MPV` support 🤝 with #609 

You'll see this feature as well in `3.1.0` 😁 -- or if you're comfortable with it, just follow the _Build_ instructions on the _README_ file and build the current `main` branch 👍 

Cheers!

**Comment by whyboris** [comment]
If I added the `compact` mode as a keyboard shortcut, which key would make sense for it you think?

`C` can't be used as default -- it would interfere with some people's habit of using `CTRL` + `C` to copy text :trollface:

**Comment by fire838** [comment]
Any key is fine

**Comment by whyboris** [comment]
I added it to default to `L` for anyone just installing VHA. For everyone else it's blank until they explicitly set it ✅ 

Done with: https://github.com/whyboris/Video-Hub-App/commit/1dd9c52e12d68ced0cdd63b66115e6bd53f50cef

Closing _Issue_ as all the three requested features have been added to the code base 😎
