### ISSUE TITLE
Implement Mac Touch Bar Support!

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#61]
Electron supports interacting with the MacBook touchbar!
https://electronjs.org/blog/touch-bar-support

This would be a very neat feature! We could have dynamic buttons for tags, changing views, zooming etc.
It seems very easy to implement! 👍

**Comment by whyboris** [comment]
Pretty cool!

I don't have a way to easily test this feature, I'd need to borrow someone's laptop at work for 5 minutes to see it in action. Anyone is welcome to contribute a PR; it just might take a few days for me to approve 👍

**Comment by cal2195** [comment]
No need for a Touch Bar! 👍 If you have any Mac, you can use this to test!
https://github.com/sindresorhus/touch-bar-simulator

🎉

**Comment by whyboris** [comment]
That's awesome! Didn't realize (never even thought to look!) that there was a simulator 😄 

I'll focus on more-pressing issues, but this could be fun to add.

I imagine as default it could have all the different views buttons and the zoom in / out buttons. 

What were you thinking of with "dynamic buttons for tags"?

**Comment by cal2195** [comment]
I'll look into this soon - will be fun to play around with! 🎈 

And those defaults sound good! I was thinking of having (hopefully) an expandable group, which will mimic the word cloud, but on the Touch Bar! 👍 By dynamic, I mean it updates as you search, just like the word cloud!

**Comment by whyboris** [comment]
Definitely feel free to experiment and see what feels useful 🎈

**Comment by cal2195** [comment]
Sweet! 👍 Fire away! (tags & sorting/filtering options would be awesome! 😄 )

**Comment by chris-bingham** [comment]
@peterszeles I have already started to look into it so would like to finish if possible

**Comment by peterszeles** [comment]
Ok no problem :) can you recommend me an first contributor issue at this project?

**Comment by chris-bingham** [comment]
I can't I'm afraid (I am a first time contributor too) maybe @cal2195 can help?

**Comment by whyboris** [comment]
Hey @peterszeles -- welcome 🙌 

You can use any IDE (code editor); InteliJ is great -- as you're starting out I recommend you try out at least a couple (Atom and Sublime Text are great too) so that you can see what is possible and what you like most. VS Code is my favorite for several years now and it integrates beautifully with _TypeScript_ and _Angular_ (though other editors are no doubt great at that as well). 

I created a [`.vscode` folder](https://github.com/whyboris/Video-Hub-App/tree/master/.vscode) in the repository so when you are using the editor you'll have some recommendations for _extensions_ and pre-set _settings_ that will make the coding experience even better 😄 

As for `good first issue` - you're welcome to think of some ideas too -- first just build the app locally and try using it a bit. See what you think would be an improvement and create an _Issue_ with your thoughts 👍 

Cheers 👋

**Comment by ErikDvorcak** [comment]
Hi, @whyboris  it's still actual? I can do that. I need little more info... which buttons you need on the touch bar? (Play/Pause, Next and Previous) ?  Or something else? I will be happy If I could help you with this.

**Comment by cal2195** [comment]
@chris-bingham Are you still working on this?

**Comment by whyboris** [comment]
@chris-bingham has a branch named `61-mac-touchbar-support` last updated 29 days ago with only a version bump of a dependency: https://github.com/whyboris/Video-Hub-App/compare/master...chris-bingham:61-mac-touchbar-support
I'm thinking he might be a bit busy and is no longer working on it (at least at this time).

@ErikDvorcak -- you're welcome to give this feature a try.

I don't have ideas for what buttons would be useful in the touchbar 🤷‍♂ 
At the moment there is no "play / pause / next / previous" functionality in the app for such buttons to correspond to.

There is a "Shortcuts" menu that might give you some ideas. Perhaps the touchbar would benefit from a button that sends the cursor to the search field (equivalent to `CTRL` + `F`) 🤷‍♂ 

If it's easy-enough, perhaps there's an easy way to re-use the icons in the touch bar - and show the same buttons the users have decided to see in the app?

I welcome suggestions and a discussion. And as I said, feel free to come up with whatever you think is useful. I can't think of anything I'd object to 👍

**Comment by ErikDvorcak** [comment]
Electron touch Bar doesn't support svg :(  I created  png from your svg.

**Comment by chris-bingham** [comment]
@cal2195 @whyboris @ErikDvorcak yes, sorry I really wanted to do this one but I'm super swamped at the moment and don't know when I'd get to it so please do crack on!

**Comment by whyboris** [comment]
Huge thank you to @ErikDvorcak for his work 🙇 
His amazing contribution (PR #299) closes this issue 👍 
We can make further improvements if someone desires -- please open a new issue for that 👍
