### ISSUE TITLE
Limited sort options

### ISSUE THREAD

**Issue by adamwinn** [whyboris/Video-Hub-App#613]
Right now you can basically only sort by size and duration.  It would be nice to be able to sort by filename, date added, date modified, etc.

![Screen Shot 2020-12-19 at 2 49 08 PM](https://user-images.githubusercontent.com/3028964/102700306-85b06180-4209-11eb-8909-d020421471ee.jpg)

**Comment by litelime** [comment]
Hi,

If you open the settings (cog in the top right), there is a tab called search settings, where you can find many other options for that drop down
![sorting](https://user-images.githubusercontent.com/38476932/102795986-cd023380-436a-11eb-93dd-0d39d0232641.png)

**Comment by whyboris** [comment]
Thank you @litelime for answering @adamwinn 's question 🤝 

I probably should add this to the [FAQ](https://videohubapp.com/en/faq) as this has been a question I receive sometimes over email.

**Comment by adamwinn** [comment]
Thanks!
