### ISSUE TITLE
Is there a way to make Tags and Rating be saved on the Metadata of the file instead that on the Library?

### ISSUE THREAD

**Issue by mlomeli** [whyboris/Video-Hub-App#614]
I figure that this way:

A) Files would work better with other library managers and even within this App it would prevent losing data when changing libraries. There's ton of devices like TVs that already support those applications.

B) Allows VH libraries to work alongside existing servers and bring this work to other devices.

I feel like the autotagging feature, the thumbnail creation, and possible features like Face Detection would allow this application to become a must to anyone owning a Video Library, even if they miss out on the Filmstrip and Thumbnails.

I realize that making a feature that makes this works better alongside other servers seems redundant when there's work on building a server but since the Apple TV doesn't have allow web-apps I figure I'd ask for my own personal use case.

**Comment by whyboris** [comment]
Thank you for creating this _Issue_ 🙂 

There is a relatively-easy way to do this on the _Mac_ -- I have code that lets you _import_ tags, but it's relatively easy to also _save_ the tags to the files using this approach: #370 -- though this code still hasn't made it into a publicly-released version of the app.

I have searched around but had no success with similar functionality for _Windows_ 😞 -- if anyone knows better please comment.

Thank you for the suggestion!
