### ISSUE TITLE
"tags include" shall be full word matching

### ISSUE THREAD

**Issue by mraway** [whyboris/Video-Hub-App#618]
When we "tag" something, we usually mean the tag is a non-separable entity.

Thus, one file with tag “abcdef” shall not appear in tag search of "abc" or "cde". 

When I import hundreds of files into VHA, this problem makes the tag searching unusable.

I suggest "tags include" shall enforce full word matching, if partial word matching shall stay as a feature, it could be a standalone option, or just include it in the fuzzy search.

**Comment by whyboris** [comment]
Thank you for the _Iussue_ 

The downside of implementing what you recommend is that some tags might be as long as a full actor's name (e.g. "Tom Cruise") in which case the user would have to type in the whole without any spelling mistakes. 

`Videos with each tag` (labeled at `Tag search` - 7th on the list of "Search filters" in the settings menu, "Search settings" - 1st tab) has auto-complete. When you start tying the tag and it shows the full tag name, you can press the `Tab` key on the keyboard to perform the search! 

Another way to achieve what you'd like is to simply open the _Tag tray_ (on the bottom) and click on the tag you have in mind.

Please let me know your thoughts 🙂
