### ISSUE TITLE
Preserve full folder name as a tag in word cloud?

### ISSUE THREAD

**Issue by mraway** [whyboris/Video-Hub-App#619]
Folder name usually suggests a common property of a collection, for example, a folder "Brad Pitt movies" indicates all videos in it are from one actor.

In VHA I noticed in each video, "Brad Pitt movies" is a tag for the video, but in the word cloud, the words are separated. 

Could VHA preserve the full folder name as tag in word cloud?

**Comment by whyboris** [comment]
The behavior of word cloud is as intended - each word is independent.

The word cloud now includes a combination of up to 3 different sources of words (folder names, file names, and tags). When you click on one of the words in the cloud, the view should update showing only videos with that word; the Word cloud updates as well - so you can click on another word in the cloud.

Visually, to make two-word combinations in word cloud, we'd need some border around them making the UI (user interface) very busy (similar to the Tag tray - requiring a smaller font too). Then, there would likely be users with folder names of more than two words - resulting in very long word cloud entries.

I'll think about your idea more, but at this time I'm leaning towards keeping the functionality as is.
