### ISSUE TITLE
Application start up is slow when managing hundreds of videos

### ISSUE THREAD

**Issue by mraway** [whyboris/Video-Hub-App#620]
After the videos being imported, the application start time takes 10+ seconds. I am afraid this will increase if I continue to import more. I suspect this is due to the construction of the main page which contains too many items.

In practice, having a single page to show all items is useless when the collection is large. Could VHA limit the amount of items to show in one page, and split the collection into multiple pages?

**Comment by whyboris** [comment]
Hello. Very weird - on my PC the app starts in under 3 seconds with a hub of 10,000+ videos. 

The app can handle thousands of videos - it uses a "virtual scroller" which doesn't render all the videos - only the ones that are shown in the gallery. So the app already limits the number of items show.

Here's an example of Video Hub App (version 1 from 3 years ago) scrolling through hundreds of videos with no problem: https://youtu.be/_KC9xrsiwZg?t=11

Are you using a portable version of the app from a USB stick? Unless your hard drive is very busy, I don't see why it would take a long time to start the app.

If you happen to have more than one hub, you could enable the "Show recent hubs" in the sidebar settings and click between the hubs to see if it takes a long time to load the hub, or just the app on start up.

**Comment by Daveesek** [comment]
Hi, just to confirm - I have over 20K videos and the app starts immediately and overall I am still amazed how fast and reactive this app is 🥇

**Comment by whyboris** [comment]
@mraway -- please comment if you think there is something else to discuss 👌
