### ISSUE TITLE
Bundled ffmpeg is ancient

### ISSUE THREAD

**Issue by Orthodox-531** [whyboris/Video-Hub-App#621]
The npm package `ffmpeg-installer/ffmpeg` went out of maintenance a while back, so the version of ffmpeg which is installed/built is from 2018.

In my case, I have encountered some OOM leak issues during thumbnail generation which I believe are resolved in later versions of the binary.

For an alternative which is still being updated, see `dnm-node-ffmpeg-installer`

**Comment by whyboris** [comment]
Thank you for the recommendation!
There is a PR for the dependency I'm using: https://github.com/kribblo/node-ffmpeg-installer/pull/48
But I will try out and maybe migrate to https://github.com/devdanim/dnm-node-ffmpeg-installer (as you recommend) - it's a fork (with newer code) of the package I use 🤝

**Comment by whyboris** [comment]
There's also: https://github.com/SavageCore/node-ffprobe-installer
https://www.npmjs.com/package/@ffprobe-installer/ffprobe

I'll check if this is better still 🤔

**Comment by whyboris** [comment]
This might be a good option with up-to-date (20 days ago!) release: https://github.com/eugeneware/ffmpeg-static

**Comment by whyboris** [comment]
We have a winner 🎉 https://github.com/eugeneware/ffmpeg-static 🎉 
- easy to swap into my setup
- works well
- up-to-date version 🚀 

Let's release #668 😎
