### ISSUE TITLE
Extract FPS for each video

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#623]
Seems like it could be useful 🤷‍♂️ 

If it's easy enough to grab it from the JSON object from FFprobe 🤔 

- Add as an extra field to `ImageElement`
- In _Details view_ display after the size, e.g. `| 18mb | 30fps | YYYY`
- Probably best to round to nearest integer (I hate `29.97` fps :trollface:  - so annoying) - so `24`, `30`, `60` etc
- Add _sort by_ filter for convenience 👍 

Open to a discussion 🤝

**Comment by jleckron** [comment]
Hi Boris, if this has not already been implemented, I would like to take a stab at it. Could you give me some guidance as to test this is working?

**Comment by whyboris** [comment]
The metadata extraction happens in this method: `extractMetadataAsync`
And we parse the JSON coming from `ffprobe` which should contain the FPS in there somewhere 😅 
https://github.com/whyboris/Video-Hub-App/blob/main/node/main-support.ts#L415

The FPS is likely going to look like this: https://stackoverflow.com/questions/7708373/get-ffmpeg-information-in-friendly-way
`"r_frame_rate": "30000/1001",` - "Real base framerate of the stream."

Store the `Math.round(fsp)` in the `ImageElement` and you're good to go 🚀 

Let's store it as `fps` -- just add an entry to the _Interface_
https://github.com/whyboris/Video-Hub-App/blob/main/interfaces/final-object.interface.ts#L27

Just add the `{{ video.fps }}` in this file: https://github.com/whyboris/Video-Hub-App/blob/main/src/app/components/meta/meta.component.html#L35 to see it working 😎

**Comment by jleckron** [comment]
Thank you for the help. I was having trouble finding the file where the fps was displayed, so that clears a lot up. How would I go about running a test environment of the application? I am probably doing this incorrectly, but when I open src/index.html in a browser, I get stuck on the loading animation.

**Comment by whyboris** [comment]
I didn't know videos can be variable FPS 😅 
I'm a little unsure. Are both available from `ffprobe` and you have to choose, or would one of them need to be computed manually? I'd opt for whatever `ffprobe` provides 🤷 I suspect the two are identical for 99.9% of the cases anyway 🤔 
Pick whichever of the two is most appropriate 🤝

**Comment by jleckron** [comment]
Ok sounds good. I am by no means an expert on video either, so I was just an unsure as you 😅
Both are provided by ffprobe, and it is very simply to switch between the two. I will stick with real frame rate for now, and I will use comments to make sure it is apparent how to switch if need be. Thank you!

**Comment by whyboris** [comment]
Thank you! 😁

**Comment by whyboris** [comment]
Thank you to @jleckron for implementing this feature 🚀 #635 🏅
