### ISSUE TITLE
Support Multiple Headings in Settings Tabs

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#63]
As far as I can see, right now you can only have a single heading in the settings tabs.

It would be nice, for example to have:

[Main Settings]
**Library Settings**
[] Quick Rescan
[] Full Rescan
[] Verify Thumbnails
**App Settings**
[] Start Wizard Again
[] Reset All Settings

Maybe this is possible already, but I couldn't see how to do it easily! 😄

**Comment by cal2195** [comment]
It would also be awesome to split the buttons into titles and descriptions: 
```
[] **Import New Files**
This will scan for new files only and import them, leaving current files alone.
```

**Comment by whyboris** [comment]
It's doable -- just a bit more work with some nesting of arrays probably.

The current organization was a fast-and-dirty one; it's worth organizing things better prior to release. Thank you for opening this issue 👍

**Comment by whyboris** [comment]
I'll be re-organizing the _menu_ as my next task 👍 
I'll see if some nesting is easy enough, or we have to settle for a simpler approach 😅

**Comment by cal2195** [comment]
In addition to my last comment about descriptions, it would be _very_ nice to have the description expand down on clicking on the text of the action, à la Unraid:

<img width="925" alt="screen shot 2019-01-23 at 16 57 03" src="https://user-images.githubusercontent.com/9119112/51624127-1d2fab80-1f32-11e9-909f-df34aa03e25c.png">

This would allow us to make lengthy descriptions if needed about functions, without crowding the settings! 👍

**Comment by whyboris** [comment]
I added an `i` _more info_ icon to the _auto tags_ description in the settings menu - please take a glance to see how it behaves visually (on hover). Please feel free to create a new issue if you think it would be better to handle the _more info_ differently 👌
