### ISSUE TITLE
Change/customize thumbnails/preview/clips

### ISSUE THREAD

**Issue by Gaibhne** [whyboris/Video-Hub-App#649]
It is unclear from the UI how, if at all, you can change/customize thumbnails, screenshots, previews and/or clips, either for specific files or for the entire collection.

The only way I have found is to completely start over with a new hub, losing all your various meta information such as ratings and tags.

If this is not yet possible at all, I would be a very welcome feature, especially the option to change the default for some files/folders. I would like to have one hub for all my media, but what I want out of thumbnails and previews changes depending on the files sizes, duration, content and so on.

**Comment by whyboris** [comment]
At the moment, the closest you can get to what you'd like is to create a hub where the number of screenshot depends on the length of the video (e.g. "1 screenshot every X minutes of video"). There is currently no per-folder or per-video way to change it. And there is no way to change it after creating the hub (other than deleting all the _filmstrips_ manually and editing the `.vha2` file in a text editor - changing the value).

The app always extracts at least 3 screenshots, and has an upper limit (depending on screenshot dimensions) so it will cap the maximum automatically as well. 

Adding a per-folder setting would require rewriting too much code to make it worth it. Adding a feature to change per-video screenshots is possible, but I can't see this feature being very useful.

I'm open to ideas and a discussion though 👂

**Comment by Gaibhne** [comment]
That's a shame; but I suppose I can change the text file before adding files and just keep my library well curated.

**Comment by whyboris** [comment]
Sorry about that. If you're comfortable with editing the code yourself (for your own build) I could help you with adding the feature you'd like.

Per-video number of images change could be very simple (the user interface is minimal; and you'd just need to add a function to delete a specific _filmstrip_ JPG file 👌 )

Do let me know -- I'll be happy to help 😄

**Comment by whyboris** [comment]
ps - editing the `.vha2` file is easy -- it's a `JSON` formatted text file. Search for `"n":` and you'll find what you need to change. 

The interface: https://github.com/whyboris/Video-Hub-App/blob/main/interfaces/final-object.interface.ts#L98

Note, the `fixed: boolean;` -- if `true` then it's a fixed number of screenshots per video, if `false` then it's "number of minutes between screenshots" 👍
