### ISSUE TITLE
Please can we have a 'quit' option from top menu on Mac

### ISSUE THREAD

**Issue by jamesfpb** [whyboris/Video-Hub-App#652]
![image](https://user-images.githubusercontent.com/43941948/115067469-d5482680-9ea5-11eb-9d80-8b9a6a3e82eb.png)
Using OS Catalina

**Comment by whyboris** [comment]
Thank you for the suggestion. Will be happy to accept a PR for it 👍 

ps - FYI you can already use the keyboard shortcuts `CMD` + `W` or `CMD` + `Q`
