### ISSUE TITLE
Add support for (Blu-ray MPEG-2 Transport Stream files) .m2ts

### ISSUE THREAD

**Issue by idk** [whyboris/Video-Hub-App#654]
M2TS is a filename extension used for the Blu-ray Disc Audio-Video MPEG-2 Transport Stream container file format. It is used for multiplexing audio, video and other streams. It is based on the MPEG-2 transport stream container. This container format is commonly used for high definition video on Blu-ray Disc and AVCHD.

Most video players can play .m2ts files.

**Comment by whyboris** [comment]
There's now a place in the settings (3rd tab) where users can add their own extensions so that the app scans them in 👍 

Alternatively, we just need to add just one more string here 👍 
https://github.com/whyboris/Video-Hub-App/blob/main/node/main-filenames.ts#L22

**Comment by idk** [comment]
Aha, nice feature. Adding the extension worked as intended, thanks. Will leave it up to you to close/not close this issue.

**Comment by whyboris** [comment]
closed with commit https://github.com/whyboris/Video-Hub-App/commit/ff9e17ef9f0299171ecaf459cad09abe0a84d088
