### ISSUE TITLE
Compact view option also for filmstrip view

### ISSUE THREAD

**Issue by dia3olik** [whyboris/Video-Hub-App#684]
Hey Boris, I think it would be great to enable the compact view also for filmstrip view, to have the view uncluttered with no blank space top/bottom of the filmstrips, just a nice wall of filmstrips as compact as possible with no UI space wasted ;-)

Thanks as always!

**Comment by whyboris** [comment]
Thank you for the suggestion - seems doable (re-use the already-present "compact view") 👍 
PR welcome 🤝
