### ISSUE TITLE
Alphabetize "Videos located here:" folders

### ISSUE THREAD

**Issue by fire838** [whyboris/Video-Hub-App#687]
This will make it easier to keep track which folder are already in. Also make a way to add more than one folder at a time?

**Comment by whyboris** [comment]
It's a nice improvement (to the 4th tab in settings) -- will be happy to accept a `PR` for this change.
The best way to handle it would be to create a dedicated _pipe_ that alphabetizes the list.

**Comment by alzbuc** [comment]
Hi @whyboris I would like to work on this issue. Could you please assign it to me?

**Comment by alzbuc** [comment]
I created a pull request #703 with implemented OrderBy pipe.

**Comment by whyboris** [comment]
Thank you @alzbuc -- I had trouble resolving a conflict and merging, so I created a PR based off your code #797 and merged it in.

All credit goes to you -- thank you for the great PR!

**Comment by whyboris** [comment]
Closed with #797 (and #703 -- code written by @alzbuc ) 🙇
