### ISSUE TITLE
Sort by alphabetical doesn't sort correctly

### ISSUE THREAD

**Issue by fire838** [whyboris/Video-Hub-App#688]
https://i.imgur.com/lug7QMq.png

Should be: 

red [1080p] - cool    |    red [720p] - cool    |    red [480p] - cool

**Comment by whyboris** [comment]
I added `Alphabetical 2` - a slower sort, but it gets the number order correctly -- please give it a glance (enable in settings) 🤝 

Please let me know if that doesn't work as expected.
