### ISSUE TITLE
Dark mode year of video needs to be visible

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#690]
Currently the font stays black, making the year invisible in dark mode 😓 

ps - "times played" is also barely visible 😅

**Comment by PriyanshX1902** [comment]
@whyboris Can I work on this as my first PR?

**Comment by whyboris** [comment]
Hey @PriyanshX1902 - thank you! 
Please feel free to reach out if you have any questions - I'll be happy to help 🤝

**Comment by ryanleigh410** [comment]
Hey @whyboris! Is this issue still being worked on? If not, I'd love to take a look.  Thanks!

**Comment by whyboris** [comment]
@ryanleigh410 -- thank you for the offer! I don't believe anyone is working on this issue at the moment - please feel free to take a look.

Do let me know if you have any questions -- I'll be happy to help 🤝

**Comment by whyboris** [comment]
Thank you @ryanleigh410 for the fix 🎉  #704 🙇
