### ISSUE TITLE
CMD+H and CMD+M not working on Mac

### ISSUE THREAD

**Issue by dia3olik** [whyboris/Video-Hub-App#691]
Hey Boris!

I just discovered these two shortcuts don't work with VHA3.

Every app systemwide usually adheres to at least these 2 shortcuts to HIDE and MINIMIZE the App.

Is there a chance to see these implemented like other Mac Apps?

Thanks!!!!

**Comment by whyboris** [comment]
Thank you @flpcury for your fix PR 🙇 it works great 🎉
Thanks for your patience - took me a while to get to review it 🤝
