### ISSUE TITLE
Snap zoom levels to use full space available

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#71]
@whyboris 
Wanted to get your opinion on this! 👍 

I don't really see a point in zooming arbitrary levels (+-25px I think atm), since most of those won't use the full space of the viewport.

I would like the zoom to change the number of files displayed in one row, filling the entire row - what do you think of this?

**Comment by cal2195** [comment]
You can see how this would work in #72! 👍

**Comment by cal2195** [comment]
I have this feature under way! 😃 Will also bundle in some overall zooming/view improvements! 👍

**Comment by whyboris** [comment]
Thank you Cal for #170 -- it implements the solution to this issue beautifully 🙇
