### ISSUE TITLE
Silicone Version for M1 M2 etc 

### ISSUE THREAD

**Issue by mrdogcat** [whyboris/Video-Hub-App#711]
Will you be producing an Apple Silicone version of the app for users running those flava of Macintosh?

**Comment by whyboris** [comment]
Thank you for the request. This is something I _want_ to do.

I will need to first acquire an Apple Silicon laptop to create that version. 

I might get a new laptop from work next year; if so, I'd be able to do it then.

**Comment by whyboris** [comment]
✅ `M1` build ready - part of the `3.2.0` _Fifth Anniversary_ release 🥳 
😅 now I just have to figure out how to build an _Intel_ version on a Mac (I now only have an `M1` Mac) 🤞
