### ISSUE TITLE
Add kb/s for videos in details

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#712]
Seems easy to add, may be useful to some 🤔

**Comment by jozefkopcak** [comment]
Hello, could I be assigned to this issue? :)

**Comment by jozefkopcak** [comment]
Hello Boris, I'm a bit lost in the project. I have inserted "bitrate" to ImageElement interface and have made function getBitrate in main-support.ts. I am struggling with what to do next, I can't find where exactly to use it now to make it show in video details. Could you help me? :)

**Comment by whyboris** [comment]
You're doing great! I'm glad you were able to get the bitrate from the `FFprobe` output 🎉 

The last part should be rather straight-forward 🤞 
Once the bitrate is part of the ImageElement - you just have to display it:
https://github.com/whyboris/Video-Hub-App/blob/main/src/app/components/meta/meta.component.html#L37
Add a line there and it should show up for every _details_ view 😎

**Comment by jozefkopcak** [comment]
![image](https://user-images.githubusercontent.com/63211669/145851647-b220f182-b6f3-4940-93f9-c370aa86a68e.png)

I think i got it, my formula for calculating bitrate was ((fileSize/1000)/duration). Do u want it like that? Ot should i change it to ((fileSize/1024)/duration)? In the end, I rounded it up, so it looks better.

**Comment by whyboris** [comment]
Looks great 😍 

Rounding up is a great idea. Calculation I'm unsure whether `1000` or `1024` is the right approach - I wonder if Windows does it correctly (when you right-click on video, go to _details_ and see the bitrate). But don't sweat it too much, I could double-check later too 👌 

I wonder if it's most-common nowadays to have bitrates of closer to 5,000 - so maybe `mb/s` rather than `kb/s` is better? 🤔

**Comment by jozefkopcak** [comment]
![image](https://user-images.githubusercontent.com/63211669/145854120-d2358291-4e34-4399-b04d-936f95b779b8.png)

(my windows is in my native language, dont get too scared :D )
So, windows shows in video details, that bitrate is 1205 kbps which converted to kb/s is 150.6, rounded up is 151 kb/s.

![image](https://user-images.githubusercontent.com/63211669/145854334-b62592c0-6e6e-44d8-ac3e-3863b6094936.png)

So that means, my calculations should be okay :D 

If u want mb/s, it's not a problem. I know, when u have like 60GB Blurays, it can be a bit too much numbers :D

**Comment by jozefkopcak** [comment]
![image](https://user-images.githubusercontent.com/63211669/145885245-de318134-30d3-4d71-af21-0d6dfa2d8053.png)

This is what I got now :) Should I create pull request, so you can take a look? :)

**Comment by whyboris** [comment]
Looks beautiful! I bet I'll accept the PR with no requests for modification 😉 🤝 😁

**Comment by whyboris** [comment]
Thank you for the PR 🙇 #714 -- looking forward to merging soon 😁

**Comment by whyboris** [comment]
Thank you @jozefkopcak for adding this feature to _Video Hub App_ 🎉 
I appreciate it 😊
