### ISSUE TITLE
Make Times Played visible in dark mode

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#719]
😓 current bug: in _Dark Mode_ in the _Details view_ the "Times played" is not visible (black on black 😅 )

Should be an easy fix 🚀

**Comment by arcadioramos** [comment]
I'm working on this issue, I'll made the pr as soon as possible

**Comment by whyboris** [comment]
Thank you @arcadioramos 🙇 for the fix #720 🎉
