### ISSUE TITLE
filter "folder does not have"

### ISSUE THREAD

**Issue by Orthos79** [whyboris/Video-Hub-App#726]
Hey!

I would like to have a filter named "folder does not have" to exclude one or more specific folders. Could that be possible?

Marc

**Comment by Orthos79** [comment]
:)

**Comment by rokaicker** [comment]
Hi, would it be okay if I look into working on this this?

**Comment by whyboris** [comment]
Hey @rokaicker -- thank you for offering to try this out. 🤝  Please let me know if you have any trouble working on this.
I'm away to [GopherCon](https://www.gophercon.com/home) this week so I won't be able to respond until Monday the 10th.
Glance around the code to see how similar filters were created. Good luck 😊

**Comment by whyboris** [comment]
Fixed with #772 & #767 🤝
