### ISSUE TITLE
OR operator

### ISSUE THREAD

**Issue by darktrend** [whyboris/Video-Hub-App#733]
Hi whyboris, I think it would be useful to have an OR operator.

![01](https://user-images.githubusercontent.com/32552575/154817480-39a72b4d-668a-4da7-bf4c-1dfaa09133ae.jpg)
![02](https://user-images.githubusercontent.com/32552575/154817481-47b985d6-7d5a-464c-9659-016fade4a322.jpg)
![03](https://user-images.githubusercontent.com/32552575/154817483-c33a15bd-cb86-45b0-bcf5-f418de5991f1.jpg)

I added circles around them to indicate that they are clickable elements, alternatively underlining would also indicate interactivity.

**Comment by whyboris** [comment]
Interesting idea!

_Note:_ at the moment there _is_ an `or` search - you just have to enable it in the settings (1st tab) "File name with each" vs "File name with any". 

As soon as you start mixing "and" & "or" in one sentence, I think you need parentheses for clarity, which would complicate things.

At the moment in the app there isn't a way to perform a complex search that mixes "and" & "or" - but allowing toggling of the and/or would be quite a large rewrite I think 🤔 so I'm reluctant to try at this time.

In the example case you give, the closest we could do is perform two searches "mario and luigi" and later, independently, clearing the search results, search for "bowser". It's not as good as what you propose, but I hope it works well enough when the desire strikes 😅

**Comment by darktrend** [comment]
Oh you're right, I can use the any function to get the same outcome of what I was trying to do. 

thanks!
