### ISSUE TITLE
No Results Found - Apple M1

### ISSUE THREAD

**Issue by Gavriik** [whyboris/Video-Hub-App#744]
Thumbnails are not generated, but looking at the terminal I can see that it does find the files. What could be the problem?

![screenshot](https://user-images.githubusercontent.com/16233200/159552028-3786fa4a-2493-4b04-acb4-a584aadb2c28.png)
)

**Comment by whyboris** [comment]
Thank you for the bug report. I was not able to replicate on my M1 machine when using the downloaded demo.
I will test again just in case when I build the app from source (at least before the next release).

I am unsure what could be going wrong.
- Did the videos happen to appear after the progress bar finished (shows 86% in your screenshot)?
- Does the accompanying _vha-[hub name]_ folder `/thumbnails` contain images?
- Have you tried again just in case -- did anything change?

Thank you for your feedback 🙇

**Comment by newadventure079** [comment]
This isn't m1-specific. I have an m1 and it works just fine

**Comment by gspinoza** [comment]
> * Did the videos happen to appear after the progress bar finished (shows 86% in your screenshot)?
> * Does the accompanying _vha-[hub name]_ folder `/thumbnails` contain images?
> * Have you tried again just in case -- did anything change?

* It gets stuck at that percentage, and no videos are generated.
* all folders are empty (thumbnails, filmstrips, and clips).
* I tried multiple times and not luck

btw, I used the main branch current code to build the app if that helps.
I'm not sure what could be the problem really.

**Comment by Gavriik** [comment]
> * Did the videos happen to appear after the progress bar finished (shows 86% in your screenshot)?
> * Does the accompanying _vha-[hub name]_ folder `/thumbnails` contain images?
> * Have you tried again just in case -- did anything change?

* It gets stuck at that percentage, and no videos are generated.
* all folders are empty (thumbnails, filmstrips, and clips).
* I tried multiple times and not luck

btw, I used the main branch current code to build the app if that helps.
I'm not sure what could be the problem really.

**Comment by whyboris** [comment]
Thank you for the update - I'll try to replicate on the `main` branch (it's ahead of the last release, so I may have messed something up already 😅 ) 

My intention is to bump up all the dependencies including `FFmpeg` which might give us some wins 🤞 I have created some PRs - maybe in a month I'll be able to get it all out 😓 (busy times with house stuff currently)

**Comment by Gavriik** [comment]
Great! I hope the new version of `FFmpeg` will make things much faster.  Thanks a lot for still maintaining this project even when you are busy.

**Comment by whyboris** [comment]
@Gavriik -- I just merged `FFmpeg` version 5 into the `main` branch 🎉 

ps - it seems to work on PC but fails on M1 Mac at the moment (I haven't tested extensively yet)

**Comment by Gavriik** [comment]
Great! everything seems to be working fine now on my M1 machine.  Thank you for the update!
