### ISSUE TITLE
Add Debug Flag for Verbose Output!

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#75]
When testing, it's important to get as much output about ffmpeg and the like as possible - so if something goes wrong, we can trace it to the source as quickly as possible!

There should be a flag to enable debug output for this purpose! 👍

**Comment by whyboris** [comment]
I don't mind a flag at all. Though ffmpeg pumps out so much detail when it runs, I imagine we wouldn't want the flag to toggle the output at every stage (generating screenshots, generating short preview video). 

At the moment the relevant logging functionality is simply commented out -- seems easy enough to comment it back in.

Up to you 👍

**Comment by cal2195** [comment]
I'd actually like all the output! I primarily use this for debugging when we're making changes to the Ffmpeg flow, so I leave it running for a few hours, and if it's stuck when I return, I need to know exactly what went wrong! 👍 

I'll have a look into this!

**Comment by whyboris** [comment]
I won't oppose a PR at all - you know me 😉
