### ISSUE TITLE
Folder size indicator show "k" when over 1,000

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#757]
_During "folder view"_

When there are more than 999 files in a folder, maybe show `1k`, `2k` etc - otherwise the number spills over the folder icon 😅

**Comment by jmdagenais** [comment]
Can I work on this issue?

**Comment by whyboris** [comment]
Hey @jmdagenais - thank you for the offer of help 😊 

Please let me know if you have any trouble while working on this -- I'll be happy to advise on anything 🤝

**Comment by jmdagenais** [comment]
@whyboris How can I acces the "folder view"?

**Comment by whyboris** [comment]
Thank you @jmdagenais for the `hacktoberfest` submission 🎉  - #769 🤝

**Comment by whyboris** [comment]
Closed with #760 and #769 🤝
