### ISSUE TITLE
Upgrade to Angular 14 🎉 

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#761]
😎 should be easy 😎

**Comment by paulchodev** [comment]
Hi, I would like to work on this issue if it's still available

**Comment by whyboris** [comment]
Hey @paulchodev -- thank you for the offer -- feel free to give this a shot; let me know if you have any trouble 🤝 

Please make sure your _Node_ is at least version 16 and your _npm_ is at least version 8 when you upgrade dependencies 🙇

**Comment by paulchodev** [comment]
After trying a few different methods to update(got incompatible peer dependencies error) I think I finally got it to work and submitted a pr. Please let me know if I did something wrong or if I need to fix something. Thank you

**Comment by whyboris** [comment]
🤝 thank you for the PR: #766 -- it's looking great. I'll merge it in hopefully within a month (when I finally get back to VHA development) 👍
