### ISSUE TITLE
Sorting by recently added

### ISSUE THREAD

**Issue by cal2195** [whyboris/Video-Hub-App#80]
One nice feature would be to be able to sort by most recent added! 🎞 

I think we'd need to add a "datetime-added" field into the vha file for this? 👍

**Comment by whyboris** [comment]
Thank you for adding this issue -- it was on my _todo_ list -- good to have tracking of progress here 👍

**Comment by whyboris** [comment]
Tracking it here: https://github.com/whyboris/Video-Hub-App/issues/99#issuecomment-455748586
Closing the issue to clean up the board 😅
